import 'dart:convert';

import 'package:flutter/foundation.dart';

import '../util/file_moderation.dart';
import '../util/photo_prep.dart';

/// Something the user hands to Okay AI to look at — a photo or a text file.
///
/// KNOWINGLY HOSTED, like the rest of the assistant. A human chat's contents
/// are end-to-end encrypted and must never reach a server that can read them;
/// an attachment the user picks HERE is the opposite by choice — they are
/// deliberately showing it to the machine, the same carve-out that lets the
/// assistant read what they type. Only what the user explicitly attaches to the
/// assistant is ever sent; nothing reaches into a chat.
///
/// Two kinds, because a hosted chat model can take exactly two things: an
/// IMAGE (sent to a vision model as a `data:` URL) and TEXT (a text file, whose
/// content is folded into the message). Anything else — a video, a PDF, an
/// archive, an executable — is refused with a plain reason, because the model
/// cannot read raw bytes and pretending otherwise burns a paid call on nothing.
@immutable
class AiAttachment {
  /// 'image' or 'text'.
  final String kind;
  final String name;

  /// Image only: the full-size `data:image/jpeg;base64,…` sent to the model.
  final String imageDataUri;

  /// Image only: a small `data:` thumbnail kept in the saved conversation for
  /// display, so the bubble shows the photo without storing the full image.
  final String thumbDataUri;

  /// Text only: the decoded file content, folded into the model message.
  final String text;

  const AiAttachment._({
    required this.kind,
    required this.name,
    this.imageDataUri = '',
    this.thumbDataUri = '',
    this.text = '',
  });

  bool get isImage => kind == 'image';

  /// Per-file cap on text folded into a message, so a giant log can't blow the
  /// token budget. Generous enough for ordinary notes, code and CSVs.
  static const int maxTextChars = 12000;

  /// Prepares a picked file for the assistant, or throws [FileRejected] with a
  /// reason the UI can show. Pure and deterministic, so the classification is
  /// unit-testable with generated bytes.
  ///
  ///  * a real image → resized to a vision-sized `data:` URI plus a small thumb;
  ///  * a text file → its decoded content (capped);
  ///  * anything else (video, PDF, archive, executable, binary) → refused.
  static AiAttachment prepare(Uint8List bytes, String name) {
    final display = name.trim().isEmpty ? 'Attachment' : name.trim();
    // Nothing the user attaches skips moderation — the same gate every other
    // out-of-device path uses. It rejects executables, scripts and oversize
    // files, and tells us what the bytes actually are.
    final verdict = FileModeration.inspectFile(bytes);
    if (!verdict.allowed) throw FileRejected(verdict.reason!);
    final kind = verdict.kind;

    if (FileModeration.allowedImageKinds.contains(kind)) {
      final full = PhotoPrep.prepare(bytes);
      if (full == null) throw FileRejected('That image couldn\'t be read.');
      // A separate, tiny thumbnail for history; falls back to the full image
      // if a pathological picture won't shrink that far.
      final thumb = PhotoPrep.prepare(bytes, maxBase64: 12000) ?? full;
      return AiAttachment._(
        kind: 'image',
        name: display,
        imageDataUri: full,
        thumbDataUri: thumb,
      );
    }

    if (kind == 'text') {
      var content = utf8.decode(bytes, allowMalformed: true).trim();
      if (content.isEmpty) throw FileRejected('That file is empty.');
      if (content.length > maxTextChars) {
        content = '${content.substring(0, maxTextChars)}\n…(truncated)';
      }
      return AiAttachment._(kind: 'text', name: display, text: content);
    }

    // pdf, zip, and anything else moderation lets through as a document: the
    // model can't read these as raw bytes, so say so rather than send nothing.
    throw FileRejected(
        'Okay AI can look at images and read text files, but not $kind files.');
  }
}
