import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// The on-device half of "write a message for me": the same one-shot draft
/// `AiAssistant.draft()` offers, generated by Apple's model on this phone
/// through `okay/aidraft` instead of the hosted `ai-chat` function.
///
/// Deliberately as narrow as [SmartReplies]: this channel is handed an
/// INSTRUCTION and nothing else — never a conversation — so it has no way to
/// become a second path into a human chat even if something later tried to
/// widen it. There is no network path in this file and there must never be
/// one; `AiAssistant.draft()` is what falls back to the hosted function when
/// this declines.
class OnDeviceDraft {
  OnDeviceDraft._();

  static final OnDeviceDraft instance = OnDeviceDraft._();

  static const MethodChannel _channel = MethodChannel('okay/aidraft');

  bool? _available;

  /// Whether this device can draft on its own. False on the web build, on
  /// Android, and on any iPhone without Apple Intelligence — which is most of
  /// them — so [AiAssistant.draft] has to treat "no" as the ordinary case and
  /// fall back to the hosted function rather than surface an error. Asked
  /// once and remembered, same as [SmartReplies.available].
  Future<bool> get available async {
    if (_available != null) return _available!;
    if (debugAvailableOverride != null) return debugAvailableOverride!;
    if (kIsWeb || defaultTargetPlatform != TargetPlatform.iOS) {
      return _available = false;
    }
    try {
      final ok = await _channel.invokeMethod<bool>('available');
      return _available = ok ?? false;
    } on PlatformException {
      return _available = false;
    } on MissingPluginException {
      // An older build of the app shell without the channel compiled in.
      return _available = false;
    }
  }

  /// Drafts a message for [instruction], or null when the device declined —
  /// no Apple Intelligence, a guardrail refusal, or the channel is missing.
  /// null is a normal answer here, not a failure: the caller falls back to
  /// the hosted function, so nothing the user typed is ever lost to it.
  Future<String?> draft(String instruction) async {
    final t = instruction.trim();
    if (t.isEmpty) return null;
    if (!await available) return null;
    try {
      final override = debugDraftOverride;
      final text = override != null
          ? await override(t)
          : await _channel.invokeMethod<String>('draft', {'instruction': t});
      final trimmed = text?.trim();
      return (trimmed == null || trimmed.isEmpty) ? null : trimmed;
    } on PlatformException {
      return null;
    } on MissingPluginException {
      return null;
    }
  }

  /// Test hooks. The real path needs an iPhone with Apple Intelligence, which
  /// no test runner has.
  @visibleForTesting
  static bool? debugAvailableOverride;

  /// Stands in for the platform channel's raw answer — including a null one.
  @visibleForTesting
  static Future<String?> Function(String instruction)? debugDraftOverride;

  @visibleForTesting
  void resetForTest() {
    _available = null;
    debugAvailableOverride = null;
    debugDraftOverride = null;
  }
}
