// PASTE-READY, self-contained version of ai-chat for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: ai-chat
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/ai-chat/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

// The app's built-in AI assistant — "Okay AI", a general-purpose helper the
// user chats with directly, in the shape of Grok or Claude.
//
// POST { messages: [{ role: 'user'|'assistant', content }], } -> { reply, configured }
//
// ENGINE: OpenRouter (chat completions), the same provider the feed moderator
// already uses. Billed per token, so the model is overridable with the
// OPENROUTER_AI_MODEL secret (a capable default, distinct from the cheap
// classifier model moderation runs on).
//
// WHY THIS IS ALLOWED TO LEAVE THE DEVICE. Everything people write TO EACH
// OTHER in this app is end-to-end encrypted and must never reach a server that
// can read it. This is different in kind: the user is knowingly talking to an
// assistant, not to a person whose privacy is being protected — the same
// reasoning that lets the public feed use a hosted model. The assistant only
// ever sees what the user types INTO the assistant chat; it is walled off from
// every human-to-human conversation. Do not wire this to chats or server feeds.
//
// INERT WITHOUT A KEY. With no OPENROUTER_API_KEY set this returns
// { reply: '', configured: false } and the client says the assistant isn't set
// up yet — never a crash.


const DEFAULT_MODEL = "openai/gpt-4o-mini";

// How the assistant behaves. Deliberately plain and helpful — a general
// assistant, not a character.
const SYSTEM = `You are Okay AI, the friendly built-in assistant of the ` +
  `OkayMessenger app. You are helpful, honest, and concise. Answer clearly, ` +
  `admit when you are unsure, and never claim to be a human. You cannot read ` +
  `the user's private chats or personal data — you only see what they type to ` +
  `you here. If asked to do something you cannot, say so plainly.`;

// The assistant "learns as it talks" by remembering durable facts about THIS
// user. It answers in "reply" and, in "remember", returns any NEW, stable,
// genuinely-useful fact worth recalling next time (a name, a preference, an
// ongoing project) — [] almost always. It must NOT remember anything
// sensitive (health, finances, credentials, precise location) or anything that
// is just this-message chatter.
const FORMAT = `Respond ONLY with a JSON object of this exact shape and ` +
  `nothing else:\n{"reply": "<your answer to the user>", ` +
  `"remember": ["<a durable fact about the user worth recalling>", ...]}\n` +
  `Keep "remember" empty unless there is a genuinely new, stable, useful, ` +
  `non-sensitive fact about the user. Never put sensitive data ` +
  `(health, money, passwords, exact location) in "remember".`;

function memoryPreamble(memories: string[]): string {
  if (memories.length === 0) return "";
  const lines = memories.slice(0, 60).map((m) => `- ${m}`).join("\n");
  return `\n\nHere is what you already remember about this user; use it ` +
    `naturally when relevant, and do not repeat it back as a list:\n${lines}`;
}

// A sane ceiling so one runaway conversation can't send a novel to the model.
const MAX_MESSAGES = 24;
const MAX_CHARS_PER_MESSAGE = 4000;

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  let body: Record<string, unknown> = {};
  try {
    body = await req.json();
  } catch {
    return json({ error: "bad_json" }, 400);
  }

  const raw = Array.isArray(body.messages) ? body.messages : [];
  const history: { role: string; content: string }[] = [];
  for (const m of raw) {
    if (typeof m !== "object" || m === null) continue;
    const role = String((m as Record<string, unknown>).role ?? "");
    let content = String((m as Record<string, unknown>).content ?? "").trim();
    if (content.length === 0) continue;
    if (role !== "user" && role !== "assistant") continue;
    if (content.length > MAX_CHARS_PER_MESSAGE) {
      content = content.slice(0, MAX_CHARS_PER_MESSAGE);
    }
    history.push({ role, content });
  }
  const trimmed = history.slice(-MAX_MESSAGES);
  if (trimmed.length === 0 || trimmed[trimmed.length - 1].role !== "user") {
    return json({ error: "no user message" }, 400);
  }

  // The user's on-device memory, sent as context so the assistant "knows"
  // them. Learning is opt-out per request: draft() sends none.
  const memories: string[] = [];
  const rawMem = Array.isArray(body.memories) ? body.memories : [];
  for (const m of rawMem) {
    const s = String(m ?? "").trim();
    if (s.length > 0 && s.length <= 200) memories.push(s);
  }
  // The one-shot draft path asks for a plain reply and no learning.
  const learn = body.learn !== false;

  const key = Deno.env.get("OPENROUTER_API_KEY") ?? "";
  if (!key) return json({ reply: "", configured: false });

  // Server-side rate limit — the real cost control, since the client's free
  // tier can be bypassed by a modified app. Counted per caller (their phone
  // when signed in, else the request IP) and checked BEFORE the model call, so
  // an over-cap request spends no tokens. Fails OPEN if the tally table isn't
  // set up, so a missing migration never breaks the assistant.
  const cap = parseInt(Deno.env.get("AI_DAILY_CAP") ?? "40", 10);
  if (cap > 0) {
    const me = (await callerPhone(req)) ?? "";
    const ip = (req.headers.get("x-forwarded-for") ?? "")
      .split(",")[0].trim();
    const usageKey = me || ip || "anon";
    try {
      const { data, error } = await admin.rpc("ai_note_usage", {
        k: usageKey,
      });
      if (!error && typeof data === "number" && data > cap) {
        return json({ error: "rate_limited", configured: true }, 429);
      }
    } catch (_) {
      // Table/RPC not deployed — fail open, no ceiling until it exists.
    }
  }

  try {
    const model = Deno.env.get("OPENROUTER_AI_MODEL") ||
      Deno.env.get("OPENROUTER_MODEL") || DEFAULT_MODEL;
    const system = learn
      ? SYSTEM + memoryPreamble(memories) + "\n\n" + FORMAT
      : SYSTEM + memoryPreamble(memories);
    const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "authorization": `Bearer ${key}`,
      },
      body: JSON.stringify({
        model,
        temperature: 0.7,
        ...(learn ? { response_format: { type: "json_object" } } : {}),
        messages: [
          { role: "system", content: system },
          ...trimmed,
        ],
      }),
    });
    if (!res.ok) {
      console.error("ai-chat: openrouter", res.status);
      return json({ reply: "", configured: true, degraded: true });
    }
    const data = await res.json();
    const content = String(data.choices?.[0]?.message?.content ?? "").trim();
    if (!content) {
      return json({ reply: "", configured: true, degraded: true });
    }
    if (!learn) return json({ reply: content, configured: true });

    // Learning turn: the content is a JSON object with reply + remember. If it
    // somehow isn't, fall back to treating it as the reply so the chat never
    // dead-ends on a formatting hiccup.
    let reply = "";
    let remember: string[] = [];
    try {
      const parsed = JSON.parse(content);
      reply = String(parsed.reply ?? "").trim();
      if (Array.isArray(parsed.remember)) {
        remember = parsed.remember
          .map((r: unknown) => String(r ?? "").trim())
          .filter((r: string) => r.length > 0 && r.length <= 200)
          .slice(0, 8);
      }
    } catch {
      reply = content;
    }
    if (!reply) return json({ reply: "", configured: true, degraded: true });
    return json({ reply, memories: remember, configured: true });
  } catch (e) {
    console.error("ai-chat: failed", String(e));
    return json({ reply: "", configured: true, degraded: true });
  }
});
