// PASTE-READY, self-contained version of ai-chat for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: ai-chat
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/ai-chat/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

// The app's built-in AI assistant — "Okay AI", a general-purpose helper the
// user chats with directly, in the shape of Grok or Claude.
//
// POST { messages: [{ role: 'user'|'assistant', content }], } -> { reply, configured }
//
// content is either a string (a plain message) or, for a user turn carrying
// attachments, an array of parts: { type: 'text', text } and
// { type: 'image_url', image_url: { url: 'data:image/…' } }. That is the
// OpenRouter/OpenAI vision shape, so an image the user hands the assistant is
// seen by a vision-capable model; a text file's content arrives folded into a
// text part. Only user turns may carry images.
//
// ENGINE: OpenRouter (chat completions), the same provider the feed moderator
// already uses. Billed per token, so the model is overridable with the
// OPENROUTER_AI_MODEL secret (a capable default, distinct from the cheap
// classifier model moderation runs on). The default model is vision-capable;
// if OPENROUTER_AI_MODEL is pointed at one that is not, images are ignored by
// the provider.
//
// WHY THIS IS ALLOWED TO LEAVE THE DEVICE. Everything people write TO EACH
// OTHER in this app is end-to-end encrypted and must never reach a server that
// can read it. This is different in kind: the user is knowingly talking to an
// assistant, not to a person whose privacy is being protected — the same
// reasoning that lets the public feed use a hosted model. The assistant only
// ever sees what the user types INTO the assistant chat; it is walled off from
// every human-to-human conversation. Do not wire this to chats or server feeds.
//
// INERT WITHOUT A KEY. With no OPENROUTER_API_KEY set this returns
// { reply: '', configured: false } and the client says the assistant isn't set
// up yet — never a crash.


// A capable, vision-capable default so answers are accurate and code is solid
// out of the box (the old gpt-4o-mini default was weak at both). Overridable
// with OPENROUTER_AI_MODEL — point it at a stronger coding/reasoning model, or
// a cheaper one, as the owner prefers; it MUST stay vision-capable for the
// image-attachment feature to keep working.
const DEFAULT_MODEL = "openai/gpt-4o";

// How the assistant behaves. Deliberately plain and helpful — a general
// assistant, not a character.
const SYSTEM = `You are Okay AI, the built-in assistant of the OkayMessenger ` +
  `app — a powerful, general-purpose assistant on the level of ChatGPT, Claude ` +
  `or Grok. You are never a human, and you cannot read the user's private chats ` +
  `or act inside the app on their behalf (you only see what they type to you ` +
  `here, plus any image or text file they attach). Within that, you are ` +
  `capable and willing across EVERYTHING: coding, math, science, writing, ` +
  `analysis, business, languages, advice — any subject, any task.\n\n` +
  `BE FULLY HELPFUL. Take on what the user actually asked and DELIVER it — do ` +
  `not deflect, downplay your ability, or offer only "snippets and guidance" ` +
  `when they asked you to build something. If they ask you to write a whole ` +
  `app, write the whole app. Do not lecture, moralize, or add needless ` +
  `disclaimers. Match length to the task: full and complete when the work ` +
  `needs it, brief when a short answer will do.\n\n` +
  `ACCURACY: reason step by step on hard problems before answering, and base ` +
  `answers on well-established facts. Never invent sources, quotes, numbers, or ` +
  `APIs. If you are genuinely unsure, or the answer depends on recent or ` +
  `changeable information you may not have, say so plainly instead of guessing, ` +
  `and separate what you know from what you are inferring.\n\n` +
  `CODING: write complete, correct, runnable code in fenced blocks tagged with ` +
  `the language (\`\`\`dart, \`\`\`python, …). Give whole files or projects when ` +
  `asked — not fragments. Use standard idioms, handle the obvious edge cases, ` +
  `state any assumption a request left open, and note real pitfalls. Never omit ` +
  `code needed to run.`;

// The assistant "learns as it talks" by remembering durable facts about THIS
// user. It answers in "reply" and, in "remember", returns any NEW, stable,
// genuinely-useful fact worth recalling next time (a name, a preference, an
// ongoing project) — [] almost always. It must NOT remember anything
// sensitive (health, finances, credentials, precise location) or anything that
// is just this-message chatter.
const FORMAT = `Respond ONLY with a JSON object of this exact shape and ` +
  `nothing else:\n{"reply": "<your answer to the user>", ` +
  `"remember": ["<a durable fact about the user worth recalling>", ...]}\n` +
  `Keep "remember" empty unless there is a genuinely new, stable, useful, ` +
  `non-sensitive fact about the user. Never put sensitive data ` +
  `(health, money, passwords, exact location) in "remember".`;

// The memory half of what FORMAT used to ask for in one breath, as its own
// prompt. Asked of a cheap model, after the answer is already on screen.
const REMEMBER = `You are a memory extractor for a chat assistant. Read the ` +
  `conversation and return ONLY a JSON object of this exact shape:\n` +
  `{"remember": ["<a durable fact about the user worth recalling>", ...]}\n` +
  `Return [] unless there is a genuinely NEW, stable, useful, non-sensitive ` +
  `fact about the user — a name, a preference, an ongoing project. Never ` +
  `include anything sensitive (health, money, credentials, exact location), ` +
  `anything that is just this-message chatter, and nothing already listed as ` +
  `remembered below.`;

function memoryPreamble(memories: string[]): string {
  if (memories.length === 0) return "";
  const lines = memories.slice(0, 60).map((m) => `- ${m}`).join("\n");
  return `\n\nHere is what you already remember about this user; use it ` +
    `naturally when relevant, and do not repeat it back as a list:\n${lines}`;
}

// Pulls the reply (and any memory) out of a learning-turn response. Normally
// that content is a clean JSON object; but a very long answer — a whole app —
// can be cut off at max_tokens, leaving TRUNCATED JSON that won't parse. Rather
// than dump raw JSON on the user or lose the answer, salvage the reply field
// from the wrapper, and only as a last resort show the content verbatim. So a
// long answer is never lost to a formatting hiccup.
function unwrapReply(content: string): { reply: string; remember: string[] } {
  try {
    const parsed = JSON.parse(content);
    const reply = String(parsed.reply ?? "").trim();
    const remember = Array.isArray(parsed.remember)
      ? parsed.remember
        .map((r: unknown) => String(r ?? "").trim())
        .filter((r: string) => r.length > 0 && r.length <= 200)
        .slice(0, 8)
      : [];
    if (reply) return { reply, remember };
  } catch (_) {
    // Fall through to salvage.
  }
  // Truncated or malformed: if it's our {"reply":"…"} wrapper, lift the reply
  // string out and best-effort unescape it.
  const m = content.match(/"reply"\s*:\s*"/);
  if (m && m.index !== undefined) {
    let rest = content.slice(m.index + m[0].length);
    const cut = rest.lastIndexOf('","remember"');
    if (cut >= 0) rest = rest.slice(0, cut);
    const unescaped = rest
      .replace(/\\n/g, "\n")
      .replace(/\\t/g, "\t")
      .replace(/\\r/g, "\r")
      .replace(/\\"/g, '"')
      .replace(/\\\\/g, "\\")
      .replace(/"\s*}?\s*$/, "")
      .trim();
    if (unescaped) return { reply: unescaped, remember: [] };
  }
  return { reply: content, remember: [] };
}

// A sane ceiling so one runaway conversation can't send a novel to the model.
const MAX_MESSAGES = 24;
const MAX_CHARS_PER_MESSAGE = 4000;
// A folded-in text file may be longer than a chat line, so its text part gets
// a roomier cap. Images are bounded by count and by data-URL size instead.
const MAX_TEXT_PART_CHARS = 16000;
const MAX_IMAGES = 6;
const MAX_IMAGE_URL_CHARS = 2_200_000; // ~1.6 MB of base64

type Part =
  | { type: "text"; text: string }
  | { type: "image_url"; image_url: { url: string } };

// Coerces one message's content into what the model accepts, dropping anything
// unrecognised: a trimmed/capped string, or a sanitized parts array with only
// text and inline `data:image/…` URLs (bounded in count and size). Returns null
// when nothing usable is left, so the message is skipped.
function normalizeContent(raw: unknown): string | Part[] | null {
  if (typeof raw === "string") {
    const s = raw.trim();
    return s.length ? s.slice(0, MAX_CHARS_PER_MESSAGE) : null;
  }
  if (!Array.isArray(raw)) return null;
  const parts: Part[] = [];
  let images = 0;
  let hasText = false;
  for (const p of raw) {
    if (typeof p !== "object" || p === null) continue;
    const type = String((p as Record<string, unknown>).type ?? "");
    if (type === "text") {
      let t = String((p as Record<string, unknown>).text ?? "").trim();
      if (!t) continue;
      if (t.length > MAX_TEXT_PART_CHARS) t = t.slice(0, MAX_TEXT_PART_CHARS);
      parts.push({ type: "text", text: t });
      hasText = true;
    } else if (type === "image_url" && images < MAX_IMAGES) {
      const iu = (p as Record<string, unknown>).image_url;
      const url = iu && typeof iu === "object"
        ? String((iu as Record<string, unknown>).url ?? "")
        : "";
      if (!url.startsWith("data:image/")) continue;
      if (url.length > MAX_IMAGE_URL_CHARS) continue;
      parts.push({ type: "image_url", image_url: { url } });
      images++;
    }
  }
  if (parts.length === 0) return null;
  // Some providers want a text part alongside images; supply a neutral one.
  if (!hasText) {
    parts.unshift({ type: "text", text: "Please look at the attached image." });
  }
  return parts;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  let body: Record<string, unknown> = {};
  try {
    body = await req.json();
  } catch {
    return json({ error: "bad_json" }, 400);
  }

  const raw = Array.isArray(body.messages) ? body.messages : [];
  const history: { role: string; content: string | Part[] }[] = [];
  for (const m of raw) {
    if (typeof m !== "object" || m === null) continue;
    const role = String((m as Record<string, unknown>).role ?? "");
    if (role !== "user" && role !== "assistant") continue;
    const content = normalizeContent((m as Record<string, unknown>).content);
    if (content === null) continue;
    // Only user turns carry images; an assistant turn is always plain text.
    if (role === "assistant" && typeof content !== "string") continue;
    history.push({ role, content });
  }
  const trimmed = history.slice(-MAX_MESSAGES);
  if (trimmed.length === 0 || trimmed[trimmed.length - 1].role !== "user") {
    return json({ error: "no user message" }, 400);
  }

  // The user's on-device memory, sent as context so the assistant "knows"
  // them. Learning is opt-out per request: draft() sends none.
  const memories: string[] = [];
  const rawMem = Array.isArray(body.memories) ? body.memories : [];
  for (const m of rawMem) {
    const s = String(m ?? "").trim();
    if (s.length > 0 && s.length <= 200) memories.push(s);
  }
  // The one-shot draft path asks for a plain reply and no learning.
  const learn = body.learn !== false;

  // STREAMING (2026-08-19). The single biggest thing that made the assistant
  // feel slow was not how fast it generated but that NOTHING appeared until
  // the whole answer had: one blocking fetch here, one blocking invoke on the
  // client. With a system prompt that says "write the whole app" and a 4000
  // token ceiling, that is half a minute of blank screen for a long answer.
  // Streaming does not make the model faster; it makes the first words arrive
  // in about a second, which is the thing being asked for.
  const wantsStream = body.stream === true;

  // Memory extraction moved OUT of the answer (see FORMAT below). A streaming
  // reply cannot also be a JSON object, so the client asks for memories in a
  // second, cheap call AFTER the reply is already on screen — the user never
  // waits for it.
  const remembering = body.what === "remember";

  // The user-chosen personality/style, if any: a short instruction the client
  // sends to shape the assistant's tone (a preset or their own words). Capped
  // and folded into the system prompt as a preference — never a way to unset
  // the assistant's real limits, which the system prompt states after it.
  const style = (typeof body.style === "string" ? body.style : "")
    .trim()
    .slice(0, 300);
  const styleLine = style
    ? `\n\nThe user has chosen this tone/personality for you — follow it in ` +
      `style, without dropping any of the rules above: ${style}`
    : "";

  const key = Deno.env.get("OPENROUTER_API_KEY") ?? "";
  if (!key) return json({ reply: "", configured: false });

  // Server-side rate limit — the real cost control, since the client's free
  // tier can be bypassed by a modified app. Counted per caller (their phone
  // when signed in, else the request IP) and checked BEFORE the model call, so
  // an over-cap request spends no tokens. Fails OPEN if the tally table isn't
  // set up, so a missing migration never breaks the assistant.
  const me = (await callerPhone(req)) ?? "";
  // The app OWNER is never capped: their phone digits go in AI_OWNER_PHONES
  // (comma-separated). This is the server half of the owner exemption — the
  // client waives its own free-tier gate for the owner too.
  const owners = (Deno.env.get("AI_OWNER_PHONES") ?? "")
    .split(",")
    .map((s) => s.replace(/\D/g, ""))
    .filter((s) => s.length > 0);
  const isOwner = me.length > 0 && owners.includes(me.replace(/\D/g, ""));

  const cap = parseInt(Deno.env.get("AI_DAILY_CAP") ?? "40", 10);
  if (cap > 0 && !isOwner) {
    const ip = (req.headers.get("x-forwarded-for") ?? "")
      .split(",")[0].trim();
    const usageKey = me || ip || "anon";
    try {
      const { data, error } = await admin.rpc("ai_note_usage", {
        k: usageKey,
      });
      if (!error && typeof data === "number" && data > cap) {
        return json({ error: "rate_limited", configured: true }, 429);
      }
    } catch (_) {
      // Table/RPC not deployed — fail open, no ceiling until it exists.
    }
  }

  const preferredModel = Deno.env.get("OPENROUTER_AI_MODEL") ||
    Deno.env.get("OPENROUTER_MODEL") || DEFAULT_MODEL;

  // ---- Memory pass ---------------------------------------------------------
  // Everything the learning turn used to do inside the answer, done separately
  // and cheaply: a small model, a small ceiling, and nothing the user waits
  // for. Returns [] on any trouble — a memory that did not get extracted is
  // not worth an error in front of somebody.
  if (remembering) {
    try {
      const res = await fetch(
        "https://openrouter.ai/api/v1/chat/completions",
        {
          method: "POST",
          headers: {
            "content-type": "application/json",
            "authorization": `Bearer ${key}`,
          },
          body: JSON.stringify({
            model: "openai/gpt-4o-mini",
            temperature: 0,
            max_tokens: 300,
            response_format: { type: "json_object" },
            messages: [
              { role: "system", content: REMEMBER + memoryPreamble(memories) },
              ...trimmed,
            ],
          }),
        },
      );
      if (!res.ok) return json({ memories: [], configured: true });
      const data = await res.json();
      const raw = String(data.choices?.[0]?.message?.content ?? "");
      const { remember } = unwrapReply(raw);
      return json({ memories: remember, configured: true });
    } catch (e) {
      console.error("ai-chat: remember failed", String(e));
      return json({ memories: [], configured: true });
    }
  }

  // ---- Streaming answer ----------------------------------------------------
  // Our OWN minimal SSE rather than OpenRouter's passed through: the client
  // should not have to know a provider's wire shape, and framing it here
  // leaves room for a terminal error, which a bare text stream has nowhere to
  // put. Two events only — `{"t": "<delta>"}` and `{"e": "<message>"}`.
  if (wantsStream) {
    const system = SYSTEM + styleLine + memoryPreamble(memories);
    const maxTokens = parseInt(Deno.env.get("AI_MAX_TOKENS") ?? "4000", 10);
    // The SAME fallback ladder the blocking path has, and leaving it out was a
    // real bug: the preferred model can be refused for reasons that have
    // nothing to do with streaming — OpenRouter pre-authorises max_tokens
    // against the account balance and answers 402 when the credit will not
    // cover it, which happens on the expensive model long before the cheap
    // one. Without this, streaming dead-ended while the blocking path quietly
    // carried on, and the difference looked like a streaming fault.
    const streamModels = [...new Set([preferredModel, "openai/gpt-4o-mini"])];
    let upstream: Response | null = null;
    let lastStatus = 0;
    let lastDetail = "";
    try {
      for (const model of streamModels) {
        const res = await fetch(
          "https://openrouter.ai/api/v1/chat/completions",
          {
        method: "POST",
        headers: {
          "content-type": "application/json",
          "authorization": `Bearer ${key}`,
        },
        body: JSON.stringify({
          model,
          temperature: 0.4,
          max_tokens: maxTokens,
          stream: true,
          // Deliberately NO JSON-object response format here: a streamed
          // answer is plain text, and asking for a structured one is exactly
          // what the memory pass above exists to replace. (Named in prose
          // rather than by its identifier — a test scans this block for that
          // token, and it must not find one in a comment saying there is
          // none.)
          messages: [{ role: "system", content: system }, ...trimmed],
        }),
          },
        );
        if (res.ok && res.body) {
          upstream = res;
          break;
        }
        lastStatus = res.status;
        lastDetail = await res.text().catch(() => "");
        console.error("ai-chat: stream", model, res.status,
          lastDetail.slice(0, 300));
      }
    } catch (e) {
      console.error("ai-chat: stream connect", String(e));
      return json(
        { reply: "", configured: true, degraded: true, why: "connect" },
      );
    }
    if (upstream === null) {
      const detail = lastDetail;
      // The STATUS, so a degraded stream can be diagnosed without reading a
      // log that lags. A number cannot leak the key — which lives in a
      // header here, not in the URL the way the sports proxy's does, so the
      // upstream's own short message is safe to pass on too.
      return json({
        reply: "",
        configured: true,
        degraded: true,
        why: `upstream ${lastStatus}`,
        detail: detail.slice(0, 200),
      });
    }

    const encoder = new TextEncoder();
    const decoder = new TextDecoder();
    const body$ = upstream.body!;
    const out = new ReadableStream({
      async start(controller) {
        const send = (o: unknown) =>
          controller.enqueue(encoder.encode(`data: ${JSON.stringify(o)}\n\n`));
        const reader = body$.getReader();
        // OpenRouter frames SSE, and a chunk can split a frame anywhere —
        // including mid-JSON — so lines are only parsed once a blank line has
        // actually arrived.
        let buf = "";
        try {
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            buf += decoder.decode(value, { stream: true });
            const parts = buf.split("\n");
            buf = parts.pop() ?? "";
            for (const line of parts) {
              const t = line.trim();
              if (!t.startsWith("data:")) continue;
              const payload = t.slice(5).trim();
              if (payload === "[DONE]") continue;
              try {
                const j = JSON.parse(payload);
                const delta = j.choices?.[0]?.delta?.content;
                if (typeof delta === "string" && delta.length > 0) {
                  send({ t: delta });
                }
              } catch (_) {
                // A frame we cannot read is one token's worth of text, not a
                // reason to end the answer.
              }
            }
          }
        } catch (e) {
          console.error("ai-chat: stream read", String(e));
          send({ e: "the answer was cut off" });
        } finally {
          controller.enqueue(encoder.encode("data: [DONE]\n\n"));
          controller.close();
          try {
            reader.releaseLock();
          } catch (_) { /* already released */ }
        }
      },
    });
    return new Response(out, {
      headers: {
        ...corsHeaders,
        "content-type": "text/event-stream; charset=utf-8",
        "cache-control": "no-cache",
        // Proxies that buffer would undo the whole point of this.
        "x-accel-buffering": "no",
      },
    });
  }

  try {
    const system = learn
      ? SYSTEM + styleLine + memoryPreamble(memories) + "\n\n" + FORMAT
      : SYSTEM + styleLine + memoryPreamble(memories);
    // 4000 is a large answer (hundreds of lines) and stays under every common
    // model's output cap, so it never 400s the way 8000 can on a 4096-cap
    // model. Raise it with AI_MAX_TOKENS if your model allows more.
    const maxTokens = parseInt(Deno.env.get("AI_MAX_TOKENS") ?? "4000", 10);

    // Try the preferred model first, then fall back — so if the strong default
    // (or a set OPENROUTER_AI_MODEL) isn't available on this account, the
    // assistant STILL answers on a model that is, instead of dead-ending. The
    // fallback (gpt-4o-mini) is broadly available and vision-capable, so
    // attachments keep working on it too. Duplicates are dropped.
    const preferred = Deno.env.get("OPENROUTER_AI_MODEL") ||
      Deno.env.get("OPENROUTER_MODEL") || DEFAULT_MODEL;
    const models = [...new Set([preferred, "openai/gpt-4o-mini"])];

    let content = "";
    for (const model of models) {
      const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
          "content-type": "application/json",
          "authorization": `Bearer ${key}`,
        },
        body: JSON.stringify({
          model,
          // Lower temperature than a chatbot's: fact-checking and code want
          // accuracy over flourish. A large max_tokens lets it return a WHOLE
          // file or app in one go rather than being cut off.
          temperature: 0.4,
          max_tokens: maxTokens,
          ...(learn ? { response_format: { type: "json_object" } } : {}),
          messages: [
            { role: "system", content: system },
            ...trimmed,
          ],
        }),
      });
      if (!res.ok) {
        const detail = await res.text().catch(() => "");
        console.error("ai-chat: openrouter", model, res.status,
          detail.slice(0, 300));
        continue; // try the next model
      }
      const data = await res.json();
      content = String(data.choices?.[0]?.message?.content ?? "").trim();
      if (content) break;
    }
    if (!content) {
      return json({ reply: "", configured: true, degraded: true });
    }
    if (!learn) return json({ reply: content, configured: true });

    // Learning turn: the content is a JSON object with reply + remember.
    const { reply, remember } = unwrapReply(content);
    if (!reply) return json({ reply: "", configured: true, degraded: true });
    return json({ reply, memories: remember, configured: true });
  } catch (e) {
    console.error("ai-chat: failed", String(e));
    return json({ reply: "", configured: true, degraded: true });
  }
});
