// PASTE-READY, self-contained version of ai-feedback for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: ai-feedback
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/ai-feedback/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

// Collects a rated Okay AI exchange as training data — the corpus a future
// fine-tune of "your own AI" is built from.
//
// POST { prompt, reply, rating } -> { ok }
//
// CONSENT IS THE CLIENT'S GATE. The app sends here ONLY when the user has
// opted in to "Help improve Okay AI" (AiConsent). By definition this is an
// assistant conversation — what the user typed to Okay AI and what it replied
// — never a human-to-human chat (those are end-to-end encrypted and never
// reach a server that can read them). The rating is the curation signal: a
// later fine-tune trains on the thumbs-up examples, filtered, so the model
// learns from good exchanges, not nonsense.
//
// Written ONLY here (service role) into ai_training_samples, which has no
// client grants. A coarse, salted submitter hash lets an abuser be rate-limited
// and a user's own samples be removed on request, without storing the phone.
//
// INERT WITHOUT THE TABLE. If ai_training.sql hasn't been run the insert fails
// and this returns { ok: false } — feedback is best-effort and never blocks.


const MAX_LEN = 8000;

async function submitterHash(phone: string): Promise<string> {
  if (!phone) return "";
  const salt = Deno.env.get("AI_FEEDBACK_SALT") ?? "okayai";
  const data = new TextEncoder().encode(`${salt}:${phone}`);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")
    .slice(0, 32);
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  let body: Record<string, unknown> = {};
  try {
    body = await req.json();
  } catch {
    return json({ error: "bad_json" }, 400);
  }

  const prompt = String(body.prompt ?? "").trim().slice(0, MAX_LEN);
  const reply = String(body.reply ?? "").trim().slice(0, MAX_LEN);
  const rating = Number(body.rating ?? 0);
  if (!prompt || !reply || (rating !== 1 && rating !== -1)) {
    return json({ error: "invalid feedback" }, 400);
  }

  const me = (await callerPhone(req)) ?? "";
  const submitter = await submitterHash(me);

  try {
    await admin.from("ai_training_samples").insert({
      prompt,
      reply,
      rating,
      submitter,
    });
    return json({ ok: true });
  } catch (e) {
    console.error("ai-feedback: insert failed", String(e));
    return json({ ok: false });
  }
});
