// PASTE-READY, self-contained version of delete-account for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: delete-account
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/delete-account/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.



// Deletes the CALLER's account: every server-side row their phone owns, the
// objects in their private storage folders, and finally the auth user itself.
// JWT-gated — only a signed-in phone can ask, and it can only ever delete
// itself. Numberless accounts have no session and so cannot reach this;
// their server footprint (a directory row and a first-write recovery blob)
// is documented in the app as staying behind.
//
// What is deliberately KEPT: payment_transactions and payout_status. Those
// are financial records of money that really moved between two people;
// deleting one side's copy of a transfer is not privacy, it is losing the
// receipt. Stripe holds the authoritative ledger either way.
//
// POST {} -> { deleted: true }
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, content-type, apikey",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });

  const auth = req.headers.get("Authorization")?.replace("Bearer ", "") ?? "";
  const { data: caller } = await admin.auth.getUser(auth);
  if (!caller?.user) {
    return Response.json({ error: "unauthorized" }, { status: 401, headers: cors });
  }
  const digits = (caller.user.phone ?? "").replace(/\D/g, "");
  if (!digits) {
    return Response.json({ error: "no phone" }, { status: 400, headers: cors });
  }

  // Rows keyed by the phone. Each delete is its own statement so one table
  // that predates this function (42P01) does not strand the rest.
  const drop = async (table: string, column: string, value: string) => {
    try {
      await admin.from(table).delete().eq(column, value);
    } catch (_) { /* table missing on this project — nothing to delete */ }
  };
  await drop("usernames", "phone", digits);
  await drop("push_tokens", "phone", digits);
  await drop("identity_backups", "inbox", digits);
  await drop("mailbox", "inbox", `inbox_${digits}`);
  await drop("payment_settings", "phone", digits);
  await drop("payment_blocks", "phone", digits);
  await drop("identity_verifications", "phone", digits);
  await drop("subscriptions", "phone", digits);
  // user_storage_usage is keyed by an HMAC `account` tag, not a phone — the
  // server cannot find it from here, and it holds only byte counts.
  // Their public posts, and the interaction rows that name them. The posts'
  // replies and reposts cascade with the posts themselves.
  await drop("public_posts", "author_phone", digits);
  await drop("public_post_likes", "liker_phone", digits);
  await drop("public_post_votes", "voter_phone", digits);
  await drop("public_post_sparks", "sparker_phone", digits);

  // Private storage folders are keyed by the phone digits. List-and-remove,
  // because Storage has no recursive delete.
  for (const bucket of ["chat-backups", "voice-notes", "market-media"]) {
    try {
      const { data: files } = await admin.storage.from(bucket)
        .list(digits, { limit: 1000 });
      const names = (files ?? []).map((f) => `${digits}/${f.name}`);
      if (names.length > 0) await admin.storage.from(bucket).remove(names);
    } catch (_) { /* bucket missing — nothing to remove */ }
  }

  // Last, so a failure above still leaves a session able to retry.
  const { error } = await admin.auth.admin.deleteUser(caller.user.id);
  if (error) {
    return Response.json({ error: error.message }, { status: 500, headers: cors });
  }
  return Response.json({ deleted: true }, { headers: cors });
});
