// PASTE-READY, self-contained version of iap-status for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: iap-status
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/iap-status/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

// Entitlement bookkeeping shared by the in-app-purchase functions.
//
// One row per Apple subscription, keyed by originalTransactionId (stable for
// the life of a subscription, and the only identifier Apple's renewal
// notifications carry). The phone on the row is what links it back to an
// account, recorded when the app validates the first purchase — Apple's
// notifications never mention it.

// deno-lint-ignore no-explicit-any
type Db = any;

interface SubscriptionRow {
  originalTransactionId: string;
  phone: string;
  productId: string;
  gb: number;
  expiresAt: string | null;
  status: string;
  environment: string;
}

/// Whether sandbox purchases count towards entitlement.
///
/// They must NOT in production: a sandbox purchase costs nothing and Apple
/// signs it with the same certificate chain as a real one, so without this
/// anyone able to run the app against a Sandbox Apple ID would get paid
/// storage for free. Set IAP_ALLOW_SANDBOX=true only while testing, and take
/// it off before release.
function sandboxAllowed(): boolean {
  return Deno.env.get("IAP_ALLOW_SANDBOX") === "true";
}

/// The storage size a product grants, or 0 when it isn't a storage product
/// (the tip consumables land here).
function gbForProduct(productId: string): number {
  const m = /\.storage\.gb(\d+)\.monthly$/.exec(productId);
  return m ? parseInt(m[1], 10) : 0;
}

async function upsertSubscription(db: Db, row: SubscriptionRow) {
  await db.from("subscriptions").upsert({
    original_transaction_id: row.originalTransactionId,
    phone: row.phone,
    product_id: row.productId,
    gb: row.gb,
    expires_at: row.expiresAt,
    status: row.status,
    environment: row.environment,
    updated_at: new Date().toISOString(),
  });
}

interface Entitlement {
  active: boolean;
  gb: number;
  expiresAt: string | null;
  productId: string | null;
}

/// What [phone] is entitled to right now: the largest size among their
/// unexpired, unrevoked subscriptions. Taking the largest (rather than the
/// newest) means a mid-cycle downgrade never strands data the user is still
/// paying to keep until the bigger plan actually lapses.
async function entitlementFor(db: Db, phone: string): Promise<Entitlement> {
  const { data } = await db
    .from("subscriptions")
    .select("product_id, gb, expires_at, status, environment")
    .eq("phone", phone);

  const now = Date.now();
  let best: Entitlement = { active: false, gb: 0, expiresAt: null, productId: null };
  for (const row of data ?? []) {
    if (row.status === "refunded" || row.status === "expired") continue;
    if (row.environment === "Sandbox" && !sandboxAllowed()) continue;
    const expires = row.expires_at ? Date.parse(row.expires_at) : 0;
    if (!expires || expires <= now) continue;
    if (row.gb > best.gb) {
      best = {
        active: true,
        gb: row.gb,
        expiresAt: row.expires_at,
        productId: row.product_id,
      };
    }
  }
  return best;
}

/// Maps an App Store Server Notification type onto the row status we keep.
/// Anything unrecognised leaves the row alone — Apple adds notification types
/// over time and an unknown one must never silently revoke someone's storage.
function statusForNotification(
  notificationType: string,
  subtype: string,
): string | null {
  switch (notificationType) {
    case "SUBSCRIBED":
    case "DID_RENEW":
    case "OFFER_REDEEMED":
      return "active";
    case "DID_CHANGE_RENEWAL_STATUS":
      // AUTO_RENEW_DISABLED means "won't renew", NOT "access ends now" — the
      // paid-for period still has to run out. Keep it active; EXPIRED will
      // arrive when it actually lapses.
      return subtype === "AUTO_RENEW_DISABLED" ? "canceled" : "active";
    case "DID_FAIL_TO_RENEW":
      // In the billing-retry grace period the subscription is still usable.
      return subtype === "GRACE_PERIOD" ? "grace" : "expired";
    case "EXPIRED":
      return "expired";
    case "REFUND":
    case "REVOKE":
      return "refunded";
    default:
      return null;
  }
}

// The caller's current storage entitlement, straight from what Apple's
// notifications have told us. The app calls this on launch and when the
// storage screen opens, so a renewal (or a cancellation, or a refund) shows
// up without the user having to buy anything again.
//
// POST {} -> { active, gb, expiresAt, productId }


Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const phone = await callerPhone(req);
  if (!phone) return json({ error: "unauthorized" }, 401);

  return json(await entitlementFor(admin, phone));
});
