// PASTE-READY, self-contained version of identity-start for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: identity-start
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/identity-start/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

import Stripe from "https://esm.sh/stripe@16.12.0?target=deno";

// The generic request plumbing lives in http.ts; re-exported so existing
// imports from this file keep working unchanged.

const stripe = new Stripe(Deno.env.get("STRIPE_SECRET_KEY") ?? "", {
  apiVersion: "2024-06-20",
  httpClient: Stripe.createFetchHttpClient(),
});

/// The platform's application fee for an [amountCents] charge, in cents.
///
/// Transfers are DIRECT charges — the PaymentIntent is created on the
/// recipient's connected account — so the platform is never in the flow of
/// funds and never pays Stripe's processing fee. That makes this fee pure
/// revenue, and means no floor is needed: unlike a destination charge, there
/// is no platform-side cost for it to fail to clear.
///
/// Stripe's cut (2.9% + 30c domestic, more on a foreign card) comes out of the
/// recipient's account instead, which is why the send sheet quotes an
/// approximate landing amount rather than the amount typed.
function applicationFee(amountCents: number): number {
  const pct = parseFloat(Deno.env.get("PLATFORM_FEE_PERCENT") ?? "3.4");
  const fixed = parseInt(Deno.env.get("PLATFORM_FEE_FIXED_CENTS") ?? "10", 10);
  return Math.max(0, Math.round((amountCents * pct) / 100) + fixed);
}

// Starts a government-ID check for the blue check.
//
// The badge used to be a free toggle: tap "Verify me" and you were verified,
// which made it a decoration rather than a claim about who someone is. It now
// requires Stripe Identity — a real document check with a selfie match.
//
// POST {} -> { url, sessionId }  (open `url`, Stripe hosts the flow)
//
// Nothing about the document reaches this app. Stripe holds the images and
// the extracted fields; all we ever store is that a session for this phone
// reached "verified".


Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const phone = await callerPhone(req);
  if (!phone) return json({ error: "unauthorized" }, 401);

  // Already verified? Don't start (or charge for) a second check.
  const { data: existing } = await admin
    .from("identity_verifications")
    .select("status")
    .eq("phone", phone)
    .maybeSingle();
  if (existing?.status === "verified") {
    return json({ alreadyVerified: true });
  }

  // Same rule as onboarding: Stripe's hosted flow needs an http(s) URL, and
  // a custom scheme is rejected as "Not a valid URL".
  const returnUrl = Deno.env.get("APP_RETURN_URL") ??
    "https://kingimann.github.io/OkayMessaging/";

  try {
    const session = await stripe.identity.verificationSessions.create({
      type: "document",
      options: {
        document: {
          // A selfie match is the difference between "this is a real ID" and
          // "this is the ID of the person holding the phone".
          require_matching_selfie: true,
          require_live_capture: true,
        },
      },
      return_url: returnUrl,
      metadata: { phone },
    });

    await admin.from("identity_verifications").upsert({
      phone,
      session_id: session.id,
      status: session.status,
      updated_at: new Date().toISOString(),
    });

    return json({
      // client_secret drives the in-app flow (Stripe.js verifyIdentity);
      // url is the hosted fallback for anywhere a WebView can't run.
      clientSecret: session.client_secret,
      url: session.url,
      sessionId: session.id,
      publishableKey: Deno.env.get("STRIPE_PUBLISHABLE_KEY") ?? "",
    });
  } catch (e) {
    return json({ error: String((e as Error).message ?? e) }, 400);
  }
});
