// PASTE-READY, self-contained version of moderation-screen for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: moderation-screen
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/moderation-screen/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

// Turning a classifier's category scores into a verdict.
//
// Pure and separate from the Edge Function so it can be executed by a test
// rather than read: this is the code that decides whether somebody gets to
// post, and "reads correct" is not the same as "is correct". See
// _shared/moderation_test.mjs.

/// Scores at or above this are treated as confident enough to stop a post.
/// Anything the classifier raises below it becomes a flag instead.
const BLOCK_AT = 0.7;

/// The categories a post can be stopped outright for, and what the person who
/// wrote it is told.
///
/// DETERMINISTIC WORDING, on purpose. The classifier returns categories and
/// scores, not prose, so these are written once here rather than generated per
/// post. Somebody stopped twice for the same thing reads the same sentence
/// both times, it can be translated, and no model can invent a rule that does
/// not exist.
const BLOCK_REASONS: Record<string, string> = {
  "sexual/minors": "That appears to involve a minor. It cannot be posted.",
  "harassment/threatening":
    "That reads as a threat aimed at someone. Take out the threat and it can go up.",
  "hate/threatening":
    "That reads as a threat against a group of people. It cannot be posted as written.",
  "illicit/violent":
    "That describes carrying out serious harm. It cannot be posted.",
  "violence":
    "That reads as a threat of violence. It cannot be posted as written.",
};

/// Everything else the classifier can raise. These never stop a post; they put
/// it in front of a moderator.
const FLAG_CATEGORIES = [
  "harassment",
  "hate",
  "illicit",
  "self-harm",
  "self-harm/intent",
  "self-harm/instructions",
  "sexual",
  "violence/graphic",
];

/// Every category name the classifier is asked about — generated from the
/// two lists above rather than typed again, so the prompt and the verdict
/// logic can never disagree about what a category is called.
const classifierCategories: string[] = [
  ...Object.keys(BLOCK_REASONS),
  ...FLAG_CATEGORIES,
];

interface Verdict {
  verdict: "ok" | "flag" | "block";
  category: string;
  reason: string;
}

/// The verdict for one classifier result.
///
/// A block needs BOTH the raised category and a confident score, because a
/// block on a machine's say-so is the decision worth being careful about.
/// Everything raised without that confidence becomes a flag — a wrong block
/// silences somebody, a wrong flag costs a moderator a glance.
function verdictFor(
  categories: Record<string, boolean>,
  scores: Record<string, number>,
): Verdict {
  for (const [category, reason] of Object.entries(BLOCK_REASONS)) {
    if (categories[category] !== true) continue;
    // Content involving minors is the one case where the threshold is the
    // classifier's own judgement; there is no version of this worth a second
    // opinion first.
    const confident = category === "sexual/minors" ||
      (scores[category] ?? 0) >= BLOCK_AT;
    if (confident) return { verdict: "block", category, reason };
  }

  // A severe category raised but not confidently is still worth a look — it
  // falls through to here rather than being forgotten.
  const flagged = FLAG_CATEGORIES.find((c) => categories[c] === true) ??
    Object.keys(BLOCK_REASONS).find((c) => categories[c] === true);
  if (flagged) return { verdict: "flag", category: flagged, reason: "" };

  return { verdict: "ok", category: "none", reason: "" };
}

/// A generative model's JSON answer, coerced to the shapes [verdictFor]
/// expects — or null when it can't be. The screen moved from OpenAI's
/// purpose-built moderation endpoint to OpenRouter chat completions, which
/// means the classifier is now a model ASKED to answer in this shape rather
/// than an API that guarantees it; this is the seam where a creative reply
/// degrades to "screened nothing" instead of a crash. Tolerates code
/// fences, drops non-boolean categories and non-finite scores.
function parseClassifier(
  raw: string,
):
  | { categories: Record<string, boolean>; scores: Record<string, number> }
  | null {
  const stripped = raw.trim()
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/, "");
  let data: unknown;
  try {
    data = JSON.parse(stripped);
  } catch {
    return null;
  }
  if (typeof data !== "object" || data === null) return null;
  const obj = data as Record<string, unknown>;
  const categories: Record<string, boolean> = {};
  const scores: Record<string, number> = {};
  const rawCats = obj.categories;
  if (typeof rawCats === "object" && rawCats !== null) {
    for (const [k, v] of Object.entries(rawCats)) {
      if (typeof v === "boolean") categories[k] = v;
    }
  }
  const rawScores = obj.scores;
  if (typeof rawScores === "object" && rawScores !== null) {
    for (const [k, v] of Object.entries(rawScores)) {
      if (typeof v === "number" && isFinite(v)) scores[k] = v;
    }
  }
  return { categories, scores };
}

// Screens a public newsfeed post before it goes up.
//
// POST { text, handle?, phone?, hasImage? }
//   -> { verdict: 'ok' | 'flag' | 'block', reason?, category?, configured }
//
// ENGINE: OpenRouter (chat completions), replacing the earlier OpenAI
// moderation endpoint at the owner's request. The model is asked to act as a
// strict classifier and answer with the SAME category/score shape the OpenAI
// moderation API used, so the shared verdict logic (_shared/moderation.ts,
// with its own executable test) is unchanged — the thresholds, the block
// wording, and the flag queue all work exactly as before. Unlike the
// moderation endpoint this is billed per token; MODEL is a cheap one on
// purpose, overridable with the OPENROUTER_MODEL secret.
//
// WHY THIS ONE IS ALLOWED TO LEAVE THE DEVICE AT ALL. Everything else people
// write in this app is end-to-end encrypted and must never reach a server that
// can read it. The public feed is the exception: those posts are
// world-readable by design — that is the entire point of the feed — so
// screening one discloses nothing that publishing it a second later will not.
// Do not copy this pattern to chats or server feeds.
//
// WHAT IT IS AND IS NOT. A speed bump and a queue-filler, not a security
// boundary: the client makes the call, so a modified client skips it entirely.
// Real enforcement stays where it was — people report, moderators sanction. A
// 'flag' verdict writes into the moderation_reports table the console already
// reads, so flagged posts land in the queue moderators already work, with no
// new table and no new screen.
//
// INERT WITHOUT A KEY. With no OPENROUTER_API_KEY set this returns
// { verdict: 'ok', configured: false } and posting works exactly as before. A
// missing key, a rate limit, or a bad gateway must never be the reason
// somebody cannot post.


const DEFAULT_MODEL = "openai/gpt-4o-mini";

/// The classifier instruction. The category names come from the shared
/// module rather than being typed again, so the verdict logic and the
/// prompt can never disagree about what a category is called.
const INSTRUCTIONS = `You are a strict content-safety classifier for a ` +
  `public social feed. Classify the user's post against exactly these ` +
  `categories: ${classifierCategories.join(", ")}.\n` +
  `Answer ONLY with a JSON object of this shape and nothing else:\n` +
  `{"categories": {"<name>": true|false, ...}, ` +
  `"scores": {"<name>": 0.0-1.0, ...}}\n` +
  `Set a category true only when the post genuinely exhibits it; scores ` +
  `are your confidence. Ordinary rudeness, profanity, and strong opinions ` +
  `are all false across the board.`;

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  let body: Record<string, unknown> = {};
  try {
    body = await req.json();
  } catch {
    return json({ error: "bad_json" }, 400);
  }

  const text = String(body.text ?? "").trim();
  const handle = String(body.handle ?? "");
  // Self-asserted when there is no session, which is the norm here — this app
  // runs with server-side OTP off. It is only used to attribute a flag, and a
  // flag is a request for a human to look, not a punishment.
  const phone = (await callerPhone(req)) ?? String(body.phone ?? "");

  const key = Deno.env.get("OPENROUTER_API_KEY") ?? "";
  if (!key) return json({ verdict: "ok", configured: false });

  // A post with no words is nothing to screen. An image-only post goes
  // through: this call reads text, and claiming to have checked a picture
  // would be a lie told to a moderator.
  if (!text) return json({ verdict: "ok", configured: true, skipped: true });

  let categories: Record<string, boolean> = {};
  let scores: Record<string, number> = {};
  try {
    const model = Deno.env.get("OPENROUTER_MODEL") || DEFAULT_MODEL;
    const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "authorization": `Bearer ${key}`,
      },
      body: JSON.stringify({
        model,
        temperature: 0,
        response_format: { type: "json_object" },
        messages: [
          { role: "system", content: INSTRUCTIONS },
          { role: "user", content: text },
        ],
      }),
    });
    if (!res.ok) {
      // Rate limited, a bad key, a bad day. Fail open — loudly in the logs and
      // silently to the person posting.
      console.error("moderation-screen: openrouter", res.status);
      return json({ verdict: "ok", configured: true, degraded: true });
    }
    const data = await res.json();
    const content = data.choices?.[0]?.message?.content ?? "";
    const parsed = parseClassifier(String(content));
    if (!parsed) {
      // A model that answered prose instead of JSON classified nothing.
      console.error("moderation-screen: unparseable classifier reply");
      return json({ verdict: "ok", configured: true, degraded: true });
    }
    categories = parsed.categories;
    scores = parsed.scores;
  } catch (e) {
    console.error("moderation-screen: failed", String(e));
    return json({ verdict: "ok", configured: true, degraded: true });
  }

  const { verdict, category, reason } = verdictFor(categories, scores);
  // Both a block and a flag go to a human. A block stopped somebody posting on
  // a machine's say-so, which is exactly the decision that deserves review.
  // The poster is told nothing about a flag — their post went up, and telling
  // somebody they are being watched is both unkind and a hint about how to
  // word it next time.
  if (verdict !== "ok") await record(phone, handle, text, verdict, category);
  return json({ verdict, category, reason, configured: true });
});

/// Puts a raised post in the queue moderators already work.
async function record(
  phone: string,
  handle: string,
  text: string,
  verdict: string,
  category: string,
): Promise<void> {
  await admin.from("moderation_reports").insert({
    target_phone: phone,
    target_handle: handle,
    reporter_phone: "", // nobody reported this; the screen raised it
    reason: `auto:${verdict}:${category}`,
    detail: text.slice(0, 1000),
    context: "post",
  });
}
