// PASTE-READY, self-contained version of moderation-queue for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: moderation-queue
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/moderation-queue/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

// The moderator's working set: open reports, live sanctions, recent actions.
//
// POST { what?: 'reports' | 'sanctions' | 'log', limit? }
//   -> { reports: [...] } | { sanctions: [...] } | { log: [...] }
//
// Reports are not client-readable — one person's report is nobody else's
// business — so they come through here, gated on the caller's role. Sanctions
// are public (the directory rules already reveal who is hidden), but they are
// served here too so the console needs one call and one contract.
//
// POST { what: 'handle', id } marks a report dealt with.


const RANK: Record<string, number> = {
  owner: 3,
  admin: 2,
  moderator: 1,
  member: 0,
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  const phone = await callerPhone(req);
  if (!phone) return json({ error: "unauthorized" }, 401);

  const { data: roleRow } = await admin
    .from("platform_roles")
    .select("role")
    .eq("phone", phone)
    .maybeSingle();
  const role = (roleRow?.role as string) ?? "member";
  if (RANK[role] < RANK.moderator) return json({ error: "forbidden" }, 403);

  let body: Record<string, unknown> = {};
  try {
    body = await req.json();
  } catch {
    // An empty body is fine — it means "the default view".
  }
  const what = String(body.what ?? "reports");
  const limit = Math.min(Number(body.limit ?? 50) || 50, 200);

  if (what === "handle") {
    const id = Number(body.id ?? 0);
    if (!id) return json({ error: "no_id" }, 400);
    await admin
      .from("moderation_reports")
      .update({ handled: true })
      .eq("id", id);
    return json({ ok: true });
  }

  if (what === "sanctions") {
    const { data } = await admin
      .from("account_sanctions")
      .select("phone, kind, reason, until, actor_phone, created_at")
      .order("created_at", { ascending: false })
      .limit(limit);
    return json({
      sanctions: (data ?? []).map((r) => ({
        phone: r.phone,
        kind: r.kind,
        reason: r.reason ?? "",
        until: r.until,
        actorPhone: r.actor_phone ?? "",
        createdAt: r.created_at,
      })),
    });
  }

  if (what === "log") {
    const { data } = await admin
      .from("moderation_log")
      .select(
        "id, created_at, actor_phone, actor_role, target_phone, action, reason, until",
      )
      .order("created_at", { ascending: false })
      .limit(limit);
    return json({ log: data ?? [] });
  }

  const { data } = await admin
    .from("moderation_reports")
    .select(
      "id, created_at, target_phone, target_handle, reporter_phone, reason, detail, context, handled",
    )
    .eq("handled", false)
    .order("created_at", { ascending: false })
    .limit(limit);
  return json({
    reports: (data ?? []).map((r) => ({
      id: r.id,
      createdAt: r.created_at,
      targetPhone: r.target_phone ?? "",
      targetHandle: r.target_handle ?? "",
      reporterPhone: r.reporter_phone ?? "",
      reason: r.reason ?? "",
      detail: r.detail ?? "",
      context: r.context ?? "",
    })),
  });
});
