// PASTE-READY, self-contained version of moderation-status for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: moderation-status
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/moderation-status/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

// What the caller is allowed to do app-wide, and what has been done to them.
//
// POST {} -> { role, sanction: { kind, reason, until, actorPhone, createdAt } | null }
//
// The role comes from platform_roles, a table no client can read — so the only
// way to learn your own role is to ask here, with a JWT that proves the phone
// is yours. A build that lies to itself about being an admin gets nothing: the
// action function checks the same table again before doing anything.


Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  const phone = await callerPhone(req);
  if (!phone) return json({ error: "unauthorized" }, 401);

  const { data: roleRow } = await admin
    .from("platform_roles")
    .select("role")
    .eq("phone", phone)
    .maybeSingle();

  const { data: sanctionRow } = await admin
    .from("account_sanctions")
    .select("kind, reason, until, actor_phone, created_at")
    .eq("phone", phone)
    .maybeSingle();

  // An expired sanction is history. Report it as gone rather than making every
  // client re-derive that from a timestamp.
  const expired = sanctionRow?.until != null &&
    new Date(sanctionRow.until as string).getTime() <= Date.now();

  return json({
    role: roleRow?.role ?? "member",
    sanction: !sanctionRow || expired ? null : {
      kind: sanctionRow.kind,
      reason: sanctionRow.reason ?? "",
      until: sanctionRow.until,
      actorPhone: sanctionRow.actor_phone ?? "",
      createdAt: sanctionRow.created_at,
    },
  });
});
