// PASTE-READY, self-contained version of pages for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: pages
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/pages/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

// GENERATED — do not edit by hand.
// Source: lib/legal/legal_content.dart · regenerate: dart tool/build_legal_pages.dart
//
// The legal documents as standalone pages, served by the `pages` function so
// the App Store's required Privacy Policy URL points at the app's own host
// rather than at wherever the source happens to live.

const PRIVACY_HTML = `<!DOCTYPE html>
<!--
  GENERATED — do not edit by hand.
  Source: lib/legal/legal_content.dart · regenerate: dart tool/build_legal_pages.dart
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Privacy Policy · OkayMessenger</title>
<style>
  :root { color-scheme: light dark; --fg: #1a1c1e; --dim: #5f6368; --bg: #ffffff; --rule: #e3e5e8; }
  @media (prefers-color-scheme: dark) {
    :root { --fg: #e8eaed; --dim: #9aa0a6; --bg: #121417; --rule: #2a2d31; }
  }
  html, body { margin: 0; background: var(--bg); }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    color: var(--fg); padding: 28px 20px 64px; box-sizing: border-box;
    -webkit-text-size-adjust: 100%;
  }
  main { max-width: 640px; margin: 0 auto; }
  h1 { font-size: 24px; margin: 0 0 4px; font-weight: 700; letter-spacing: -0.2px; }
  .meta { font-size: 13px; color: var(--dim); margin: 0 0 28px; }
  h2 {
    font-size: 17px; font-weight: 600; margin: 32px 0 8px;
    padding-top: 20px; border-top: 1px solid var(--rule);
  }
  h2:first-of-type { border-top: 0; padding-top: 0; margin-top: 0; }
  p { font-size: 15px; line-height: 1.6; margin: 0 0 12px; }
  ul { margin: 0 0 12px; padding-left: 20px; }
  li { font-size: 15px; line-height: 1.6; margin-bottom: 6px; }
  footer { margin-top: 40px; font-size: 13px; color: var(--dim); }
  a { color: inherit; }
</style>
</head>
<body>
<main>
  <h1>Privacy Policy</h1>
  <p class="meta">OkayMessenger · Last updated: August 2026 · version 9</p>
    <h2>The short version</h2>
    <p>Your messages are stored on our servers so your conversations follow you to a new phone instead of disappearing with the old one. They are encrypted while travelling between devices and encrypted on our disks, but we hold those disk keys — which means we can read stored messages, and will where the law requires it or where somebody reports one. Your calls are different: audio and video go directly between devices and are never recorded.</p>
    <h2>What we do NOT store</h2>
    <ul>
      <li>Calls — audio and video go directly between devices (WebRTC) and are never recorded or routed through us.</li>
      <li>Anything sent over Okay Drop — those files cross Bluetooth or a direct Wi-Fi link between two phones in the same room and never touch a server at all.</li>
      <li>Card numbers — payments are handled by Stripe; we never see or store them.</li>
      <li>Your device passcode, app lock PIN, chat passwords or backup passphrase — none of these ever leaves your phone, and we cannot reset any of them for you.</li>
    </ul>
    <h2>What we DO store</h2>
    <ul>
      <li>A username directory: your verified phone number mapped to the username you choose, so usernames are unique and reachable.</li>
      <li>Payment metadata: for money you send/receive we keep the transaction id, amount, fee, and status (never card data) to show receipts and payout status. The money itself is held by Stripe, not us.</li>
      <li>Communal data: your servers, feed posts and follows sync for everyone in a server, encrypted as ciphertext we cannot read. This is shared infrastructure — it is not part of anyone’s personal storage and costs nothing.</li>
      <li>Your messages: text, and the photos, voice notes and other attachments that ride with them, kept so your history is there on any phone you sign in on. They sit on encrypted disks, but we hold those keys, so we can read them. Deleting a message for everyone marks it deleted; taking a message back within the undo window removes it outright.</li>
      <li>Encrypted chat backup (only if you choose it): a separate ciphertext blob of your history, encrypted on your device with a passphrase we never receive and cannot reset.</li>
      <li>Offline message queue: when a recipient is offline the message is briefly held so it can be delivered when they reconnect, then deleted on delivery or swept within 14 days.</li>
      <li>Minimal operational logs needed to run and secure the service, kept only as long as necessary and never containing message content.</li>
    </ul>
    <h2>Cloud storage (optional)</h2>
    <p>Cloud storage backs up your chat history — and only your chats — as encrypted ciphertext we cannot read. It is offered in tiers: a free allowance and paid monthly plans for more space. Your servers, posts and follows are communal and never count against this storage. You can see how much space you use, change or cancel your plan, and restore your chats on a new device with your key, all in Settings → Cloud storage. If a paid plan lapses you drop to the free tier; your last backup stays available to restore.</p>
    <h2>Encryption, and its limits</h2>
    <p>Messages and call setup are encrypted on your device before they travel (AES-256-GCM with an ECDH key exchange), so nobody between you and the person you are talking to can read them in transit. Call audio and video stay end-to-end encrypted the whole way and are never recorded.</p>
    <p>You can turn that off for a single conversation, and if you do we say so plainly: the setting asks you to confirm, and the chat itself carries a notice for as long as anything in it has travelled in the clear — on both people's phones, not only the one who chose it. It governs what YOU send. Nobody can switch off your encryption from their end.</p>
    <p>Stored messages are a different thing and we will not blur the two: your history is held on encrypted disks whose keys we hold, so we can read it. That is what lets your conversations appear on a new phone and lets us act on a reported message. If you want a copy only you can open, the encrypted chat backup uses a passphrase we never receive.</p>
    <h2>Service providers</h2>
    <ul>
      <li>Supabase — realtime message relay and the username directory (project hosted in Canada, ca-central-1).</li>
      <li>Stripe — processes payments and holds/pays out funds under its own agreements; handles identity verification (KYC) for people who receive money.</li>
      <li>Twilio — sends the one-time SMS code that verifies your number.</li>
    </ul>
    <h2>Data retention</h2>
    <p>Message content: not stored, nothing to retain. Username directory and payment metadata: kept until you delete your account, then removed. Operational logs: kept for a short period, then rotated out.</p>
    <h2>Your rights</h2>
    <p>Under PIPEDA (Canada) and, where applicable, the GDPR (EU) you can request access to, correction of, or deletion of the limited data we hold about you, and withdraw consent. Because we don’t store your messages, there is no message history for us to hand over or delete.</p>
    <h2>Safety</h2>
    <p>You can block and report other users from their profile. Reports are confidential and help us keep the community safe. Files you attach are checked on your device before they are sent: only real image files may be sent as photos, videos cannot be uploaded, executables and scripts are refused, and known prohibited content is blocked. This check runs locally — we do not see the file — and applies before anything leaves your device.</p>
    <h2>Children</h2>
    <p>OkayMessenger is not directed to children under 13 (or the minimum age in your region), and we do not knowingly collect their information.</p>
    <h2>Contact</h2>
    <p>Questions about privacy? Reach us at privacy@okay.chat.</p>
  <footer>The same text is shown inside the app, under Settings &rarr; About.</footer>
</main>
</body>
</html>
`;

const TERMS_HTML = `<!DOCTYPE html>
<!--
  GENERATED — do not edit by hand.
  Source: lib/legal/legal_content.dart · regenerate: dart tool/build_legal_pages.dart
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Terms of Service · OkayMessenger</title>
<style>
  :root { color-scheme: light dark; --fg: #1a1c1e; --dim: #5f6368; --bg: #ffffff; --rule: #e3e5e8; }
  @media (prefers-color-scheme: dark) {
    :root { --fg: #e8eaed; --dim: #9aa0a6; --bg: #121417; --rule: #2a2d31; }
  }
  html, body { margin: 0; background: var(--bg); }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    color: var(--fg); padding: 28px 20px 64px; box-sizing: border-box;
    -webkit-text-size-adjust: 100%;
  }
  main { max-width: 640px; margin: 0 auto; }
  h1 { font-size: 24px; margin: 0 0 4px; font-weight: 700; letter-spacing: -0.2px; }
  .meta { font-size: 13px; color: var(--dim); margin: 0 0 28px; }
  h2 {
    font-size: 17px; font-weight: 600; margin: 32px 0 8px;
    padding-top: 20px; border-top: 1px solid var(--rule);
  }
  h2:first-of-type { border-top: 0; padding-top: 0; margin-top: 0; }
  p { font-size: 15px; line-height: 1.6; margin: 0 0 12px; }
  ul { margin: 0 0 12px; padding-left: 20px; }
  li { font-size: 15px; line-height: 1.6; margin-bottom: 6px; }
  footer { margin-top: 40px; font-size: 13px; color: var(--dim); }
  a { color: inherit; }
</style>
</head>
<body>
<main>
  <h1>Terms of Service</h1>
  <p class="meta">OkayMessenger · Last updated: August 2026 · version 9</p>
    <h2>Acceptance</h2>
    <p>By using OkayMessenger you agree to these Terms. If you don’t agree, please don’t use the app.</p>
    <h2>The service</h2>
    <p>OkayMessenger is a private, local-first messenger. You are responsible for the content you send and for keeping your device secure. Because messages are stored only on devices, keep your own backups if you want to preserve them.</p>
    <h2>Payments</h2>
    <p>Peer-to-peer payments — money you send to or receive from another person in a chat — are processed by Stripe, and only these use Stripe. When you send or receive money you agree to the Stripe Connected Account Agreement and Stripe’s terms. OkayMessenger is not a bank or money-services business, does not hold your funds, and never takes custody of the money — funds move from the sender’s card through Stripe to the recipient’s Stripe account and are paid out to their bank by Stripe. We charge a small application fee per transaction, shown before you pay. You are responsible for any taxes on money you receive. Digital purchases are billed by the App Store instead, not Stripe: cloud storage, Okay AI Pro, a subscription to a creator, membership of a paid server, and tips to the developer. Of those, ONLY cloud storage renews by itself — see below. The other four are a one-time charge that unlocks something for 30 days and then simply stops; nothing renews unless you buy again.</p>
    <h2>Cloud storage subscription</h2>
    <p>Cloud storage backs up your chats. You get a free allowance, and can buy more space monthly — choose the amount you want, up to a maximum of 100 GB. There is no unlimited option. Paid storage is billed through your App Store account (Apple) at the price shown before you buy — not through Stripe. It is an auto-renewing subscription: it renews every month at the price shown, charged to your Apple ID at confirmation of purchase, until you cancel. To stop it, turn off auto-renew at least 24 hours before the period ends in your device Settings → your name → Subscriptions, which is also where you cancel — cancelling inside the app drops the plan in the app only. Your servers and posts are communal and never count against your storage. Fair use: downloads (egress) are limited to roughly three times your stored amount per month; sustained excess may be throttled. You can view usage and change or cancel your plan anytime in Settings → Cloud storage; cancelling drops you to the free tier and is not refundable for the current period. Fees and limits may change on notice.</p>
    <h2>Acceptable use</h2>
    <p>Don’t use OkayMessenger to break the law, harass others, send spam, infringe rights, or transmit malware. Files you attach are moderated on your device before sending: only genuine image files may be sent as photos, videos cannot be uploaded, executables and scripts are refused, oversized files are blocked, and known prohibited content is refused outright. Attempting to bypass these checks, or uploading unlawful content, is a violation of these Terms. We may limit or end access that violates these Terms. Use the in-app block and report tools if someone is abusing the service.</p>
    <h2>No warranty</h2>
    <p>The app is provided “as is” without warranties of any kind. If a recipient is offline the message is held briefly so it can be delivered when they reconnect, and is deleted on delivery or swept within 14 days, so we don’t guarantee delivery of anything older than that. Your message history is kept on our servers so it follows you between devices; we don’t guarantee it against loss, and the encrypted chat backup is there for a copy only you can open.</p>
    <h2>Limitation of liability</h2>
    <p>To the extent permitted by law, OkayMessenger is not liable for indirect or consequential damages arising from your use of the app.</p>
    <h2>Changes</h2>
    <p>We may update these Terms; continued use after an update means you accept the new Terms.</p>
    <h2>Governing law</h2>
    <p>These Terms are governed by the laws of Canada and your province of residence.</p>
    <h2>Contact</h2>
    <p>Questions about these Terms? Reach us at legal@okay.chat.</p>
  <footer>The same text is shown inside the app, under Settings &rarr; About.</footer>
</main>
</body>
</html>
`;

// supabase: verify_jwt = false
//
// The handful of web pages the app needs to exist, served from the project
// the app already depends on.
//
// A BROWSER OPENS THESE, so there is no Supabase session to send and the JWT
// gate must be OFF (same as payments-webhook and iap-notify). They read
// nothing, write nothing, and take no input — the worst an anonymous caller
// can do is read three paragraphs of static HTML.
//
// They used to be files on GitHub Pages, which is the problem they now solve.
// That site republishes the repository's README over the app for minutes
// after every push, so a confirmation link clicked in the wrong minute landed
// on "File not found" — and there is nothing the app can do about a page
// somebody opens in Safari on another device. Here there is no second system
// and no deploy race: if the app can reach its own backend, the page is up.
//
//   /functions/v1/pages                  what this app is (share/invite target)
//   /functions/v1/pages/done             Stripe's hosted flows return here
//   /functions/v1/pages/email-confirmed  where a confirmation link lands

const page = (title: string, heading: string, body: string) =>
  `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${title}</title>
<style>
  :root { color-scheme: light dark; --ink: #10131a; --dim: #6b7280; --bg: #ffffff; }
  @media (prefers-color-scheme: dark) {
    :root { --ink: #f2f4f8; --dim: #9aa1ad; --bg: #0d1015; }
  }
  html, body { margin: 0; height: 100%; background: var(--bg); }
  body {
    display: flex; align-items: center; justify-content: center;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    color: var(--ink); padding: 32px; box-sizing: border-box;
  }
  main { max-width: 30rem; text-align: center; }
  h1 { font-size: 1.5rem; font-weight: 700; margin: 0 0 0.75rem; }
  p { font-size: 1rem; line-height: 1.55; color: var(--dim); margin: 0 0 0.75rem; }
</style>
</head>
<body><main><h1>${heading}</h1>${body}</main></body>
</html>`;

const html = (body: string, status = 200) =>
  new Response(body, {
    status,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      // Cheap to render and it never changes between deploys, but keep it
      // short: this is also how a wrong page stops being served.
      "Cache-Control": "public, max-age=300",
      "Access-Control-Allow-Origin": "*",
    },
  });

const LANDING = page(
  "OkayMessenger",
  "OkayMessenger",
  `<p>A messenger that keeps your conversations on your own phone. Messages are
   encrypted before they leave the device, and there is no copy of them on any
   server to read, hand over, or lose.</p>
   <p>If somebody sent you this, ask them for an invite — that is currently the
   only way in.</p>`,
);

// Stripe's hosted flows finish by navigating to a return URL. In the app that
// navigation is caught and cancelled before anything renders, so this is only
// ever seen by somebody who got there in a real browser.
const DONE = page(
  "All done",
  "All done",
  `<p>You can close this window and go back to OkayMessenger.</p>`,
);

// Supabase reports a failure — an expired or already-used link — in the URL
// FRAGMENT, which never reaches a server. So the correction has to happen in
// the page: saying "confirmed" over the top of that would be a lie the reader
// only discovers later, in the app, with no idea why.
const EMAIL_CONFIRMED = page(
  "Email confirmed",
  "Email confirmed",
  `<p id="detail">Your address is verified. You can close this window — the app
   picks it up on its own the next time you open it.</p>
<script>
  (function () {
    var hash = window.location.hash || '';
    var params = new URLSearchParams(hash.replace(/^#/, ''));
    var error = params.get('error_description') || params.get('error');
    if (!error) return;
    document.querySelector('h1').textContent = 'Link didn’t work';
    document.getElementById('detail').textContent =
      error.replace(/\\+/g, ' ') +
      '. Open OkayMessenger and send yourself a new confirmation email.';
  })();
</script>`,
);

Deno.serve((req) => {
  // Last non-empty segment, so it works whether or not a slash is trailing.
  const parts = new URL(req.url).pathname.split("/").filter(Boolean);
  const leaf = parts[parts.length - 1] ?? "";
  switch (leaf) {
    case "done":
      return html(DONE);
    case "email-confirmed":
      return html(EMAIL_CONFIRMED);
    // The App Store needs a reachable Privacy Policy URL, and it must not be
    // a link to wherever the source lives. Served from here because this
    // function is already the app's one public host — the same reason every
    // other URL the app names comes off it.
    case "privacy":
      return html(PRIVACY_HTML);
    case "terms":
      return html(TERMS_HTML);
    default:
      // Anything else is the function's own root, or a path nobody meant.
      // Both get the landing page rather than a 404: a confirmation link with
      // a typo in it should still say something true.
      return html(LANDING);
  }
});
