// PASTE-READY, self-contained version of payments-status for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: payments-status
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/payments-status/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

import Stripe from "https://esm.sh/stripe@16.12.0?target=denonext";

// The generic request plumbing lives in http.ts; re-exported so existing
// imports from this file keep working unchanged.

const stripe = new Stripe(Deno.env.get("STRIPE_SECRET_KEY") ?? "", {
  apiVersion: "2024-06-20",
  httpClient: Stripe.createFetchHttpClient(),
});

/// The platform's application fee for an [amountCents] charge, in cents.
///
/// Transfers are DIRECT charges — the PaymentIntent is created on the
/// recipient's connected account — so the platform is never in the flow of
/// funds and never pays Stripe's processing fee. That makes this fee pure
/// revenue, and means no floor is needed: unlike a destination charge, there
/// is no platform-side cost for it to fail to clear.
///
/// Stripe's cut (2.9% + 30c domestic, more on a foreign card) comes out of the
/// recipient's account instead, which is why the send sheet quotes an
/// approximate landing amount rather than the amount typed.
function applicationFee(amountCents: number): number {
  const pct = parseFloat(Deno.env.get("PLATFORM_FEE_PERCENT") ?? "3.4");
  const fixed = parseInt(Deno.env.get("PLATFORM_FEE_FIXED_CENTS") ?? "10", 10);
  return Math.max(0, Math.round((amountCents * pct) / 100) + fixed);
}

/// Stripe's published card rates, mirroring StorageEconomics in
/// lib/payments/storage_economics.dart — the Dart side is the documented
/// source of these numbers and the test suite holds it to them.
///
/// Not read from the environment on purpose: these are Stripe's prices, not
/// ours. A deployment cannot negotiate them, and an env var would only offer
/// a way to gross up against a rate Stripe isn't charging.
const STRIPE_PERCENT = 2.9;
const STRIPE_FIXED_CENTS = 30;

/// Stripe's extra cut on a card issued abroad. The card's country is only
/// known after the charge, so grossing up has to assume it.
const STRIPE_INTERNATIONAL_SURCHARGE_PERCENT = 1.5;

/// Stripe's own cost for a charge of [amountCents] on a domestic card. Paid by
/// the recipient's account on a direct charge, which is why it has to be
/// accounted for when grossing up.
function stripeCost(amountCents: number): number {
  return Math.round((amountCents * STRIPE_PERCENT) / 100) + STRIPE_FIXED_CENTS;
}

/// What the sender must be charged so [targetCents] actually reaches the
/// recipient.
///
/// Both fees come out of the transfer, so charging exactly what was typed
/// delivers less than that. Grossing up moves the fees onto the sender, which
/// is what people expect when they type a number.
///
/// Solved by search rather than algebra: the fees round to whole cents, so a
/// closed form lands a cent out either way. Mirrors grossUpCents() in
/// lib/payments/storage_economics.dart.
function grossUp(targetCents: number): number {
  if (targetCents <= 0) return 0;
  const pct = parseFloat(Deno.env.get("PLATFORM_FEE_PERCENT") ?? "3.4");
  const fixed = parseInt(Deno.env.get("PLATFORM_FEE_FIXED_CENTS") ?? "10", 10);
  // Grossed up against the WORST-case Stripe rate. The sender picks the card
  // and its country is only known afterwards, so budgeting on the domestic
  // rate would under-deliver every international transfer — the recipient
  // would get less than the sender typed, which is the one promise this
  // makes. Erring the other way costs a domestic sender a few cents and the
  // surplus goes to the recipient, never to the platform.
  const worst = STRIPE_PERCENT + STRIPE_INTERNATIONAL_SURCHARGE_PERCENT;
  const worstCost = (t: number) =>
    Math.round((t * worst) / 100) + STRIPE_FIXED_CENTS;
  const rate = 1 - (pct + worst) / 100;
  let total = Math.floor((targetCents + fixed + STRIPE_FIXED_CENTS) / rate);
  for (let i = 0; i < 12; i++) {
    if (total - worstCost(total) - applicationFee(total) >= targetCents) {
      return total;
    }
    total++;
  }
  return total;
}

// The debit-card rules, pure so they can be executed without Stripe.
//
// WHY THESE EXIST. The debit card is where instant payouts LAND — whoever
// controls it walks away with the balance. The classic account-takeover
// drains in one motion: sign in, attach your own card, cash out in minutes.
// Two rules close it, both enforced server-side because a client-side rule
// is a suggestion:
//
//   * A newly attached card waits SEVEN BUSINESS DAYS before instant
//     payouts may land on it — long enough for the real owner to notice a
//     takeover and act, which is the entire point of the delay. Standard
//     bank payouts are untouched: they go to the bank account, which an
//     attacker's card swap does not redirect.
//   * Attaching cards too often locks the feature: the third card inside
//     thirty days is not somebody correcting a typo. The lock releases on
//     its own as the changes age out of the window.

const CARD_HOLD_BUSINESS_DAYS = 7;
const CARD_CHANGE_WINDOW_DAYS = 30;
const CARD_CHANGE_LIMIT = 3;

/// Whole business days (Mon–Fri, UTC) elapsed from [from] to [to]. Partial
/// days do not count — "seven business days" must never round down to six
/// and a bit.
function businessDaysBetween(from: Date, to: Date): number {
  if (to.getTime() <= from.getTime()) return 0;
  let days = 0;
  const cursor = new Date(Date.UTC(
    from.getUTCFullYear(),
    from.getUTCMonth(),
    from.getUTCDate(),
  ));
  const end = new Date(Date.UTC(
    to.getUTCFullYear(),
    to.getUTCMonth(),
    to.getUTCDate(),
  ));
  while (cursor.getTime() < end.getTime()) {
    cursor.setUTCDate(cursor.getUTCDate() + 1);
    const dow = cursor.getUTCDay();
    if (dow !== 0 && dow !== 6) days++;
  }
  return days;
}

/// The verdict on this account's card, from its attach history.
///
/// [attachedAts] is every recorded attach, any order. An account with no
/// recorded attaches is neither held nor locked: cards added before this
/// policy existed have already had their waiting period in the world.
function cardPolicy(opts: { attachedAts: Date[]; now: Date }): {
  locked: boolean;
  held: boolean;
  businessDaysLeft: number;
} {
  const { attachedAts, now } = opts;
  const windowStart = now.getTime() -
    CARD_CHANGE_WINDOW_DAYS * 24 * 60 * 60 * 1000;
  const recent = attachedAts.filter((a) => a.getTime() > windowStart);
  const locked = recent.length >= CARD_CHANGE_LIMIT;
  if (attachedAts.length === 0) {
    return { locked, held: false, businessDaysLeft: 0 };
  }
  const latest = new Date(
    Math.max(...attachedAts.map((a) => a.getTime())),
  );
  const elapsed = businessDaysBetween(latest, now);
  const held = elapsed < CARD_HOLD_BUSINESS_DAYS;
  return {
    locked,
    held,
    businessDaysLeft: held ? CARD_HOLD_BUSINESS_DAYS - elapsed : 0,
  };
}

// Returns the caller's payment/KYC status and their connected-account balance
// (available + pending) plus the latest payout status, so the app can show a
// wallet with a "cash out" state. Balance is read live from Stripe; funds are
// never held by the platform.
//
// POST  ->  { onboarded, chargesEnabled, payoutsEnabled, available, pending,
//             currency, payout: { status, amount, arrivalDate } | null }


Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const phone = await callerPhone(req);
  if (!phone) return json({ error: "unauthorized" }, 401);

  const { data: acct } = await admin
    .from("payment_accounts")
    .select("stripe_account_id")
    .eq("phone", phone)
    .maybeSingle();

  if (!acct?.stripe_account_id) {
    return json({ onboarded: false, chargesEnabled: false, payoutsEnabled: false });
  }
  const accountId = acct.stripe_account_id as string;

  try {
    const account = await stripe.accounts.retrieve(accountId);
    const balance = await stripe.balance.retrieve({ stripeAccount: accountId });

    const sum = (arr: { amount: number }[]) =>
      arr.reduce((n, b) => n + b.amount, 0);
    const currency = balance.available[0]?.currency ?? "cad";

    // What can be cashed out to a debit card right now. Its own bucket, not
    // a slice of `available` — showing the ordinary balance beside a "cash
    // out instantly" button would offer money Stripe will refuse to move.
    const instantAvailable = sum(
      (balance as { instant_available?: { amount: number }[] })
        .instant_available ?? [],
    );
    const externals = (account.external_accounts?.data ?? []) as {
      object?: string;
      last4?: string;
      brand?: string;
      default_for_currency?: boolean;
    }[];
    const cards = externals.filter((e) => e.object === "card");
    // The default for the currency is the one Stripe would pick itself, so
    // picking anything else would surprise somebody.
    const card = cards.find((c) => c.default_for_currency) ?? cards[0];
    const banks = externals.filter((e) => e.object === "bank_account");
    const bank = banks.find((b) => b.default_for_currency) ?? banks[0];

    // The takeover safeguards' verdicts, so the wallet can say WHY a button
    // is off with a number instead of a refusal three taps later.
    const { data: attachEvents } = await admin
      .from("payment_card_events")
      .select("created_at, kind")
      .eq("phone", phone)
      .order("created_at", { ascending: false })
      .limit(24);
    const ats = (kind: string) =>
      (attachEvents ?? [])
        .filter((e) => ((e as { kind?: string }).kind ?? "card") === kind)
        .map((e) => new Date((e as { created_at: string }).created_at));
    const now = new Date();
    const cardVerdict = cardPolicy({ attachedAts: ats("card"), now });
    const bankVerdict = cardPolicy({ attachedAts: ats("bank"), now });

    // A bank change paused automatic payouts for the hold; the moment the
    // hold has passed, the next wallet visit turns them back on. This app
    // never sets the schedule to manual for any other reason.
    const interval = (account as {
      settings?: { payouts?: { schedule?: { interval?: string } } };
    }).settings?.payouts?.schedule?.interval;
    if (
      !bankVerdict.held && ats("bank").length > 0 && interval === "manual"
    ) {
      try {
        await stripe.accounts.update(accountId, {
          settings: { payouts: { schedule: { interval: "daily" } } },
        });
      } catch (_) { /* the next visit tries again */ }
    }

    // Keep our cached KYC flags fresh.
    await admin.from("payment_accounts").update({
      charges_enabled: account.charges_enabled,
      payouts_enabled: account.payouts_enabled,
      details_submitted: account.details_submitted,
      updated_at: new Date().toISOString(),
    }).eq("phone", phone);

    const { data: payout } = await admin
      .from("payout_status")
      .select("status, amount_cents, arrival_date")
      .eq("stripe_account_id", accountId)
      .maybeSingle();

    return json({
      onboarded: account.details_submitted,
      chargesEnabled: account.charges_enabled,
      payoutsEnabled: account.payouts_enabled,
      available: sum(balance.available),
      pending: sum(balance.pending),
      instantAvailable,
      currency,
      country: (account as { country?: string }).country ?? null,
      hasDebitCard: card !== undefined,
      cardLast4: card?.last4 ?? null,
      cardBrand: card?.brand ?? null,
      cardHoldBusinessDaysLeft: cardVerdict.businessDaysLeft,
      cardLocked: cardVerdict.locked,
      bankLast4: bank?.last4 ?? null,
      bankHoldBusinessDaysLeft: bankVerdict.businessDaysLeft,
      payout: payout
        ? {
          status: payout.status,
          amount: payout.amount_cents,
          arrivalDate: payout.arrival_date,
        }
        : null,
    });
  } catch (e) {
    return json({ error: String((e as Error).message ?? e) }, 400);
  }
});
