// PASTE-READY, self-contained version of payments-payout for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: payments-payout
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/payments-payout/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

import Stripe from "https://esm.sh/stripe@16.12.0?target=denonext";

// The generic request plumbing lives in http.ts; re-exported so existing
// imports from this file keep working unchanged.

const stripe = new Stripe(Deno.env.get("STRIPE_SECRET_KEY") ?? "", {
  apiVersion: "2024-06-20",
  httpClient: Stripe.createFetchHttpClient(),
});

/// The platform's application fee for an [amountCents] charge, in cents.
///
/// Transfers are DIRECT charges — the PaymentIntent is created on the
/// recipient's connected account — so the platform is never in the flow of
/// funds and never pays Stripe's processing fee. That makes this fee pure
/// revenue, and means no floor is needed: unlike a destination charge, there
/// is no platform-side cost for it to fail to clear.
///
/// Stripe's cut (2.9% + 30c domestic, more on a foreign card) comes out of the
/// recipient's account instead, which is why the send sheet quotes an
/// approximate landing amount rather than the amount typed.
function applicationFee(amountCents: number): number {
  const pct = parseFloat(Deno.env.get("PLATFORM_FEE_PERCENT") ?? "3.4");
  const fixed = parseInt(Deno.env.get("PLATFORM_FEE_FIXED_CENTS") ?? "10", 10);
  return Math.max(0, Math.round((amountCents * pct) / 100) + fixed);
}

/// Stripe's published card rates, mirroring StorageEconomics in
/// lib/payments/storage_economics.dart — the Dart side is the documented
/// source of these numbers and the test suite holds it to them.
///
/// Not read from the environment on purpose: these are Stripe's prices, not
/// ours. A deployment cannot negotiate them, and an env var would only offer
/// a way to gross up against a rate Stripe isn't charging.
const STRIPE_PERCENT = 2.9;
const STRIPE_FIXED_CENTS = 30;

/// Stripe's extra cut on a card issued abroad. The card's country is only
/// known after the charge, so grossing up has to assume it.
const STRIPE_INTERNATIONAL_SURCHARGE_PERCENT = 1.5;

/// Stripe's own cost for a charge of [amountCents] on a domestic card. Paid by
/// the recipient's account on a direct charge, which is why it has to be
/// accounted for when grossing up.
function stripeCost(amountCents: number): number {
  return Math.round((amountCents * STRIPE_PERCENT) / 100) + STRIPE_FIXED_CENTS;
}

/// What the sender must be charged so [targetCents] actually reaches the
/// recipient.
///
/// Both fees come out of the transfer, so charging exactly what was typed
/// delivers less than that. Grossing up moves the fees onto the sender, which
/// is what people expect when they type a number.
///
/// Solved by search rather than algebra: the fees round to whole cents, so a
/// closed form lands a cent out either way. Mirrors grossUpCents() in
/// lib/payments/storage_economics.dart.
function grossUp(targetCents: number): number {
  if (targetCents <= 0) return 0;
  const pct = parseFloat(Deno.env.get("PLATFORM_FEE_PERCENT") ?? "3.4");
  const fixed = parseInt(Deno.env.get("PLATFORM_FEE_FIXED_CENTS") ?? "10", 10);
  // Grossed up against the WORST-case Stripe rate. The sender picks the card
  // and its country is only known afterwards, so budgeting on the domestic
  // rate would under-deliver every international transfer — the recipient
  // would get less than the sender typed, which is the one promise this
  // makes. Erring the other way costs a domestic sender a few cents and the
  // surplus goes to the recipient, never to the platform.
  const worst = STRIPE_PERCENT + STRIPE_INTERNATIONAL_SURCHARGE_PERCENT;
  const worstCost = (t: number) =>
    Math.round((t * worst) / 100) + STRIPE_FIXED_CENTS;
  const rate = 1 - (pct + worst) / 100;
  let total = Math.floor((targetCents + fixed + STRIPE_FIXED_CENTS) / rate);
  for (let i = 0; i < 12; i++) {
    if (total - worstCost(total) - applicationFee(total) >= targetCents) {
      return total;
    }
    total++;
  }
  return total;
}

// The debit-card rules, pure so they can be executed without Stripe.
//
// WHY THESE EXIST. The debit card is where instant payouts LAND — whoever
// controls it walks away with the balance. The classic account-takeover
// drains in one motion: sign in, attach your own card, cash out in minutes.
// Two rules close it, both enforced server-side because a client-side rule
// is a suggestion:
//
//   * A newly attached card waits SEVEN BUSINESS DAYS before instant
//     payouts may land on it — long enough for the real owner to notice a
//     takeover and act, which is the entire point of the delay. Standard
//     bank payouts are untouched: they go to the bank account, which an
//     attacker's card swap does not redirect.
//   * Attaching cards too often locks the feature: the third card inside
//     thirty days is not somebody correcting a typo. The lock releases on
//     its own as the changes age out of the window.

const CARD_HOLD_BUSINESS_DAYS = 7;
const CARD_CHANGE_WINDOW_DAYS = 30;
const CARD_CHANGE_LIMIT = 3;

/// Whole business days (Mon–Fri, UTC) elapsed from [from] to [to]. Partial
/// days do not count — "seven business days" must never round down to six
/// and a bit.
function businessDaysBetween(from: Date, to: Date): number {
  if (to.getTime() <= from.getTime()) return 0;
  let days = 0;
  const cursor = new Date(Date.UTC(
    from.getUTCFullYear(),
    from.getUTCMonth(),
    from.getUTCDate(),
  ));
  const end = new Date(Date.UTC(
    to.getUTCFullYear(),
    to.getUTCMonth(),
    to.getUTCDate(),
  ));
  while (cursor.getTime() < end.getTime()) {
    cursor.setUTCDate(cursor.getUTCDate() + 1);
    const dow = cursor.getUTCDay();
    if (dow !== 0 && dow !== 6) days++;
  }
  return days;
}

/// The verdict on this account's card, from its attach history.
///
/// [attachedAts] is every recorded attach, any order. An account with no
/// recorded attaches is neither held nor locked: cards added before this
/// policy existed have already had their waiting period in the world.
function cardPolicy(opts: { attachedAts: Date[]; now: Date }): {
  locked: boolean;
  held: boolean;
  businessDaysLeft: number;
} {
  const { attachedAts, now } = opts;
  const windowStart = now.getTime() -
    CARD_CHANGE_WINDOW_DAYS * 24 * 60 * 60 * 1000;
  const recent = attachedAts.filter((a) => a.getTime() > windowStart);
  const locked = recent.length >= CARD_CHANGE_LIMIT;
  if (attachedAts.length === 0) {
    return { locked, held: false, businessDaysLeft: 0 };
  }
  const latest = new Date(
    Math.max(...attachedAts.map((a) => a.getTime())),
  );
  const elapsed = businessDaysBetween(latest, now);
  const held = elapsed < CARD_HOLD_BUSINESS_DAYS;
  return {
    locked,
    held,
    businessDaysLeft: held ? CARD_HOLD_BUSINESS_DAYS - elapsed : 0,
  };
}

// Cash out to a debit card, in minutes rather than days.
//
// Stripe's standard payout goes to a bank account and settles on a schedule.
// An INSTANT payout goes to a debit card the account has already attached, and
// lands in minutes — for a fee Stripe charges the connected account, never the
// platform. That is the whole reason this can exist without a fee of ours on
// top: there is no platform-side cost to clear.
//
// Two things this deliberately does NOT do:
//
//   * It does not invent a maximum. Stripe reports what is instantly
//     available for this specific account and that number is the ceiling;
//     an amount picked here would be wrong for somebody.
//   * It does not attach the card. Card details must never reach this
//     function or the app — the debit card is added through Stripe's own
//     `payouts` embedded component (see payments-account-session), which is
//     also where Stripe asks the questions it needs to ask.
//
// POST { amountCents?, method? }  ->  { ok, payoutId, status, amountCents,
//                                       feeCents, arrivalDate, method }
// POST { what: "quote" }          ->  { instantAvailable, currency, country,
//                                       hasDebitCard, cardLast4, cardBrand }


/// Stripe's published instant-payout rate by country, mirroring
/// InstantPayoutEconomics on the client. Quoted here too so the receipt the
/// app stores is the server's number, not one the client worked out.
const INSTANT_PERCENT: Record<string, number> = {
  CA: 1.0,
  US: 1.5,
  AU: 1.5,
  GB: 1.0,
  SG: 1.0,
};
const FALLBACK_PERCENT = 1.5;

function feeCentsFor(amountCents: number, country: string | null): number {
  const pct = INSTANT_PERCENT[(country ?? "").toUpperCase()] ?? FALLBACK_PERCENT;
  return Math.ceil((amountCents * pct) / 100);
}

/// The attached external account that a card payout can actually go to.
/// Stripe allows several; the default for the currency is the one it would
/// pick itself, so picking anything else would surprise somebody.
function pickDebitCard(
  account: { external_accounts?: { data?: unknown[] } },
): { id: string; last4?: string; brand?: string; currency?: string } | null {
  const list = account.external_accounts?.data ?? [];
  const cards = list.filter((e) => (e as { object?: string }).object === "card");
  if (cards.length === 0) return null;
  const preferred = cards.find((c) => (c as { default_for_currency?: boolean })
    .default_for_currency) ?? cards[0];
  return preferred as { id: string; last4?: string; brand?: string };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  const phone = await callerPhone(req);
  if (!phone) return json({ error: "unauthorized" }, 401);

  // Cashing out is money leaving, so it carries the same lock the wallet's
  // other write does: a banned account does not get to move funds while a
  // dispute against it is open.
  const { data: ban } = await admin
    .from("payment_bans")
    .select("reason")
    .eq("phone", phone)
    .maybeSingle();
  if (ban) return json({ error: "sender_banned" }, 403);

  const { data: acct } = await admin
    .from("payment_accounts")
    .select("stripe_account_id")
    .eq("phone", phone)
    .maybeSingle();
  if (!acct?.stripe_account_id) return json({ error: "not_onboarded" }, 400);
  const accountId = acct.stripe_account_id as string;

  let body: { amountCents?: number; method?: string; what?: string } = {};
  try {
    body = await req.json();
  } catch { /* an empty body means "quote" */ }

  try {
    const account = await stripe.accounts.retrieve(accountId);
    const country = (account as { country?: string }).country ?? null;
    const card = pickDebitCard(account as { external_accounts?: { data?: unknown[] } });

    // The card's standing under the takeover safeguards: a newly attached
    // card waits seven business days, and too many changes lock instants.
    const { data: attachEvents } = await admin
      .from("payment_card_events")
      .select("created_at, kind")
      .eq("phone", phone)
      .order("created_at", { ascending: false })
      .limit(24);
    const ats = (kind: string) =>
      (attachEvents ?? [])
        .filter((e) => ((e as { kind?: string }).kind ?? "card") === kind)
        .map((e) => new Date((e as { created_at: string }).created_at));
    const policy = cardPolicy({ attachedAts: ats("card"), now: new Date() });
    // The bank's own hold: a changed direct deposit is the other half of
    // the drain, and no manual payout goes to it while the hold runs.
    const bankPolicy = cardPolicy({
      attachedAts: ats("bank"),
      now: new Date(),
    });

    const balance = await stripe.balance.retrieve({ stripeAccount: accountId });
    // `instant_available` is its own bucket and is NOT a slice of
    // `available` — reading the ordinary available balance here would offer
    // people money Stripe will refuse to move instantly.
    const instant = ((balance as {
      instant_available?: { amount: number; currency: string }[];
    }).instant_available ?? []);
    const instantAvailable = instant.reduce((n, b) => n + b.amount, 0);
    const currency = instant[0]?.currency ??
      balance.available[0]?.currency ?? "cad";

    if (body.what === "quote") {
      return json({
        instantAvailable,
        currency,
        country,
        hasDebitCard: card !== null,
        cardLast4: card?.last4 ?? null,
        cardBrand: card?.brand ?? null,
        // So the wallet says WHY the instant button is off, with a number.
        cardHoldBusinessDaysLeft: policy.businessDaysLeft,
        cardLocked: policy.locked,
        bankHoldBusinessDaysLeft: bankPolicy.businessDaysLeft,
        payoutsEnabled: account.payouts_enabled,
      });
    }

    const method = body.method === "standard" ? "standard" : "instant";
    const amountCents = Math.round(Number(body.amountCents ?? 0));
    if (!Number.isFinite(amountCents) || amountCents <= 0) {
      return json({ error: "invalid amount" }, 400);
    }

    if (method === "standard" && bankPolicy.held) {
      return json({
        error: "bank_hold",
        businessDaysLeft: bankPolicy.businessDaysLeft,
      }, 403);
    }
    if (method === "instant") {
      if (!card) return json({ error: "no_debit_card" }, 400);
      // The takeover safeguards, at the moment money would actually move.
      // Standard bank payouts are untouched: a card swap does not redirect
      // where those land.
      if (policy.locked) {
        return json({ error: "card_changes_locked" }, 429);
      }
      if (policy.held) {
        return json({
          error: "card_hold",
          businessDaysLeft: policy.businessDaysLeft,
        }, 403);
      }
      if (amountCents > instantAvailable) {
        return json({
          error: "over_instant_balance",
          instantAvailable,
        }, 400);
      }
    }

    const payout = await stripe.payouts.create({
      amount: amountCents,
      currency,
      method,
      ...(method === "instant" && card ? { destination: card.id } : {}),
      metadata: {
        phone,
        // Recorded at the time, like the transfer evidence is: what somebody
        // was told the fee would be is not reconstructable afterwards.
        quoted_fee_cents: String(feeCentsFor(amountCents, country)),
      },
    }, { stripeAccount: accountId });

    // The webhook keeps payout_status current, but it arrives when it
    // arrives; writing here means the wallet reflects the tap immediately
    // rather than looking like nothing happened.
    await admin.from("payout_status").upsert({
      stripe_account_id: accountId,
      status: payout.status,
      amount_cents: payout.amount,
      arrival_date: new Date(payout.arrival_date * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    });

    return json({
      ok: true,
      payoutId: payout.id,
      status: payout.status,
      amountCents: payout.amount,
      feeCents: feeCentsFor(amountCents, country),
      arrivalDate: new Date(payout.arrival_date * 1000).toISOString(),
      method,
    });
  } catch (e) {
    // Stripe's own words. Its refusals here are specific and useful —
    // "insufficient funds", "no such external account", instant payouts not
    // enabled — and paraphrasing them costs the person the one sentence that
    // says what to fix.
    return json({ error: String((e as Error).message ?? e) }, 400);
  }
});
