// PASTE-READY, self-contained version of payments-onboard for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: payments-onboard
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/payments-onboard/index.ts with the
// _shared/stripe.ts helpers inlined (the paste editor has no shared files).
// Edit the sources, then re-run the tool.

import Stripe from "https://esm.sh/stripe@16.12.0?target=deno";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const stripe = new Stripe(Deno.env.get("STRIPE_SECRET_KEY") ?? "", {
  apiVersion: "2024-06-20",
  httpClient: Stripe.createFetchHttpClient(),
});

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Payments require an authenticated, phone-verified user.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

/// The platform's application fee for an [amountCents] charge, in cents.
///
/// This MUST exceed what Stripe charges the platform, or every transfer loses
/// money. On a destination charge the platform is the merchant of record, so
/// Stripe's processing fee (2.9% + 30¢ on standard CAD/USD cards) comes out of
/// the platform's balance while only `application_fee_amount` comes back in.
///
/// The defaults below (3.4% + 35¢) clear that with a thin margin:
///   $10 transfer → fee 69¢ in, Stripe takes 59¢ → +10¢
///   $50 transfer → fee $2.05 in, Stripe takes $1.75 → +30¢
/// Override via PLATFORM_FEE_PERCENT / PLATFORM_FEE_FIXED_CENTS, but keep them
/// above Stripe's own rate for your region or the platform pays the difference.
const STRIPE_PERCENT = 2.9;
const STRIPE_FIXED_CENTS = 30;

function applicationFee(amountCents: number): number {
  const pct = parseFloat(Deno.env.get("PLATFORM_FEE_PERCENT") ?? "3.4");
  const fixed = parseInt(Deno.env.get("PLATFORM_FEE_FIXED_CENTS") ?? "35", 10);
  const fee = Math.round((amountCents * pct) / 100) + fixed;
  // Never let a misconfigured env var make the platform eat Stripe's cut.
  const stripeCost =
    Math.round((amountCents * STRIPE_PERCENT) / 100) + STRIPE_FIXED_CENTS;
  return Math.max(fee, stripeCost + 1);
}

// Creates (or reuses) a Stripe Express connected account for the caller and
// returns a Stripe-hosted onboarding link (account_link) for KYC. This is the
// only hosted step — Stripe requires it for Express identity verification. The
// actual sending of money is fully native (see payments-create-intent).
//
// POST  ->  { url, accountId, chargesEnabled, payoutsEnabled, detailsSubmitted }


Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const phone = await callerPhone(req);
  if (!phone) return json({ error: "unauthorized" }, 401);

  try {
    // Reuse an existing account, or create a new Canadian Express account.
    const { data: existing } = await admin
      .from("payment_accounts")
      .select("stripe_account_id")
      .eq("phone", phone)
      .maybeSingle();

    let accountId = existing?.stripe_account_id as string | undefined;
    if (!accountId) {
      const account = await stripe.accounts.create({
        type: "express",
        country: "CA",
        capabilities: {
          card_payments: { requested: true },
          transfers: { requested: true },
        },
        business_type: "individual",
        metadata: { phone },
      });
      accountId = account.id;
      await admin.from("payment_accounts").upsert({
        phone,
        stripe_account_id: accountId,
        updated_at: new Date().toISOString(),
      });
    }

    const returnUrl = Deno.env.get("APP_RETURN_URL") ?? "okaymsg://payments/return";
    const link = await stripe.accountLinks.create({
      account: accountId,
      refresh_url: returnUrl,
      return_url: returnUrl,
      type: "account_onboarding",
    });

    const account = await stripe.accounts.retrieve(accountId);
    await admin.from("payment_accounts").update({
      charges_enabled: account.charges_enabled,
      payouts_enabled: account.payouts_enabled,
      details_submitted: account.details_submitted,
      updated_at: new Date().toISOString(),
    }).eq("phone", phone);

    return json({
      url: link.url,
      accountId,
      chargesEnabled: account.charges_enabled,
      payoutsEnabled: account.payouts_enabled,
      detailsSubmitted: account.details_submitted,
    });
  } catch (e) {
    return json({ error: String((e as Error).message ?? e) }, 400);
  }
});
