// PASTE-READY, self-contained version of payments-create-intent for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: payments-create-intent
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/payments-create-intent/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

import Stripe from "https://esm.sh/stripe@16.12.0?target=denonext";

// The generic request plumbing lives in http.ts; re-exported so existing
// imports from this file keep working unchanged.

const stripe = new Stripe(Deno.env.get("STRIPE_SECRET_KEY") ?? "", {
  apiVersion: "2024-06-20",
  httpClient: Stripe.createFetchHttpClient(),
});

/// The platform's application fee for an [amountCents] charge, in cents.
///
/// Transfers are DIRECT charges — the PaymentIntent is created on the
/// recipient's connected account — so the platform is never in the flow of
/// funds and never pays Stripe's processing fee. That makes this fee pure
/// revenue, and means no floor is needed: unlike a destination charge, there
/// is no platform-side cost for it to fail to clear.
///
/// Stripe's cut (2.9% + 30c domestic, more on a foreign card) comes out of the
/// recipient's account instead, which is why the send sheet quotes an
/// approximate landing amount rather than the amount typed.
function applicationFee(amountCents: number): number {
  const pct = parseFloat(Deno.env.get("PLATFORM_FEE_PERCENT") ?? "3.4");
  const fixed = parseInt(Deno.env.get("PLATFORM_FEE_FIXED_CENTS") ?? "10", 10);
  return Math.max(0, Math.round((amountCents * pct) / 100) + fixed);
}

/// Stripe's published card rates, mirroring StorageEconomics in
/// lib/payments/storage_economics.dart — the Dart side is the documented
/// source of these numbers and the test suite holds it to them.
///
/// Not read from the environment on purpose: these are Stripe's prices, not
/// ours. A deployment cannot negotiate them, and an env var would only offer
/// a way to gross up against a rate Stripe isn't charging.
const STRIPE_PERCENT = 2.9;
const STRIPE_FIXED_CENTS = 30;

/// Stripe's extra cut on a card issued abroad. The card's country is only
/// known after the charge, so grossing up has to assume it.
const STRIPE_INTERNATIONAL_SURCHARGE_PERCENT = 1.5;

/// Stripe's own cost for a charge of [amountCents] on a domestic card. Paid by
/// the recipient's account on a direct charge, which is why it has to be
/// accounted for when grossing up.
function stripeCost(amountCents: number): number {
  return Math.round((amountCents * STRIPE_PERCENT) / 100) + STRIPE_FIXED_CENTS;
}

/// What the sender must be charged so [targetCents] actually reaches the
/// recipient.
///
/// Both fees come out of the transfer, so charging exactly what was typed
/// delivers less than that. Grossing up moves the fees onto the sender, which
/// is what people expect when they type a number.
///
/// Solved by search rather than algebra: the fees round to whole cents, so a
/// closed form lands a cent out either way. Mirrors grossUpCents() in
/// lib/payments/storage_economics.dart.
function grossUp(targetCents: number): number {
  if (targetCents <= 0) return 0;
  const pct = parseFloat(Deno.env.get("PLATFORM_FEE_PERCENT") ?? "3.4");
  const fixed = parseInt(Deno.env.get("PLATFORM_FEE_FIXED_CENTS") ?? "10", 10);
  // Grossed up against the WORST-case Stripe rate. The sender picks the card
  // and its country is only known afterwards, so budgeting on the domestic
  // rate would under-deliver every international transfer — the recipient
  // would get less than the sender typed, which is the one promise this
  // makes. Erring the other way costs a domestic sender a few cents and the
  // surplus goes to the recipient, never to the platform.
  const worst = STRIPE_PERCENT + STRIPE_INTERNATIONAL_SURCHARGE_PERCENT;
  const worstCost = (t: number) =>
    Math.round((t * worst) / 100) + STRIPE_FIXED_CENTS;
  const rate = 1 - (pct + worst) / 100;
  let total = Math.floor((targetCents + fixed + STRIPE_FIXED_CENTS) / rate);
  for (let i = 0; i < 12; i++) {
    if (total - worstCost(total) - applicationFee(total) >= targetCents) {
      return total;
    }
    total++;
  }
  return total;
}

// The numbers a transfer is checked against, and what changing one does.
//
// Kept here rather than inside the functions because these are the rules, and
// rules that nobody runs drift. `payment_limits_test.mjs` executes every branch
// below without Supabase in the picture — this file is pure: no I/O, no Deno
// globals, no clock of its own (callers pass `nowMs`).

/// What may leave an account in a rolling 24 hours when it has never chosen.
const DEFAULT_DAILY_LIMIT_CENTS = 50000; // $500

/// The ceiling on the ceiling. An account may not hand itself a bigger day
/// than this, whatever it asks for.
const MAX_DAILY_LIMIT_CENTS = 200000; // $2,000

/// The largest a single transfer may be. Same ceiling, different question:
/// a day's worth of small mistakes and one big one are not the same failure.
const MAX_PER_SEND_CENTS = 200000;

/// Zero means "no cap of this kind" — never "nothing may be sent". Both limits
/// use it, so the two read the same way, and so lifting a cap sorts as the
/// loosening it is rather than as the tightest possible setting.
const NO_CAP = 0;

/// Loosening a limit waits this long before it means anything. Tightening one
/// is immediate.
///
/// Without this the limits are advice. Someone holding an unlocked phone holds
/// the session too, so they can call payments-settings and raise the day to its
/// ceiling before sending — the limit stops nothing it was written to stop.
/// With the delay, what they can move is whatever the owner chose while calm.
const RAISE_DELAY_MS = 24 * 60 * 60 * 1000;

/// The `payment_settings` columns this file cares about.
interface LimitRow {
  daily_send_limit_cents?: number | null;
  max_send_cents?: number | null;
  pending_daily_send_limit_cents?: number | null;
  pending_daily_effective_at?: string | null;
  pending_max_send_cents?: number | null;
  pending_max_effective_at?: string | null;
}

/// A raise that has been asked for but has not arrived yet.
interface PendingLimit {
  cents: number;
  at: string;
}

interface EffectiveLimits {
  dailyCents: number;
  maxSendCents: number;
  pendingDaily: PendingLimit | null;
  pendingMax: PendingLimit | null;
}

/// Ordering that understands zero. A cap of 0 is no cap, so it sorts above
/// every real number rather than below all of them.
function rank(cents: number): number {
  return cents <= NO_CAP ? Infinity : cents;
}

function clamp(cents: number, ceiling: number): number {
  return Math.min(Math.max(Math.round(cents), 0), ceiling);
}

/// A number that can be a limit. `typeof x === "number"` is true of NaN and of
/// Infinity, and clamping either one lands on zero — which means *no cap*, so
/// the worst possible input would quietly buy the most permissive setting.
/// Garbage is ignored instead.
function asked(cents: number | undefined): cents is number {
  return typeof cents === "number" && Number.isFinite(cents);
}

/// Whether a pending value has come due. A row with no timestamp has nothing
/// pending; an unparseable one is treated as not due, which errs toward the
/// tighter number.
function due(at: string | null | undefined, nowMs: number): boolean {
  if (!at) return false;
  const t = Date.parse(at);
  return Number.isFinite(t) && t <= nowMs;
}

/// What the limits actually are right now, matured raises included.
///
/// Maturing is computed, not written: a raise takes effect on the first read
/// after its moment passes, so nothing depends on a job having run.
function effectiveLimits(
  row: LimitRow | null | undefined,
  nowMs: number,
): EffectiveLimits {
  const r = row ?? {};

  let dailyCents = r.daily_send_limit_cents ?? DEFAULT_DAILY_LIMIT_CENTS;
  let pendingDaily: PendingLimit | null = null;
  if (r.pending_daily_effective_at != null &&
      r.pending_daily_send_limit_cents != null) {
    if (due(r.pending_daily_effective_at, nowMs)) {
      dailyCents = r.pending_daily_send_limit_cents;
    } else {
      pendingDaily = {
        cents: r.pending_daily_send_limit_cents,
        at: r.pending_daily_effective_at,
      };
    }
  }

  let maxSendCents = r.max_send_cents ?? NO_CAP;
  let pendingMax: PendingLimit | null = null;
  if (r.pending_max_effective_at != null && r.pending_max_send_cents != null) {
    if (due(r.pending_max_effective_at, nowMs)) {
      maxSendCents = r.pending_max_send_cents;
    } else {
      pendingMax = {
        cents: r.pending_max_send_cents,
        at: r.pending_max_effective_at,
      };
    }
  }

  return { dailyCents, maxSendCents, pendingDaily, pendingMax };
}

interface LimitRequest {
  dailySendLimitCents?: number;
  maxSendCents?: number;
}

/// The columns to write for a requested change.
///
/// A tightening lands in the live column and clears any raise still waiting —
/// so asking for the number you already have is how you call off a raise you
/// changed your mind about. A loosening lands in the pending column with the
/// moment it starts counting.
function limitPatch(
  row: LimitRow | null | undefined,
  req: LimitRequest,
  nowMs: number,
): Record<string, unknown> {
  const now = effectiveLimits(row, nowMs);
  const patch: Record<string, unknown> = {};
  const effectiveAt = new Date(nowMs + RAISE_DELAY_MS).toISOString();

  if (asked(req.dailySendLimitCents)) {
    const next = clamp(req.dailySendLimitCents, MAX_DAILY_LIMIT_CENTS);
    if (rank(next) > rank(now.dailyCents)) {
      // Asking again for the raise already waiting must not restart its clock,
      // or a second tap costs another day and looks like nothing happened.
      if (now.pendingDaily?.cents !== next) {
        patch.pending_daily_send_limit_cents = next;
        patch.pending_daily_effective_at = effectiveAt;
      }
    } else {
      patch.daily_send_limit_cents = next;
      patch.pending_daily_send_limit_cents = null;
      patch.pending_daily_effective_at = null;
    }
  }

  if (asked(req.maxSendCents)) {
    const next = clamp(req.maxSendCents, MAX_PER_SEND_CENTS);
    if (rank(next) > rank(now.maxSendCents)) {
      if (now.pendingMax?.cents !== next) {
        patch.pending_max_send_cents = next;
        patch.pending_max_effective_at = effectiveAt;
      }
    } else {
      patch.max_send_cents = next;
      patch.pending_max_send_cents = null;
      patch.pending_max_effective_at = null;
    }
  }

  return patch;
}

/// Why a transfer is being refused, or null if nothing here refuses it.
///
/// `spentCents` is what has already left in the rolling window; the caller sums
/// it, because only the caller knows which rows counted.
function refusalFor(
  limits: EffectiveLimits,
  amountCents: number,
  spentCents: number,
): { error: string; limitCents: number; spentCents?: number } | null {
  if (limits.maxSendCents > NO_CAP && amountCents > limits.maxSendCents) {
    return { error: "over_send_limit", limitCents: limits.maxSendCents };
  }
  if (limits.dailyCents > NO_CAP &&
      spentCents + amountCents > limits.dailyCents) {
    return {
      error: "daily_limit_reached",
      limitCents: limits.dailyCents,
      spentCents,
    };
  }
  return null;
}

// Creates a PaymentIntent that routes money straight to the RECEIVER's Stripe
// connected account (destination charge), taking the platform's application fee
// — the platform never touches the funds. The client confirms this natively
// with the Stripe Payment Sheet (card / Apple Pay / Google Pay), no redirect to
// Stripe Checkout.
//
// POST { toPhone, amountCents, currency?, note? }
//   -> { clientSecret, paymentIntentId, amountCents, feeCents, currency }


Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const fromPhone = await callerPhone(req);
  if (!fromPhone) return json({ error: "unauthorized" }, 401);

  let body: {
    toPhone?: string;
    amountCents?: number;
    currency?: string;
    note?: string;
    receiptEmail?: string;
    // The sender ticked the box saying they understand the transfer is
    // final. Recorded as dispute evidence, not as a gate.
    acknowledged?: boolean;
  };
  try {
    body = await req.json();
  } catch {
    return json({ error: "invalid body" }, 400);
  }

  // Banned senders cannot start a charge. A chargeback ends the ability to
  // send, and the check belongs here rather than in the app — a client-side
  // ban is a suggestion.
  const { data: ban } = await admin
    .from("payment_bans")
    .select("reason")
    .eq("phone", fromPhone)
    .maybeSingle();
  if (ban) return json({ error: "sender_banned" }, 403);

  // Sending money requires a checked identity. The phone is already verified —
  // callerPhone comes from a Supabase session whose JWT carries an SMS-verified
  // number — so this is the other half.
  const { data: identity } = await admin
    .from("identity_verifications")
    .select("status, verified_name")
    .eq("phone", fromPhone)
    .maybeSingle();
  if (identity?.status !== "verified") {
    return json({ error: "identity_required" }, 403);
  }
  // Without a name there is nothing to check the card against, and the card
  // check is not optional.
  if (!identity.verified_name) {
    return json({ error: "identity_required" }, 403);
  }

  const toPhone = (body.toPhone ?? "").replace(/\D/g, "");
  const amountCents = Math.round(Number(body.amountCents ?? 0));
  const currency = (body.currency ?? "cad").toLowerCase();
  if (!toPhone || amountCents <= 0) return json({ error: "invalid amount" }, 400);
  if (toPhone === fromPhone) return json({ error: "cannot pay yourself" }, 400);

  // The receiver must have an onboarded, payout-enabled connected account.
  const { data: dest } = await admin
    .from("payment_accounts")
    .select("stripe_account_id, charges_enabled, payouts_enabled")
    .eq("phone", toPhone)
    .maybeSingle();
  if (!dest?.stripe_account_id || !dest.charges_enabled) {
    return json({ error: "receiver_not_onboarded" }, 409);
  }

  // The recipient's own rules come first: they decide who may pay them, and
  // refusing a specific person outranks accepting everyone. A paused account
  // is not accepting either — the sender is told the same thing in both cases,
  // because which of the two it is isn't the sender's business.
  const { data: recipientSettings } = await admin
    .from("payment_settings")
    .select("accepts_from, paused")
    .eq("phone", toPhone)
    .maybeSingle();
  if (recipientSettings?.accepts_from === "nobody" ||
      recipientSettings?.paused === true) {
    return json({ error: "recipient_not_accepting" }, 403);
  }
  const { data: blocked } = await admin
    .from("payment_blocks")
    .select("blocked_phone")
    .eq("phone", toPhone)
    .eq("blocked_phone", fromPhone)
    .maybeSingle();
  if (blocked) return json({ error: "recipient_not_accepting" }, 403);

  // The sender's own limits. A per-transfer cap bounds one mistake; the
  // rolling-day cap bounds a bad afternoon and a phone in the wrong hands.
  // Neither is addressed by the per-transfer checks above.
  const { data: senderRow } = await admin
    .from("payment_settings")
    .select(
      "paused, daily_send_limit_cents, max_send_cents, " +
        "pending_daily_send_limit_cents, pending_daily_effective_at, " +
        "pending_max_send_cents, pending_max_effective_at",
    )
    .eq("phone", fromPhone)
    .maybeSingle();
  // Composed column list, so supabase-js infers no row shape; named here.
  const senderSettings =
    (senderRow ?? null) as (LimitRow & { paused?: boolean | null }) | null;
  if (senderSettings?.paused === true) {
    return json({ error: "payments_paused" }, 403);
  }
  const limits = effectiveLimits(senderSettings, Date.now());

  // The day is only summed when there is a day to fill.
  let spent = 0;
  if (limits.dailyCents > 0) {
    const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
    const { data: recent } = await admin
      .from("payment_transactions")
      .select("amount_cents, status")
      .eq("from_phone", fromPhone)
      .gte("updated_at", since);
    // Only money that actually moved (or is still moving) counts. A blocked
    // or failed charge never left the account and must not use up the day.
    spent = (recent ?? [])
      .filter((t: { status?: string }) =>
        !String(t.status ?? "").startsWith("blocked_") &&
        t.status !== "canceled" &&
        t.status !== "failed"
      )
      .reduce(
        (sum: number, t: { amount_cents?: number }) =>
          sum + (t.amount_cents ?? 0),
        0,
      );
  }
  // amountCents is what the RECIPIENT should receive. Both fees come out of
  // the transfer, so the sender is charged the grossed-up total — paying the
  // amount plus the fees, rather than the recipient absorbing them.
  //
  // The limits are checked against that total, not against the target: a limit
  // is about what leaves the sender's card, and `spent` is summed from the same
  // grossed-up figures the transaction rows store.
  const chargeCents = grossUp(amountCents);
  const refusal = refusalFor(limits, chargeCents, spent);
  if (refusal) return json(refusal, 403);

  try {
    const feeCents = applicationFee(chargeCents);
    // DIRECT charge, not a destination charge: the PaymentIntent is created
    // ON the recipient's connected account. The money goes straight there and
    // never lands in the platform's balance, so the platform is not in the
    // flow of funds and is not merchant of record.
    //
    // The consequences are the whole point of doing it this way:
    //   * the recipient's account pays Stripe's processing fee, so the
    //     platform's application fee is what it keeps, full stop;
    //   * chargebacks land on the recipient, not the platform — under a
    //     destination charge a dispute clawed money back out of a balance
    //     the platform had already paid away.
    const intent = await stripe.paymentIntents.create({
      amount: chargeCents,
      currency,
      // Enables cards + Apple/Google Pay in the native Payment Sheet.
      automatic_payment_methods: { enabled: true },
      application_fee_amount: feeCents,
      // Authorise now, capture only once the card has been judged. The
      // cardholder name and whether it is prepaid are not knowable until a
      // card is actually attached, so the alternative is checking after the
      // money has moved — which is not a check, it is a refund.
      capture_method: "manual",
      // A statement line the sender will recognise. "STRIPE* SOMETHING" is a
      // leading cause of friendly fraud: people dispute what they don't
      // recognise instead of asking about it.
      statement_descriptor_suffix:
        (Deno.env.get("STATEMENT_DESCRIPTOR") ?? "OKAYMSG").slice(0, 22),
      // Stripe emails a real receipt, which is the other half of the same
      // problem — a charge nobody has a record of is a charge worth
      // disputing.
      receipt_email: body.receiptEmail,
      metadata: {
        from_phone: fromPhone,
        to_phone: toPhone,
        note: body.note ?? "",
        // Evidence, gathered up front. A dispute is defended with what was
        // recorded at the time, so record it at the time: who sent what to
        // whom, and that they confirmed it was final.
        acknowledged_final: body.acknowledged === true ? "yes" : "no",
        acknowledged_at: new Date().toISOString(),
        // Carried on the intent so the capture gate can compare without
        // another round trip to our own database.
        verified_name: identity.verified_name,
      },
    }, { stripeAccount: dest.stripe_account_id });

    await admin.from("payment_transactions").upsert({
      id: intent.id,
      from_phone: fromPhone,
      to_phone: toPhone,
      amount_cents: chargeCents,
      fee_cents: feeCents,
      currency,
      status: intent.status,
      updated_at: new Date().toISOString(),
    });

    return json({
      clientSecret: intent.client_secret,
      paymentIntentId: intent.id,
      // What the sender is charged, and what the recipient is meant to get.
      amountCents: chargeCents,
      targetCents: amountCents,
      feeCents,
      currency,
      // A direct charge's client secret only means anything to the SDK when
      // it is told which connected account the intent lives on.
      stripeAccountId: dest.stripe_account_id,
    });
  } catch (e) {
    return json({ error: String((e as Error).message ?? e) }, 400);
  }
});
