// PASTE-READY, self-contained version of payments-status for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: payments-status
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/payments-status/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

import Stripe from "https://esm.sh/stripe@16.12.0?target=deno";

// The generic request plumbing lives in http.ts; re-exported so existing
// imports from this file keep working unchanged.

const stripe = new Stripe(Deno.env.get("STRIPE_SECRET_KEY") ?? "", {
  apiVersion: "2024-06-20",
  httpClient: Stripe.createFetchHttpClient(),
});

/// The platform's application fee for an [amountCents] charge, in cents.
///
/// This MUST exceed what Stripe charges the platform, or every transfer loses
/// money. On a destination charge the platform is the merchant of record, so
/// Stripe's processing fee (2.9% + 30¢ on standard CAD/USD cards) comes out of
/// the platform's balance while only `application_fee_amount` comes back in.
///
/// The defaults below (3.4% + 35¢) clear that with a thin margin:
///   $10 transfer → fee 69¢ in, Stripe takes 59¢ → +10¢
///   $50 transfer → fee $2.05 in, Stripe takes $1.75 → +30¢
/// Override via PLATFORM_FEE_PERCENT / PLATFORM_FEE_FIXED_CENTS, but keep them
/// above Stripe's own rate for your region or the platform pays the difference.
const STRIPE_PERCENT = 2.9;
const STRIPE_FIXED_CENTS = 30;

function applicationFee(amountCents: number): number {
  const pct = parseFloat(Deno.env.get("PLATFORM_FEE_PERCENT") ?? "3.4");
  const fixed = parseInt(Deno.env.get("PLATFORM_FEE_FIXED_CENTS") ?? "35", 10);
  const fee = Math.round((amountCents * pct) / 100) + fixed;
  // Never let a misconfigured env var make the platform eat Stripe's cut.
  const stripeCost =
    Math.round((amountCents * STRIPE_PERCENT) / 100) + STRIPE_FIXED_CENTS;
  return Math.max(fee, stripeCost + 1);
}

// Returns the caller's payment/KYC status and their connected-account balance
// (available + pending) plus the latest payout status, so the app can show a
// wallet with a "cash out" state. Balance is read live from Stripe; funds are
// never held by the platform.
//
// POST  ->  { onboarded, chargesEnabled, payoutsEnabled, available, pending,
//             currency, payout: { status, amount, arrivalDate } | null }


Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const phone = await callerPhone(req);
  if (!phone) return json({ error: "unauthorized" }, 401);

  const { data: acct } = await admin
    .from("payment_accounts")
    .select("stripe_account_id")
    .eq("phone", phone)
    .maybeSingle();

  if (!acct?.stripe_account_id) {
    return json({ onboarded: false, chargesEnabled: false, payoutsEnabled: false });
  }
  const accountId = acct.stripe_account_id as string;

  try {
    const account = await stripe.accounts.retrieve(accountId);
    const balance = await stripe.balance.retrieve({ stripeAccount: accountId });

    const sum = (arr: { amount: number }[]) =>
      arr.reduce((n, b) => n + b.amount, 0);
    const currency = balance.available[0]?.currency ?? "cad";

    // Keep our cached KYC flags fresh.
    await admin.from("payment_accounts").update({
      charges_enabled: account.charges_enabled,
      payouts_enabled: account.payouts_enabled,
      details_submitted: account.details_submitted,
      updated_at: new Date().toISOString(),
    }).eq("phone", phone);

    const { data: payout } = await admin
      .from("payout_status")
      .select("status, amount_cents, arrival_date")
      .eq("stripe_account_id", accountId)
      .maybeSingle();

    return json({
      onboarded: account.details_submitted,
      chargesEnabled: account.charges_enabled,
      payoutsEnabled: account.payouts_enabled,
      available: sum(balance.available),
      pending: sum(balance.pending),
      currency,
      payout: payout
        ? {
          status: payout.status,
          amount: payout.amount_cents,
          arrivalDate: payout.arrival_date,
        }
        : null,
    });
  } catch (e) {
    return json({ error: String((e as Error).message ?? e) }, 400);
  }
});
