// PASTE-READY, self-contained version of payments-webhook for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: payments-webhook
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/payments-webhook/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

import Stripe from "https://esm.sh/stripe@16.12.0?target=deno";

// The generic request plumbing lives in http.ts; re-exported so existing
// imports from this file keep working unchanged.

const stripe = new Stripe(Deno.env.get("STRIPE_SECRET_KEY") ?? "", {
  apiVersion: "2024-06-20",
  httpClient: Stripe.createFetchHttpClient(),
});

/// The platform's application fee for an [amountCents] charge, in cents.
///
/// Transfers are DIRECT charges — the PaymentIntent is created on the
/// recipient's connected account — so the platform is never in the flow of
/// funds and never pays Stripe's processing fee. That makes this fee pure
/// revenue, and means no floor is needed: unlike a destination charge, there
/// is no platform-side cost for it to fail to clear.
///
/// Stripe's cut (2.9% + 30c domestic, more on a foreign card) comes out of the
/// recipient's account instead, which is why the send sheet quotes an
/// approximate landing amount rather than the amount typed.
function applicationFee(amountCents: number): number {
  const pct = parseFloat(Deno.env.get("PLATFORM_FEE_PERCENT") ?? "3.4");
  const fixed = parseInt(Deno.env.get("PLATFORM_FEE_FIXED_CENTS") ?? "10", 10);
  return Math.max(0, Math.round((amountCents * pct) / 100) + fixed);
}

// Deciding whether a card may be used to send money.
//
// Two rules, both of which have to hold before a charge is captured:
//
//   1. The card is not prepaid. A prepaid card is bought with cash and tied
//      to nobody, which is the whole appeal for someone moving money they
//      shouldn't be.
//   2. The cardholder name matches the name Stripe read off the sender's
//      government ID. Someone else's card is not yours to send from.
//
// Both are checked against the *authorised* payment method, before capture,
// so a card that fails is never actually charged.

/// Strips case, accents and punctuation so "O'BRIEN-Smith" and "obrien smith"
/// compare equal.
///
/// Apostrophes are deleted rather than turned into spaces: they never
/// separate one name from another, and splitting "O'Brien" into "o" and
/// "brien" would stop it matching a card printed "OBRIEN". Hyphens do
/// separate, so they become spaces.
function normalizeName(name: string): string {
  return name
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/['’ʼ]/g, "")
    .replace(/[^a-z\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/// Whether [cardName] plausibly belongs to the person whose ID says
/// [verifiedName].
///
/// Deliberately lenient in one direction and strict in the other. Cards carry
/// abbreviated and reordered names — "SMITH/ROBERT J", "Rob Smith", "Robert
/// John Smith" — and rejecting a legitimate sender is a worse failure here
/// than accepting a nickname. So: every surname-ish token of the ID name must
/// appear, and the first name must match or be a prefix of it. A different
/// person's name shares neither.
function nameMatches(cardName: string, verifiedName: string): boolean {
  const card = normalizeName(cardName);
  const id = normalizeName(verifiedName);
  if (card.length === 0 || id.length === 0) return false;
  if (card === id) return true;

  const cardParts = card.split(" ").filter((p) => p.length > 1);
  const idParts = id.split(" ").filter((p) => p.length > 1);
  if (cardParts.length === 0 || idParts.length === 0) return false;

  // The last token of the ID name is the one that must be present outright.
  const surname = idParts[idParts.length - 1];
  if (!cardParts.includes(surname)) return false;

  // And something on the card has to correspond to the given name, allowing
  // "Rob" for "Robert" but not "Alice" for "Robert".
  const given = idParts[0];
  return cardParts.some((p) =>
    p === given || given.startsWith(p) || p.startsWith(given)
  );
}

type CardVerdict =
  | { ok: true }
  | { ok: false; reason: "prepaid" | "name_mismatch" | "unknown_card" };

/// The full decision for one authorised card.
function judgeCard(
  card: { funding?: string | null } | null | undefined,
  billingName: string | null | undefined,
  verifiedName: string | null | undefined,
): CardVerdict {
  if (!card) return { ok: false, reason: "unknown_card" };
  if (card.funding === "prepaid") return { ok: false, reason: "prepaid" };
  // No verified name means the sender never passed the ID check, or Stripe
  // gave us no name to compare. Either way there is nothing to match against,
  // and "nothing to match" must fail closed.
  if (!verifiedName || !billingName) {
    return { ok: false, reason: "name_mismatch" };
  }
  return nameMatches(billingName, verifiedName)
    ? { ok: true }
    : { ok: false, reason: "name_mismatch" };
}

// Stripe webhook: keeps our payment metadata in sync with the source of truth.
// Handles payment success/failure, connected-account KYC updates, and payouts
// to the receiver's bank. Configure the endpoint in the Stripe Dashboard and
// set STRIPE_WEBHOOK_SECRET. Deploy with `--no-verify-jwt` (Stripe signs it).


const webhookSecret = Deno.env.get("STRIPE_WEBHOOK_SECRET") ?? "";

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const sig = req.headers.get("stripe-signature");
  const raw = await req.text();
  let event;
  try {
    event = await stripe.webhooks.constructEventAsync(raw, sig!, webhookSecret);
  } catch (e) {
    return new Response(`bad signature: ${(e as Error).message}`, { status: 400 });
  }

  try {
    switch (event.type) {
      case "payment_intent.succeeded":
      case "payment_intent.payment_failed":
      case "payment_intent.processing": {
        const pi = event.data.object as { id: string; status: string };
        await admin.from("payment_transactions").update({
          status: pi.status,
          updated_at: new Date().toISOString(),
        }).eq("id", pi.id);
        break;
      }
      // A chargeback on a peer-to-peer transfer is not a billing dispute with
      // a merchant: the money reached another person who has already been
      // paid, and clawing it back through the card network leaves them
      // carrying the loss. Filing one ends the sender's ability to send.
      //
      // It protects the platform too — Stripe closes accounts whose dispute
      // ratio climbs, and that ratio counts disputes whether they are won or
      // lost.
      // The card is authorised but not yet charged. This is the only moment
      // the cardholder name and funding type are knowable *before* money
      // moves, so both rules are enforced here: capture a card that passes,
      // cancel one that doesn't. A cancelled authorisation releases the hold
      // and the sender is never charged.
      case "payment_intent.amount_capturable_updated": {
        const pi = event.data.object as {
          id: string;
          payment_method?: string;
          metadata?: { verified_name?: string };
        };
        const account = event.account; // direct charges live on the recipient
        const opts = account ? { stripeAccount: account } : undefined;
        let verdict: CardVerdict = { ok: false, reason: "unknown_card" };
        try {
          const pm = pi.payment_method
            ? await stripe.paymentMethods.retrieve(pi.payment_method, opts)
            : null;
          verdict = judgeCard(
            pm?.card as { funding?: string | null } | null,
            pm?.billing_details?.name,
            pi.metadata?.verified_name,
          );
        } catch (_) {
          // Anything we can't inspect, we don't capture.
        }

        if (verdict.ok) {
          await stripe.paymentIntents.capture(pi.id, opts);
          await admin.from("payment_transactions").update({
            status: "succeeded",
            updated_at: new Date().toISOString(),
          }).eq("id", pi.id);
        } else {
          await stripe.paymentIntents.cancel(pi.id, opts);
          await admin.from("payment_transactions").update({
            status: `blocked_${verdict.reason}`,
            updated_at: new Date().toISOString(),
          }).eq("id", pi.id);
        }
        break;
      }
      case "charge.dispute.created": {
        const dispute = event.data.object as {
          id: string;
          charge: string;
          amount: number;
          payment_intent?: string;
        };
        const intentId = dispute.payment_intent;
        if (intentId) {
          const { data: tx } = await admin
            .from("payment_transactions")
            .select("from_phone")
            .eq("id", intentId)
            .maybeSingle();
          if (tx?.from_phone) {
            await admin.from("payment_bans").upsert({
              phone: tx.from_phone,
              reason: "chargeback",
              dispute_id: dispute.id,
              charge_id: dispute.charge,
              amount_cents: dispute.amount,
              banned_at: new Date().toISOString(),
            });
          }
          await admin.from("payment_transactions").update({
            status: "disputed",
            updated_at: new Date().toISOString(),
          }).eq("id", intentId);
        }
        break;
      }
      case "account.updated": {
        const acct = event.data.object as {
          id: string;
          charges_enabled: boolean;
          payouts_enabled: boolean;
          details_submitted: boolean;
        };
        await admin.from("payment_accounts").update({
          charges_enabled: acct.charges_enabled,
          payouts_enabled: acct.payouts_enabled,
          details_submitted: acct.details_submitted,
          updated_at: new Date().toISOString(),
        }).eq("stripe_account_id", acct.id);
        break;
      }
      // Identity — what actually earns the blue check. Verified is the only
      // status that grants it; everything else (requires_input, canceled,
      // processing) leaves or takes the badge away.
      case "identity.verification_session.verified":
      case "identity.verification_session.requires_input":
      case "identity.verification_session.canceled":
      case "identity.verification_session.processing": {
        const session = event.data.object as {
          id: string;
          status: string;
          metadata?: { phone?: string };
        };
        const phone = session.metadata?.phone;
        if (phone) {
          // On a pass, keep the legal name Stripe read off the document. It
          // is the only trustworthy thing to check a cardholder name against,
          // and verified_outputs has to be asked for explicitly.
          let verifiedName: string | null = null;
          if (session.status === "verified") {
            try {
              const full = await stripe.identity.verificationSessions.retrieve(
                session.id,
                { expand: ["verified_outputs"] },
              );
              const out = (full as { verified_outputs?: { name?: string } })
                .verified_outputs;
              verifiedName = out?.name ?? null;
            } catch (_) {
              // A missing name means the name check can't pass; it must never
              // mean the name check is skipped.
            }
          }
          await admin.from("identity_verifications").upsert({
            phone,
            session_id: session.id,
            status: session.status,
            ...(verifiedName ? { verified_name: verifiedName } : {}),
            updated_at: new Date().toISOString(),
          });
        }
        break;
      }
      case "payout.created":
      case "payout.paid":
      case "payout.failed":
      case "payout.canceled": {
        const payout = event.data.object as {
          status: string;
          amount: number;
          arrival_date: number;
        };
        const accountId = event.account; // connected account id
        if (accountId) {
          await admin.from("payout_status").upsert({
            stripe_account_id: accountId,
            status: payout.status,
            amount_cents: payout.amount,
            arrival_date: new Date(payout.arrival_date * 1000).toISOString(),
            updated_at: new Date().toISOString(),
          });
        }
        break;
      }
    }
    return new Response(JSON.stringify({ received: true }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (e) {
    return new Response(`handler error: ${(e as Error).message}`, { status: 500 });
  }
});
