// PASTE-READY, self-contained version of payments-connect-fields for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: payments-connect-fields
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/payments-connect-fields/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

// The debit-card rules, pure so they can be executed without Stripe.
//
// WHY THESE EXIST. The debit card is where instant payouts LAND — whoever
// controls it walks away with the balance. The classic account-takeover
// drains in one motion: sign in, attach your own card, cash out in minutes.
// Two rules close it, both enforced server-side because a client-side rule
// is a suggestion:
//
//   * A newly attached card waits SEVEN BUSINESS DAYS before instant
//     payouts may land on it — long enough for the real owner to notice a
//     takeover and act, which is the entire point of the delay. Standard
//     bank payouts are untouched: they go to the bank account, which an
//     attacker's card swap does not redirect.
//   * Attaching cards too often locks the feature: the third card inside
//     thirty days is not somebody correcting a typo. The lock releases on
//     its own as the changes age out of the window.

const CARD_HOLD_BUSINESS_DAYS = 7;
const CARD_CHANGE_WINDOW_DAYS = 30;
const CARD_CHANGE_LIMIT = 3;

/// Whole business days (Mon–Fri, UTC) elapsed from [from] to [to]. Partial
/// days do not count — "seven business days" must never round down to six
/// and a bit.
function businessDaysBetween(from: Date, to: Date): number {
  if (to.getTime() <= from.getTime()) return 0;
  let days = 0;
  const cursor = new Date(Date.UTC(
    from.getUTCFullYear(),
    from.getUTCMonth(),
    from.getUTCDate(),
  ));
  const end = new Date(Date.UTC(
    to.getUTCFullYear(),
    to.getUTCMonth(),
    to.getUTCDate(),
  ));
  while (cursor.getTime() < end.getTime()) {
    cursor.setUTCDate(cursor.getUTCDate() + 1);
    const dow = cursor.getUTCDay();
    if (dow !== 0 && dow !== 6) days++;
  }
  return days;
}

/// The verdict on this account's card, from its attach history.
///
/// [attachedAts] is every recorded attach, any order. An account with no
/// recorded attaches is neither held nor locked: cards added before this
/// policy existed have already had their waiting period in the world.
function cardPolicy(opts: { attachedAts: Date[]; now: Date }): {
  locked: boolean;
  held: boolean;
  businessDaysLeft: number;
} {
  const { attachedAts, now } = opts;
  const windowStart = now.getTime() -
    CARD_CHANGE_WINDOW_DAYS * 24 * 60 * 60 * 1000;
  const recent = attachedAts.filter((a) => a.getTime() > windowStart);
  const locked = recent.length >= CARD_CHANGE_LIMIT;
  if (attachedAts.length === 0) {
    return { locked, held: false, businessDaysLeft: 0 };
  }
  const latest = new Date(
    Math.max(...attachedAts.map((a) => a.getTime())),
  );
  const elapsed = businessDaysBetween(latest, now);
  const held = elapsed < CARD_HOLD_BUSINESS_DAYS;
  return {
    locked,
    held,
    businessDaysLeft: held ? CARD_HOLD_BUSINESS_DAYS - elapsed : 0,
  };
}

// Deciding whether a card may be used to send money.
//
// Two rules, both of which have to hold before a charge is captured:
//
//   1. The card is not prepaid. A prepaid card is bought with cash and tied
//      to nobody, which is the whole appeal for someone moving money they
//      shouldn't be.
//   2. The cardholder name matches the name Stripe read off the sender's
//      government ID. Someone else's card is not yours to send from.
//
// Both are checked against the *authorised* payment method, before capture,
// so a card that fails is never actually charged.

/// Strips case, accents and punctuation so "O'BRIEN-Smith" and "obrien smith"
/// compare equal.
///
/// Apostrophes are deleted rather than turned into spaces: they never
/// separate one name from another, and splitting "O'Brien" into "o" and
/// "brien" would stop it matching a card printed "OBRIEN". Hyphens do
/// separate, so they become spaces.
function normalizeName(name: string): string {
  return name
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/['’ʼ]/g, "")
    .replace(/[^a-z\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/// Whether [cardName] plausibly belongs to the person whose ID says
/// [verifiedName].
///
/// Deliberately lenient in one direction and strict in the other. Cards carry
/// abbreviated and reordered names — "SMITH/ROBERT J", "Rob Smith", "Robert
/// John Smith" — and rejecting a legitimate sender is a worse failure here
/// than accepting a nickname. So: every surname-ish token of the ID name must
/// appear, and the first name must match or be a prefix of it. A different
/// person's name shares neither.
function nameMatches(cardName: string, verifiedName: string): boolean {
  const card = normalizeName(cardName);
  const id = normalizeName(verifiedName);
  if (card.length === 0 || id.length === 0) return false;
  if (card === id) return true;

  const cardParts = card.split(" ").filter((p) => p.length > 1);
  const idParts = id.split(" ").filter((p) => p.length > 1);
  if (cardParts.length === 0 || idParts.length === 0) return false;

  // The last token of the ID name is the one that must be present outright.
  const surname = idParts[idParts.length - 1];
  if (!cardParts.includes(surname)) return false;

  // And something on the card has to correspond to the given name, allowing
  // "Rob" for "Robert" but not "Alice" for "Robert".
  const given = idParts[0];
  return cardParts.some((p) =>
    p === given || given.startsWith(p) || p.startsWith(given)
  );
}

/// The `reason?: undefined` on the passing arm is deliberate. Without it,
/// reading `verdict.reason` requires TypeScript to have narrowed the union
/// first, and the Supabase dashboard editor's type worker does not narrow
/// across the try/catch these verdicts are produced in — it reports
/// "Property 'reason' does not exist on type '{ ok: true }'" over code that
/// both `deno check` and strict `tsc` accept. Declaring the property as
/// always-present-but-undefined makes the access legal unnarrowed while
/// still refusing `{ ok: true, reason: … }`, so nothing is given up.
type CardVerdict =
  | { ok: true; reason?: undefined }
  | { ok: false; reason: "prepaid" | "name_mismatch" | "unknown_card" };

/// The full decision for one authorised card.
function judgeCard(
  card: { funding?: string | null } | null | undefined,
  billingName: string | null | undefined,
  verifiedName: string | null | undefined,
): CardVerdict {
  if (!card) return { ok: false, reason: "unknown_card" };
  if (card.funding === "prepaid") return { ok: false, reason: "prepaid" };
  // No verified name means the sender never passed the ID check, or Stripe
  // gave us no name to compare. Either way there is nothing to match against,
  // and "nothing to match" must fail closed.
  if (!verifiedName || !billingName) {
    return { ok: false, reason: "name_mismatch" };
  }
  return nameMatches(billingName, verifiedName)
    ? { ok: true }
    : { ok: false, reason: "name_mismatch" };
}

import Stripe from "https://esm.sh/stripe@16.12.0?target=denonext";

// The generic request plumbing lives in http.ts; re-exported so existing
// imports from this file keep working unchanged.

const stripe = new Stripe(Deno.env.get("STRIPE_SECRET_KEY") ?? "", {
  apiVersion: "2024-06-20",
  httpClient: Stripe.createFetchHttpClient(),
});

/// The platform's application fee for an [amountCents] charge, in cents.
///
/// Transfers are DIRECT charges — the PaymentIntent is created on the
/// recipient's connected account — so the platform is never in the flow of
/// funds and never pays Stripe's processing fee. That makes this fee pure
/// revenue, and means no floor is needed: unlike a destination charge, there
/// is no platform-side cost for it to fail to clear.
///
/// Stripe's cut (2.9% + 30c domestic, more on a foreign card) comes out of the
/// recipient's account instead, which is why the send sheet quotes an
/// approximate landing amount rather than the amount typed.
function applicationFee(amountCents: number): number {
  const pct = parseFloat(Deno.env.get("PLATFORM_FEE_PERCENT") ?? "3.4");
  const fixed = parseInt(Deno.env.get("PLATFORM_FEE_FIXED_CENTS") ?? "10", 10);
  return Math.max(0, Math.round((amountCents * pct) / 100) + fixed);
}

/// Stripe's published card rates, mirroring StorageEconomics in
/// lib/payments/storage_economics.dart — the Dart side is the documented
/// source of these numbers and the test suite holds it to them.
///
/// Not read from the environment on purpose: these are Stripe's prices, not
/// ours. A deployment cannot negotiate them, and an env var would only offer
/// a way to gross up against a rate Stripe isn't charging.
const STRIPE_PERCENT = 2.9;
const STRIPE_FIXED_CENTS = 30;

/// Stripe's extra cut on a card issued abroad. The card's country is only
/// known after the charge, so grossing up has to assume it.
const STRIPE_INTERNATIONAL_SURCHARGE_PERCENT = 1.5;

/// Stripe's own cost for a charge of [amountCents] on a domestic card. Paid by
/// the recipient's account on a direct charge, which is why it has to be
/// accounted for when grossing up.
function stripeCost(amountCents: number): number {
  return Math.round((amountCents * STRIPE_PERCENT) / 100) + STRIPE_FIXED_CENTS;
}

/// What the sender must be charged so [targetCents] actually reaches the
/// recipient.
///
/// Both fees come out of the transfer, so charging exactly what was typed
/// delivers less than that. Grossing up moves the fees onto the sender, which
/// is what people expect when they type a number.
///
/// Solved by search rather than algebra: the fees round to whole cents, so a
/// closed form lands a cent out either way. Mirrors grossUpCents() in
/// lib/payments/storage_economics.dart.
function grossUp(targetCents: number): number {
  if (targetCents <= 0) return 0;
  const pct = parseFloat(Deno.env.get("PLATFORM_FEE_PERCENT") ?? "3.4");
  const fixed = parseInt(Deno.env.get("PLATFORM_FEE_FIXED_CENTS") ?? "10", 10);
  // Grossed up against the WORST-case Stripe rate. The sender picks the card
  // and its country is only known afterwards, so budgeting on the domestic
  // rate would under-deliver every international transfer — the recipient
  // would get less than the sender typed, which is the one promise this
  // makes. Erring the other way costs a domestic sender a few cents and the
  // surplus goes to the recipient, never to the platform.
  const worst = STRIPE_PERCENT + STRIPE_INTERNATIONAL_SURCHARGE_PERCENT;
  const worstCost = (t: number) =>
    Math.round((t * worst) / 100) + STRIPE_FIXED_CENTS;
  const rate = 1 - (pct + worst) / 100;
  let total = Math.floor((targetCents + fixed + STRIPE_FIXED_CENTS) / rate);
  for (let i = 0; i < 12; i++) {
    if (total - worstCost(total) - applicationFee(total) >= targetCents) {
      return total;
    }
    total++;
  }
  return total;
}

// Native Connect onboarding: what Stripe still needs, and taking it.
//
// WHY THIS EXISTS. Setting up payments used to mean one of Stripe's own web
// pages — the hosted flow or the embedded component — because the accounts were
// created as `express`, and Stripe does not let a platform collect an Express
// account's KYC over the API. That is not a limitation anybody can code around:
// it is the account type. So payments could never be integrated the way the rest
// of this app is, and the setup screen always looked like somebody else's page.
//
// Accounts are created here with `controller.requirement_collection:
// "application"`, which means THIS application collects the requirements. Then
// the fields can be asked for in the app's own forms and submitted over the
// API — no hosted page, no iframe, no browser.
//
// WHAT THAT COSTS, PLAINLY: with requirement collection on the application, the
// platform also takes `losses.payments: "application"` — disputes and negative
// balances land on the platform, not on Stripe. That is the trade for native
// onboarding and it is a business decision, not a technical one.
//
// WHAT NEVER REACHES THIS FUNCTION: bank account numbers and government ID
// numbers. The app tokenises those against Stripe directly with the publishable
// key, and sends only the resulting `btok_…` / `piitok_…`. So the one server in
// this system never sees them, which is the same rule the rest of the app
// follows.
//
// POST {}                    -> { accountId, collection, currentlyDue, pastDue,
//                                 errors, status, country, currency }
// POST { submit: {...} }      -> the same, after applying the submission
// POST { replaceAccount: true } -> abandons an account Stripe will only onboard
//                                 on its own pages, and makes one this app can
//                                 collect for. Asked for explicitly.


/// Whether a connected account is an Express leftover worth throwing away.
///
/// An Express account can only be onboarded on Stripe's own pages, so keeping
/// one means the app has to send somebody out to a web form — the exact seam
/// this function exists to remove. But an Express account that has been *used*
/// is somebody's real payment account, with a history and possibly a balance,
/// and abandoning it would be destroying something.
///
/// So: replace it only when it holds nothing. Nothing submitted, no charges, no
/// payouts — an account that was created, never finished, and is worth exactly
/// zero. Anything else is kept and the hosted flow is offered for it honestly.
export function isDiscardableExpressAccount(account: {
  controller?: { requirement_collection?: string } | null;
  details_submitted?: boolean | null;
  charges_enabled?: boolean | null;
  payouts_enabled?: boolean | null;
}): boolean {
  const collectedByStripe =
    (account.controller?.requirement_collection ?? "stripe") !== "application";
  return collectedByStripe &&
    !account.details_submitted &&
    !account.charges_enabled &&
    !account.payouts_enabled;
}

type Submission = {
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  dob?: { day: number; month: number; year: number };
  address?: {
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  };
  // Tokens minted on the device with the publishable key. Raw numbers must
  // never appear here; the checks below refuse them if they do.
  idNumberToken?: string;
  ssnLast4?: string;
  /// What this person is to the account — Stripe's individual.relationship.title.
  title?: string;
  bankToken?: string;
  // A card token for instant payouts, tokenised on the device like the bank
  // account — the card number itself must never reach this function.
  cardToken?: string;
  // Ids of files already uploaded to Stripe FROM THE DEVICE. The photo of
  // somebody's licence never passes through here either.
  documentFrontFileId?: string;
  documentBackFileId?: string;
  productDescription?: string;
  mcc?: string;
  // The business website. Optional from the client: an individual receiving
  // money from friends has none, so when a description arrives without one,
  // the platform's own page stands in below.
  url?: string;
  acceptedTos?: boolean;
};

// NOTE: this deliberately does NOT report which requirements the app can
// collect. That knowledge belongs to the app's form, and keeping a second copy
// here meant the two drifted the moment one was deployed without the other —
// the form grew a field and this kept calling it missing.
function describe(account: Record<string, unknown>) {
  const req = (account.requirements ?? {}) as Record<string, unknown>;
  const currentlyDue = (req.currently_due ?? []) as string[];
  const pastDue = (req.past_due ?? []) as string[];
  const errors = ((req.errors ?? []) as { requirement: string; reason: string }[])
    .map((e) => ({ requirement: e.requirement, reason: e.reason }));
  const controller = (account.controller ?? {}) as Record<string, unknown>;
  return {
    accountId: account.id,
    // 'application' means the fields can be collected in the app. 'stripe'
    // means this is an older Express account and only Stripe's own pages can
    // onboard it — the client then uses the hosted flow, honestly, rather than
    // presenting a form that cannot work.
    collection: controller.requirement_collection ?? "stripe",
    currentlyDue,
    pastDue,
    errors,
    country: account.country,
    currency: (account.default_currency ?? "").toString(),
    status: {
      chargesEnabled: account.charges_enabled,
      payoutsEnabled: account.payouts_enabled,
      detailsSubmitted: account.details_submitted,
      disabledReason: ((account.requirements ?? {}) as Record<string, unknown>)
        .disabled_reason ?? null,
    },
  };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const phone = await callerPhone(req);
  if (!phone) return json({ error: "unauthorized" }, 401);

  let body: { submit?: Submission; replaceAccount?: boolean } = {};
  try {
    body = await req.json();
  } catch (_) {
    // An empty body is the "just tell me what is needed" call.
  }

  try {
    const { data: existing } = await admin
      .from("payment_accounts")
      .select("stripe_account_id")
      .eq("phone", phone)
      .maybeSingle();

    let accountId = existing?.stripe_account_id as string | undefined;

    // A stored id from the other key mode is real but invisible under this key;
    // Stripe answers "No such account". Forget it and make one that belongs
    // here. Only on resource_missing — a network blip must not discard an
    // account somebody has already put their details into.
    // An unused Express account is the last thing standing between somebody
    // and setting payments up without leaving the app, so it goes.
    let replacedStaleAccount = false;

    // Asked for by name, from the screen that would otherwise be a dead end:
    // an account Stripe will only onboard on its own pages, and somebody who
    // wants it done in the app. The account is abandoned, not deleted — it stays
    // in the Stripe dashboard — and a fresh one takes its place.
    //
    // Refused for an account that can actually move money. Payouts enabled means
    // a real, working payment account, and swapping that out from under somebody
    // could strand a payout in flight. Everything short of that is a half-made
    // account worth nothing.
    if (body.replaceAccount && accountId) {
      const current = await stripe.accounts.retrieve(accountId);
      if ((current.controller?.requirement_collection ?? "stripe") ===
          "application") {
        // Already collectable here; nothing to replace.
      } else if (current.payouts_enabled) {
        return json({
          error: "account_in_use: this payment account can already receive " +
            "payouts, so it is not replaced. Finish on Stripe's page, or " +
            "remove the account in the Stripe dashboard first.",
        }, 400);
      } else {
        await admin.from("payment_accounts").delete().eq("phone", phone);
        accountId = undefined;
        replacedStaleAccount = true;
      }
    }

    if (accountId) {
      try {
        const stored = await stripe.accounts.retrieve(accountId);
        if (isDiscardableExpressAccount(
          stored as unknown as Parameters<typeof isDiscardableExpressAccount>[0],
        )) {
          await admin.from("payment_accounts").delete().eq("phone", phone);
          accountId = undefined;
          replacedStaleAccount = true;
        }
      } catch (e) {
        const err = e as { code?: string; statusCode?: number };
        if (err?.code === "resource_missing" || err?.statusCode === 404) {
          await admin.from("payment_accounts").delete().eq("phone", phone);
          accountId = undefined;
        } else {
          throw e;
        }
      }
    }

    if (!accountId) {
      const created = await stripe.accounts.create({
        country: Deno.env.get("CONNECT_COUNTRY") ?? "CA",
        business_type: "individual",
        controller: {
          // This application collects the requirements, which is what makes a
          // native form legal to use at all.
          requirement_collection: "application",
          fees: { payer: "application" },
          losses: { payments: "application" },
          // No Stripe-hosted dashboard for the recipient: everything they need
          // is in this app.
          stripe_dashboard: { type: "none" },
        },
        capabilities: {
          card_payments: { requested: true },
          transfers: { requested: true },
        },
        metadata: { phone },
      });
      accountId = created.id;
      await admin.from("payment_accounts").upsert({
        phone,
        stripe_account_id: accountId,
        updated_at: new Date().toISOString(),
      });
    }

    const submit = body.submit;
    if (submit) {
      // Refuse raw secrets outright rather than forwarding them. If a future
      // client ever sends an account number here by mistake, this is the line
      // that stops it reaching Stripe's logs through our server.
      if (submit.cardToken && !submit.cardToken.startsWith("tok_")) {
        return json({
          error: "card_must_be_tokenised: send a tok_ from the device",
        }, 400);
      }
      if (submit.bankToken && !submit.bankToken.startsWith("btok_")) {
        return json({
          error: "bank_details_must_be_tokenised: send a btok_ from the device, " +
            "never an account number",
        }, 400);
      }
      if (submit.idNumberToken && !submit.idNumberToken.startsWith("piitok_")) {
        return json({
          error: "id_number_must_be_tokenised: send a piitok_ from the device",
        }, 400);
      }
      for (
        const id of [submit.documentFrontFileId, submit.documentBackFileId]
      ) {
        if (id && !id.startsWith("file_")) {
          return json({
            error: "document_must_be_uploaded_from_the_device: send a file_ id, " +
              "never image bytes",
          }, 400);
        }
      }

      const individual: Record<string, unknown> = {};
      if (submit.firstName) individual.first_name = submit.firstName;
      if (submit.lastName) individual.last_name = submit.lastName;
      if (submit.email) individual.email = submit.email;
      if (submit.phone) individual.phone = submit.phone;
      if (submit.dob) individual.dob = submit.dob;
      if (submit.title) individual.relationship = { title: submit.title };
      if (submit.idNumberToken) individual.id_number = submit.idNumberToken;
      if (submit.ssnLast4) individual.ssn_last_4 = submit.ssnLast4;
      if (submit.address) {
        const a = submit.address;
        individual.address = {
          ...(a.line1 ? { line1: a.line1 } : {}),
          ...(a.line2 ? { line2: a.line2 } : {}),
          ...(a.city ? { city: a.city } : {}),
          ...(a.state ? { state: a.state } : {}),
          ...(a.postalCode ? { postal_code: a.postalCode } : {}),
          ...(a.country ? { country: a.country } : {}),
        };
      }

      if (submit.documentFrontFileId || submit.documentBackFileId) {
        individual.verification = {
          document: {
            ...(submit.documentFrontFileId
              ? { front: submit.documentFrontFileId }
              : {}),
            ...(submit.documentBackFileId
              ? { back: submit.documentBackFileId }
              : {}),
          },
        };
      }

      const update: Record<string, unknown> = {};
      if (Object.keys(individual).length) update.individual = individual;
      if (submit.productDescription || submit.mcc || submit.url) {
        // Stripe also requires business_profile.url, and on real accounts a
        // product description does not reliably stand in for it — the
        // requirement came straight back and the form looped on "What the
        // money is for". A person receiving money from friends has no
        // website, so the platform's page is the truthful answer: SITE_URL
        // when configured, else this project's own landing page.
        const defaultUrl = Deno.env.get("SITE_URL") ??
          `${Deno.env.get("SUPABASE_URL") ?? ""}/functions/v1/pages`;
        update.business_profile = {
          ...(submit.mcc ? { mcc: submit.mcc } : {}),
          ...(submit.productDescription
            ? { product_description: submit.productDescription }
            : {}),
          ...(submit.url
            ? { url: submit.url }
            : (submit.productDescription && defaultUrl.startsWith("http")
              ? { url: defaultUrl }
              : {})),
        };
      }
      if (submit.acceptedTos) {
        // Stripe requires the moment and the IP of the acceptance. Both come
        // from here rather than from the client: a client-supplied IP is not
        // evidence of anything.
        update.tos_acceptance = {
          date: Math.floor(Date.now() / 1000),
          ip: req.headers.get("x-forwarded-for")?.split(",")[0].trim() ??
            req.headers.get("cf-connecting-ip") ?? "0.0.0.0",
        };
      }
      if (Object.keys(update).length) {
        await stripe.accounts.update(accountId, update);
      }
      // The bank account goes on separately: it is an external account, not a
      // field of the person. A FIRST bank account is onboarding and attaches
      // plainly; REPLACING one is the other half of the account-takeover
      // drain — redirect where the money lands, wait for the schedule — so a
      // change pauses automatic payouts and starts the seven-business-day
      // hold that payments-payout and payments-status enforce and explain.
      if (submit.bankToken) {
        const existing = await stripe.accounts.retrieve(accountId);
        const oldBanks =
          ((existing.external_accounts?.data ?? []) as {
            object?: string;
            id: string;
          }[]).filter((e) => e.object === "bank_account");
        const isChange = oldBanks.length > 0;
        if (isChange) {
          const { data: bankEvents } = await admin
            .from("payment_card_events")
            .select("created_at")
            .eq("phone", phone)
            .eq("kind", "bank")
            .order("created_at", { ascending: false })
            .limit(12);
          const policy = cardPolicy({
            attachedAts: (bankEvents ?? []).map((e) =>
              new Date((e as { created_at: string }).created_at)
            ),
            now: new Date(),
          });
          if (policy.locked) {
            return json({ error: "bank_changes_locked" }, 429);
          }
        }
        await stripe.accounts.createExternalAccount(accountId, {
          external_account: submit.bankToken,
          ...(isChange ? { default_for_currency: true } : {}),
        });
        if (isChange) {
          // No money leaves on the schedule while the hold runs; the status
          // and payout functions restore the schedule once it has passed.
          await stripe.accounts.update(accountId, {
            settings: { payouts: { schedule: { interval: "manual" } } },
          });
          await admin.from("payment_card_events").insert({
            phone,
            kind: "bank",
          });
          // One destination: the replaced accounts go, so a payout cannot
          // quietly land somewhere somebody forgot was still attached.
          for (const b of oldBanks) {
            try {
              await stripe.accounts.deleteExternalAccount(accountId, b.id);
            } catch (_) {
              // Stripe refuses to delete in some states; harmless — the new
              // account is the default either way.
            }
          }
        }
      }
      // A debit card rides the same door: it is an external account too,
      // the one instant payouts land on. Attaching consults the change
      // policy first and RECORDS the attach — the seven-business-day hold
      // in payments-payout is only as real as this row.
      if (submit.cardToken) {
        const { data: events } = await admin
          .from("payment_card_events")
          .select("created_at")
          .eq("phone", phone)
          .eq("kind", "card")
          .order("created_at", { ascending: false })
          .limit(12);
        const policy = cardPolicy({
          attachedAts: (events ?? []).map((e) =>
            new Date((e as { created_at: string }).created_at)
          ),
          now: new Date(),
        });
        if (policy.locked) {
          return json({ error: "card_changes_locked" }, 429);
        }
        // The name on the card has to match the name on the account — the
        // one Stripe read off the government ID. Judged BEFORE attaching,
        // with the same rules the sending card is judged by (lenient about
        // "ROB SMITH" for "Robert Smith", closed to anybody else), and the
        // prepaid refusal comes along: a prepaid card is tied to nobody,
        // which is the whole appeal for draining a balance onto one.
        const { data: identity } = await admin
          .from("identity_verifications")
          .select("status, verified_name")
          .eq("phone", phone)
          .maybeSingle();
        if (identity?.status !== "verified" || !identity.verified_name) {
          return json({ error: "identity_required" }, 403);
        }
        const tok = await stripe.tokens.retrieve(submit.cardToken);
        const tokCard = (tok as {
          card?: { name?: string | null; funding?: string | null };
        }).card;
        const verdict = judgeCard(
          tokCard,
          tokCard?.name,
          identity.verified_name as string,
        );
        if (!verdict.ok) {
          return json({
            error: verdict.reason === "prepaid"
              ? "card_prepaid"
              : "card_name_mismatch",
          }, 403);
        }
        await stripe.accounts.createExternalAccount(accountId, {
          external_account: submit.cardToken,
        });
        await admin.from("payment_card_events").insert({
          phone,
          kind: "card",
        });
      }
    }

    const account = await stripe.accounts.retrieve(accountId);
    const out = {
      ...describe(account as unknown as Record<string, unknown>),
      // True when an unused Express account was thrown away for this one. Not
      // an error — but the app should not pretend nothing happened either.
      replacedStaleAccount,
    };
    await admin.from("payment_accounts").update({
      charges_enabled: account.charges_enabled,
      payouts_enabled: account.payouts_enabled,
      details_submitted: account.details_submitted,
      updated_at: new Date().toISOString(),
    }).eq("phone", phone);
    return json(out);
  } catch (e) {
    const err = e as { message?: string; param?: string; code?: string };
    return json({
      error: String(err.message ?? e),
      param: err.param ?? null,
      code: err.code ?? null,
    }, 400);
  }
});
