// PASTE-READY, self-contained version of pricing-set for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: pricing-set
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/pricing-set/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

// Owner-editable pricing — the owner's console for keeping the prices the APP
// assumes in step with App Store Connect, without shipping a build.
//
// POST { what: 'get' }
//   -> { prices }   (also served straight from the table via anon SELECT;
//      this verb exists for symmetry/debugging)
// POST { what: 'publish', prices } -> { ok: true }   OWNER ONLY.
//
// These numbers are NOT what anyone is charged: Apple charges what the SKU
// says, and the app shows StoreKit's own localized price whenever it has one.
// They fill in where there is no store price (web, payments-test mode, the
// frame before StoreKit answers) and set the tier ladder a creator picks
// from — so a bad value here cannot advertise a price different from the
// charge on a real purchase.
//
// OWNER ONLY for publish, checked HERE against platform_roles with a phone
// proven by JWT — the app's button decides nothing. Every value is clamped to
// a sane range, because a price is rendered straight into the UI.


// A price point has to fit a real store: no negative, no runaway.
const MAX_CENTS = 100000; // $1000.00
const MAX_TIPS = 24;
const MAX_TIP_ID = 120;
// The storage ladder tops out at 100 GB in 10 GB steps; the caps are slack
// enough for that to grow without another deploy.
const MAX_SIZES = 64;
const MAX_GB = 100000;

function cents(v: unknown, fallback: number): number {
  const n = Math.round(Number(v));
  if (!Number.isFinite(n) || n < 0 || n > MAX_CENTS) return fallback;
  return n;
}

// Sanitizes the incoming price map into exactly the shape the app reads.
function cleanPrices(raw: unknown): Record<string, unknown> {
  if (typeof raw !== "object" || raw === null) return {};
  const rec = raw as Record<string, unknown>;
  const out: Record<string, unknown> = {};

  if (rec.storagePerGbCents !== undefined) {
    // Per GB per month, in cents. 1..500 keeps it a storage price.
    const v = cents(rec.storagePerGbCents, 0);
    if (v > 0 && v <= 500) out.storagePerGbCents = v;
  }

  if (Array.isArray(rec.tierCents)) {
    // Exactly four levels, matching the four creatorsub/communitysub SKUs,
    // and increasing — a ladder that goes backwards is the App Store Connect
    // mistake this whole surface exists to keep out of the app.
    const t = rec.tierCents.slice(0, 4).map((v) => cents(v, 0));
    if (t.length === 4 && t.every((v) => v > 0)) {
      let rising = true;
      for (let i = 1; i < t.length; i++) if (t[i] <= t[i - 1]) rising = false;
      if (rising) out.tierCents = t;
    }
  }

  if (typeof rec.tipCents === "object" && rec.tipCents !== null) {
    const tips: Record<string, number> = {};
    let n = 0;
    for (const [k, v] of Object.entries(rec.tipCents as Record<string, unknown>)) {
      if (n++ >= MAX_TIPS) break;
      const id = String(k).slice(0, MAX_TIP_ID);
      const c = cents(v, 0);
      if (id && c > 0) tips[id] = c;
    }
    if (Object.keys(tips).length > 0) out.tipCents = tips;
  }

  if (typeof rec.storageCents === "object" && rec.storageCents !== null) {
    // One price per storage size, keyed by GB. This replaced a single per-GB
    // rate, which could not be made to match App Store Connect: one rate
    // fixes every size in relation to the others, so matching one size threw
    // the rest out.
    const sizes: Record<string, number> = {};
    const pairs: Array<[number, number]> = [];
    for (
      const [k, v] of Object.entries(rec.storageCents as Record<string, unknown>)
    ) {
      const gb = Math.round(Number(k));
      const c = cents(v, 0);
      if (!Number.isFinite(gb) || gb <= 0 || gb > MAX_GB || c <= 0) continue;
      if (pairs.length >= MAX_SIZES) break;
      pairs.push([gb, c]);
    }
    // Must rise with size, or a bigger plan would cost less — the App Store
    // Connect fault this surface exists to keep out of the app. Rejected
    // whole rather than half-applied, so the app falls back to the rate.
    pairs.sort((a, b) => a[0] - b[0]);
    let rising = true;
    for (let i = 1; i < pairs.length; i++) {
      if (pairs[i][1] <= pairs[i - 1][1]) rising = false;
    }
    if (pairs.length > 0 && rising) {
      for (const [gb, c] of pairs) sizes[String(gb)] = c;
      out.storageCents = sizes;
    }
  }

  return out;
}

async function roleOf(phone: string): Promise<string> {
  const { data } = await admin
    .from("platform_roles")
    .select("role")
    .eq("phone", phone)
    .maybeSingle();
  return (data?.role as string) ?? "member";
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return json({ error: "bad_request" }, 400);
  }
  const what = String(body.what ?? "");

  if (what === "get") {
    const { data } = await admin
      .from("app_pricing")
      .select("prices")
      .eq("id", 1)
      .maybeSingle();
    return json({ prices: data?.prices ?? {} });
  }

  if (what !== "publish") return json({ error: "bad_request" }, 400);

  const phone = await callerPhone(req);
  if (!phone) return json({ error: "unauthorized" }, 401);
  if ((await roleOf(phone)) !== "owner") {
    return json({ error: "owner_only" }, 403);
  }

  const prices = cleanPrices(body.prices);
  const { error } = await admin.from("app_pricing").upsert({
    id: 1,
    prices,
    edited_at: new Date().toISOString(),
  });
  if (error) return json({ error: error.message }, 400);
  return json({ ok: true, prices });
});
