// PASTE-READY, self-contained version of promote-post for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: promote-post
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/promote-post/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const admin = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

/// Resolves the caller's verified phone (E.164 digits) from their Supabase
/// session JWT. Everything that spends or grants money requires one.
async function callerPhone(req: Request): Promise<string | null> {
  const auth = req.headers.get("Authorization");
  if (!auth) return null;
  const token = auth.replace("Bearer ", "");
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) return null;
  const phone = data.user.phone ?? "";
  return phone ? phone.replace(/\D/g, "") : null;
}

// Verification for the signed payloads Apple hands us: StoreKit 2 transactions
// (which the app forwards after a purchase) and App Store Server Notifications
// V2 (which Apple POSTs to us directly).
//
// Both are JWS with the full certificate chain in the `x5c` header — leaf,
// intermediate, root — so they can be verified offline. That's why this
// project needs no App Store Connect API key: nothing here calls Apple.
//
// Trusting a payload requires ALL of:
//   1. the pinned Apple root is the last cert in the chain,
//   2. each cert is really signed by the next one up (a chain with Apple's
//      root pasted on the end but an attacker's leaf must NOT pass),
//   3. every cert is inside its validity window,
//   4. the JWS signature verifies against the leaf's public key.
//
// Step 2 is the one that matters most: without it, pinning the root proves
// nothing — anyone could append the real (public) Apple root to a chain they
// forged and sign with their own key.

/// Apple Root CA - G3, DER base64.
/// From https://www.apple.com/certificateauthority/AppleRootCA-G3.cer
/// SHA-256 63:34:3A:BF:B8:9A:6A:03:EB:B5:7E:9B:3F:5F:A7:BE:7C:4F:5C:75:6F:30:17:B3:A8:C4:88:C3:65:3E:91:79
/// Valid 2014-04-30 through 2039-04-30.
const APPLE_ROOT_CA_G3 =
  "MIICQzCCAcmgAwIBAgIILcX8iNLFS5UwCgYIKoZIzj0EAwMwZzEbMBkGA1UEAwwSQXBwbGUg" +
  "Um9vdCBDQSAtIEczMSYwJAYDVQQLDB1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTET" +
  "MBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwHhcNMTQwNDMwMTgxOTA2WhcNMzkw" +
  "NDMwMTgxOTA2WjBnMRswGQYDVQQDDBJBcHBsZSBSb290IENBIC0gRzMxJjAkBgNVBAsMHUFw" +
  "cGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYD" +
  "VQQGEwJVUzB2MBAGByqGSM49AgEGBSuBBAAiA2IABJjpLz1AcqTtkyJygRMc3RCV8cWjTnHc" +
  "FBbZDuWmBSp3ZHtfTjjTuxxEtX/1H7YyYl3J6YRbTzBPEVoA/VhYDKX1DyxNB0cTddqXl5dv" +
  "MVztK517IDvYuVTZXpmkOlEKMaNCMEAwHQYDVR0OBBYEFLuw3qFYM4iapIqZ3r6966/ayySr" +
  "MA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMAoGCCqGSM49BAMDA2gAMGUCMQCD" +
  "6cHEFl4aXTQY2e3v9GwOAEZLuN+yRhHFD/3meoyhpmvOwgPUnPWTxnS4at+qIxUCMG1mihDK" +
  "1A3UT82NQz60imOlM27jbdoXt2QfyFMm+YhidDkLF1vLUagM6BgD56KyKA==";

class JwsError extends Error {}

const b64ToBytes = (b64: string): Uint8Array =>
  Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));

const b64urlToBytes = (s: string): Uint8Array => {
  const pad = s.length % 4 === 0 ? "" : "=".repeat(4 - (s.length % 4));
  return b64ToBytes(s.replace(/-/g, "+").replace(/_/g, "/") + pad);
};

// --- Minimal DER walking ----------------------------------------------------
// Only enough to pull four things out of a certificate: the tbsCertificate
// bytes (what the signature covers), the signature algorithm OID, the
// signature itself, and the SubjectPublicKeyInfo. A full ASN.1 library would
// be overkill and another dependency to trust.

interface Tlv {
  tag: number;
  content: Uint8Array;
  /// The complete element including its header — what gets hashed.
  full: Uint8Array;
  end: number;
}

function readTlv(buf: Uint8Array, offset: number): Tlv {
  if (offset + 2 > buf.length) throw new JwsError("truncated DER");
  const tag = buf[offset];
  let len = buf[offset + 1];
  let headerLen = 2;
  if (len & 0x80) {
    const count = len & 0x7f;
    if (count === 0 || count > 4) throw new JwsError("bad DER length");
    len = 0;
    for (let i = 0; i < count; i++) len = (len << 8) | buf[offset + 2 + i];
    headerLen = 2 + count;
  }
  const start = offset + headerLen;
  const end = start + len;
  if (end > buf.length) throw new JwsError("DER overrun");
  return {
    tag,
    content: buf.subarray(start, end),
    full: buf.subarray(offset, end),
    end,
  };
}

function children(seq: Uint8Array): Tlv[] {
  const out: Tlv[] = [];
  let offset = 0;
  while (offset < seq.length) {
    const tlv = readTlv(seq, offset);
    out.push(tlv);
    offset = tlv.end;
  }
  return out;
}

const oidToString = (bytes: Uint8Array): string => {
  const parts = [Math.floor(bytes[0] / 40), bytes[0] % 40];
  let value = 0;
  for (let i = 1; i < bytes.length; i++) {
    value = (value << 7) | (bytes[i] & 0x7f);
    if (!(bytes[i] & 0x80)) {
      parts.push(value);
      value = 0;
    }
  }
  return parts.join(".");
};

const OID_ECDSA_SHA256 = "1.2.840.10045.4.3.2";
const OID_ECDSA_SHA384 = "1.2.840.10045.4.3.3";
const OID_P256 = "1.2.840.10045.3.1.7";
const OID_P384 = "1.3.132.0.34";

interface ParsedCert {
  tbs: Uint8Array;
  sigAlgOid: string;
  signature: Uint8Array;
  spki: Uint8Array;
  curveOid: string;
  notBefore: Date;
  notAfter: Date;
}

/// Parses the handful of certificate fields the chain check needs.
function parseCertificate(der: Uint8Array): ParsedCert {
  const cert = readTlv(der, 0);
  const [tbs, sigAlg, sigBits] = children(cert.content);
  if (!tbs || !sigAlg || !sigBits) throw new JwsError("malformed certificate");

  const sigAlgOid = oidToString(children(sigAlg.content)[0].content);
  // A BIT STRING's first content byte counts unused trailing bits (0 here).
  const signature = sigBits.content.subarray(1);

  const tbsParts = children(tbs.content);
  // tbsCertificate ::= [0] version, serial, signature, issuer, validity,
  //                    subject, subjectPublicKeyInfo, ...
  // The version tag is context-specific [0] and optional, so find the
  // validity/spki by position after accounting for it.
  const versioned = tbsParts[0].tag === 0xa0 ? 1 : 0;
  const validity = tbsParts[versioned + 3];
  const spkiTlv = tbsParts[versioned + 5];
  if (!validity || !spkiTlv) throw new JwsError("malformed tbsCertificate");

  const [nb, na] = children(validity.content);
  const parseTime = (tlv: Tlv): Date => {
    const s = new TextDecoder().decode(tlv.content);
    // UTCTime is YYMMDDHHMMSSZ; GeneralizedTime is YYYYMMDDHHMMSSZ.
    const full = tlv.tag === 0x17
      ? (Number(s.slice(0, 2)) >= 50 ? "19" : "20") + s
      : s;
    return new Date(
      `${full.slice(0, 4)}-${full.slice(4, 6)}-${full.slice(6, 8)}T` +
        `${full.slice(8, 10)}:${full.slice(10, 12)}:${full.slice(12, 14)}Z`,
    );
  };

  const spkiParts = children(spkiTlv.content);
  const algParams = children(spkiParts[0].content);
  const curveOid = algParams[1] ? oidToString(algParams[1].content) : "";

  return {
    tbs: tbs.full,
    sigAlgOid,
    signature,
    spki: spkiTlv.full,
    curveOid,
    notBefore: parseTime(nb),
    notAfter: parseTime(na),
  };
}

/// ECDSA X.509 signatures are DER SEQUENCE{r,s}; WebCrypto wants the raw
/// fixed-width r‖s pair.
function derSigToRaw(der: Uint8Array, size: number): Uint8Array {
  const seq = readTlv(der, 0);
  const [r, s] = children(seq.content);
  const out = new Uint8Array(size * 2);
  const place = (int: Uint8Array, offset: number) => {
    // Strip the leading zero DER adds to keep the integer positive.
    let bytes = int;
    while (bytes.length > size && bytes[0] === 0) bytes = bytes.subarray(1);
    out.set(bytes, offset + size - bytes.length);
  };
  place(r.content, 0);
  place(s.content, size);
  return out;
}

const curveName = (oid: string): string => {
  if (oid === OID_P256) return "P-256";
  if (oid === OID_P384) return "P-384";
  throw new JwsError(`unsupported curve ${oid}`);
};

const hashFor = (sigAlgOid: string): string => {
  if (sigAlgOid === OID_ECDSA_SHA256) return "SHA-256";
  if (sigAlgOid === OID_ECDSA_SHA384) return "SHA-384";
  throw new JwsError(`unsupported signature algorithm ${sigAlgOid}`);
};

/// Widens a byte array to the `BufferSource` WebCrypto's types ask for.
///
/// TypeScript 5.7 made `Uint8Array` generic over its backing buffer, so
/// `Uint8Array<ArrayBufferLike>` — what `Uint8Array.from` and friends produce —
/// no longer satisfies `BufferSource`, which wants `ArrayBufferView<ArrayBuffer>`.
/// The bytes are identical; only the type parameter differs. Named so the
/// reason is written down once instead of a bare cast at each call.
const bufferOf = (bytes: Uint8Array): BufferSource => bytes as BufferSource;

const importSpki = (cert: ParsedCert): Promise<CryptoKey> =>
  crypto.subtle.importKey(
    "spki",
    bufferOf(cert.spki),
    { name: "ECDSA", namedCurve: curveName(cert.curveOid) },
    false,
    ["verify"],
  );

/// True when [child] really was signed by [parent].
async function signedBy(child: ParsedCert, parent: ParsedCert): Promise<boolean> {
  const hash = hashFor(child.sigAlgOid);
  const key = await importSpki(parent);
  const size = curveName(parent.curveOid) === "P-384" ? 48 : 32;
  return crypto.subtle.verify(
    { name: "ECDSA", hash },
    key,
    bufferOf(derSigToRaw(child.signature, size)),
    bufferOf(child.tbs),
  );
}

interface VerifyOptions {
  /// Pinned trust anchor, DER base64. Defaults to Apple's root; overridable so
  /// the tests can drive the same code with a throwaway chain.
  rootCertificate?: string;
  /// Treat certificate validity windows as of this instant.
  now?: Date;
}

/// Verifies an Apple-signed JWS and returns its decoded payload.
/// Throws [JwsError] if anything about the chain or signature doesn't hold.
async function verifyAppleJws(
  jws: string,
  options: VerifyOptions = {},
): Promise<Record<string, unknown>> {
  const root = options.rootCertificate ?? APPLE_ROOT_CA_G3;
  const now = options.now ?? new Date();

  const parts = jws.split(".");
  if (parts.length !== 3) throw new JwsError("not a compact JWS");
  const [headerB64, payloadB64, signatureB64] = parts;

  const header = JSON.parse(new TextDecoder().decode(b64urlToBytes(headerB64)));
  if (header.alg !== "ES256") throw new JwsError(`unexpected alg ${header.alg}`);
  const x5c: string[] = header.x5c ?? [];
  if (x5c.length < 2) throw new JwsError("missing certificate chain");

  if (x5c[x5c.length - 1] !== root) {
    throw new JwsError("chain is not anchored to the pinned Apple root");
  }

  const certs = x5c.map((c) => parseCertificate(b64ToBytes(c)));

  for (const cert of certs) {
    if (now < cert.notBefore || now > cert.notAfter) {
      throw new JwsError("certificate outside its validity window");
    }
  }

  // Walk leaf -> ... -> root. Pinning the anchor is worthless without this:
  // Apple's root is public, so anyone can append it to a forged chain.
  for (let i = 0; i < certs.length - 1; i++) {
    if (!(await signedBy(certs[i], certs[i + 1]))) {
      throw new JwsError(`certificate ${i} is not signed by its issuer`);
    }
  }

  const leaf = certs[0];
  const signingKey = await importSpki(leaf);
  const ok = await crypto.subtle.verify(
    { name: "ECDSA", hash: "SHA-256" },
    signingKey,
    bufferOf(b64urlToBytes(signatureB64)),
    bufferOf(new TextEncoder().encode(`${headerB64}.${payloadB64}`)),
  );
  if (!ok) throw new JwsError("signature does not verify");

  return JSON.parse(new TextDecoder().decode(b64urlToBytes(payloadB64)));
}

// Starts (or extends) a paid placement on one of the caller's OWN public
// posts, after VERIFYING the store receipt.
//
// The owner's ask was "a custom ad system... so I can allow users to pay to
// advertise their post" — the app's own inventory, sold to its own users,
// separate from the AdMob banners on the two public surfaces.
//
// Promoting a post is a digital good bought inside the app, so it bills
// through the App Store as a CONSUMABLE, exactly like a creator subscription
// or an Okay AI pass: Apple does not know WHICH post it was for, so the app
// tells us the post and hands over the signed transaction (JWS) Apple gave
// it. We verify Apple's signature ourselves, refuse a product that is not a
// promotion tier, refuse a receipt already consumed, refuse a post that is
// not the caller's, and only THEN write the row. `post_promotions` has no
// client write policy of any kind — this function, running as the service
// role, is its only writer, so a modified client can change what it draws but
// cannot buy itself reach.
//
// POST { postId, jws } -> { until, days }


const BUNDLE_ID = Deno.env.get("APNS_BUNDLE_ID") ?? "com.okaymessaging";
const DAY_MS = 24 * 3600 * 1000;
// com.okaymessaging.promote.tier0.week … tier3.week
const PROMOTE = /\.promote\.tier([0-3])\.week$/;

// How many days each tier buys. Paying more buys more DAYS, never a better
// slot — there is no auction here, so there is nothing to outbid and no
// reason for the serving side to read what was spent.
const DAYS_FOR_TIER = [3, 7, 14, 30];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  const me = await callerPhone(req);
  if (!me) return json({ error: "unauthorized" }, 401);

  let postId = "";
  let jws = "";
  try {
    const body = await req.json();
    postId = String(body.postId ?? "").trim();
    jws = String(body.jws ?? "");
  } catch {
    return json({ error: "invalid body" }, 400);
  }
  if (!postId || !jws) return json({ error: "missing post or receipt" }, 400);

  let payload: Record<string, unknown>;
  try {
    payload = await verifyAppleJws(jws);
  } catch (e) {
    // A token that doesn't verify is the whole threat model. Say no, and
    // don't leak which check failed.
    if (e instanceof JwsError) return json({ error: "invalid receipt" }, 400);
    throw e;
  }

  if (payload.bundleId !== BUNDLE_ID) return json({ error: "wrong app" }, 400);

  const productId = String(payload.productId ?? "");
  const tierMatch = PROMOTE.exec(productId);
  if (!tierMatch) return json({ error: "not a promotion" }, 400);
  const days = DAYS_FOR_TIER[Number(tierMatch[1])] ?? DAYS_FOR_TIER[0];

  const txnId = String(payload.transactionId ?? "");
  if (!txnId) return json({ error: "incomplete receipt" }, 400);

  // You may only promote your OWN post. Checked against the row rather than
  // trusted from the request: otherwise anybody could buy a placement for
  // somebody else's post, which is a way to put words in their mouth at the
  // top of a timeline.
  const { data: post } = await admin
    .from("public_posts")
    .select("author_phone")
    .eq("id", postId)
    .maybeSingle();
  if (!post) return json({ error: "unknown post" }, 404);
  if (post.author_phone !== me) return json({ error: "not your post" }, 403);

  // A sanctioned account cannot buy its way back onto the timeline. The read
  // policy hides the placement anyway, but refusing the CHARGE is the honest
  // order — taking the money and hiding the ad would be worse.
  const { data: silenced } = await admin.rpc("is_silenced", { p: me });
  if (silenced === true) return json({ error: "account restricted" }, 403);

  // Refuse a receipt already banked, so one purchase cannot promote many.
  const { data: seen } = await admin
    .from("promote_receipts")
    .select("txn_id")
    .eq("txn_id", txnId)
    .maybeSingle();
  if (seen) return json({ error: "receipt already used" }, 409);

  // Extend from whatever is left, so buying again stacks rather than resets.
  const { data: existing } = await admin
    .from("post_promotions")
    .select("until, spent_cents")
    .eq("post_id", postId)
    .maybeSingle();
  const now = Date.now();
  const curMs = existing?.until ? Date.parse(existing.until as string) : 0;
  const base = curMs > now ? curMs : now;
  const until = new Date(base + days * DAY_MS).toISOString();

  // What Apple actually charged, when the receipt says. Never used to rank —
  // it is for the promoter's own screen.
  const price = Number(payload.price ?? 0);
  const paidCents = Number.isFinite(price) && price > 0
    ? Math.round(price / 1000)
    : 0;

  await admin.from("post_promotions").upsert({
    post_id: postId,
    promoter_phone: me,
    until,
    spent_cents: Number(existing?.spent_cents ?? 0) + paidCents,
    updated_at: new Date(now).toISOString(),
  });
  await admin.from("promote_receipts").insert({ txn_id: txnId });

  return json({ until, days });
});
