import Flutter
import Foundation

#if canImport(FoundationModels)
  import FoundationModels
#endif

/// A one-shot "write a message for me" draft, generated by the model on this
/// device rather than the hosted `ai-chat` function.
///
/// Same shape and same two guards as `SmartReplies.swift` (`canImport` at
/// compile time, `@available` at runtime) and the same honesty: nothing here
/// leaves the device, and it takes only the caller's INSTRUCTION — never a
/// conversation, because this channel has no way to see one and must never
/// grow one. `AiAssistant.draft()` on the Dart side reaches for this first and
/// falls back to the hosted function when it declines, so the fallback is the
/// same one-shot shape either way — going on-device changes where the words
/// come from, never what they see.
enum AiDraft {
  static func register(with messenger: FlutterBinaryMessenger) {
    let channel = FlutterMethodChannel(name: "okay/aidraft", binaryMessenger: messenger)
    channel.setMethodCallHandler { call, result in
      switch call.method {
      case "available":
        result(isAvailable)
      case "draft":
        guard let args = call.arguments as? [String: Any],
          let instruction = args["instruction"] as? String
        else {
          result(FlutterError(
            code: "bad_args", message: "instruction required", details: nil))
          return
        }
        draft(instruction: instruction, result: result)
      default:
        result(FlutterMethodNotImplemented)
      }
    }
  }

  /// Whether this device can generate at all — see `SmartReplies.isAvailable`
  /// for the three reasons it may not be (OS, hardware, or the model being
  /// off or still downloading). Identical check: it is the same on-device
  /// model answering a different question.
  static var isAvailable: Bool {
    #if canImport(FoundationModels)
      if #available(iOS 26.0, *) {
        return SystemLanguageModel.default.availability == .available
      }
      return false
    #else
      return false
    #endif
  }

  private static func draft(instruction: String, result: @escaping FlutterResult) {
    #if canImport(FoundationModels)
      if #available(iOS 26.0, *) {
        Task {
          do {
            let session = LanguageModelSession(instructions: systemInstructions)
            let response = try await session.respond(to: instruction)
            let text = response.content.trimmingCharacters(in: .whitespacesAndNewlines)
            await MainActor.run {
              text.isEmpty
                ? result(FlutterError(code: "unavailable", message: "no draft", details: nil))
                : result(text)
            }
          } catch {
            // A guardrail refusal or an instruction that overran the context
            // window. Both are "couldn't draft that", which the Dart side
            // already treats as a normal reason to fall back to ai-chat.
            await MainActor.run {
              result(FlutterError(code: "unavailable", message: "no draft", details: nil))
            }
          }
        }
        return
      }
    #endif
    result(FlutterError(
      code: "unsupported", message: "on-device model unavailable", details: nil))
  }

  private static let systemInstructions = """
    You are drafting a short message a person could send in a private chat, \
    based on what they tell you they want to say. Reply with ONLY the \
    message text itself — no preamble, no quotation marks, no explanation.

    Keep it natural, like something a person would actually type, not a form \
    letter. Never invent facts, names, times, or details the instruction did \
    not give you.
    """
}
