import Flutter
import UIKit

/// Changing the app's home-screen icon.
///
/// `setAlternateIconName` is iOS 10.3+ and `supportsAlternateIcons` is the
/// same, both far below this app's iOS 15 floor, so unlike `.banner` and
/// `setBadgeCount` neither needs an `#available` guard. (Stated rather than
/// left implicit: two archives have already been lost to that mistake.)
///
/// The icons themselves live in `Assets.xcassets` as `AppIcon-<Name>`
/// alternate sets, generated by `tool/build_app_icons.dart` and declared to
/// the asset compiler by `ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES` in
/// the Runner target. Nothing here names one: the list comes from Dart, so
/// there is one place a variant is added.
///
/// **iOS shows its own "You have changed the icon for OkayMessenger" alert**
/// after a successful change. There is no public way to suppress it, so the
/// picker says it is coming rather than letting it arrive as a surprise.
enum OkayAppIcon {
  static func register(messenger: FlutterBinaryMessenger) {
    let channel = FlutterMethodChannel(
      name: "okay/appicon", binaryMessenger: messenger)
    channel.setMethodCallHandler { call, result in
      switch call.method {
      case "available":
        result(UIApplication.shared.supportsAlternateIcons)
      case "current":
        // nil is the PRIMARY icon, which is not an alternate and has no name.
        // Empty string is what Dart reads as "the one the app ships with".
        result(UIApplication.shared.alternateIconName ?? "")
      case "set":
        let name = (call.arguments as? [String: Any])?["name"] as? String ?? ""
        guard UIApplication.shared.supportsAlternateIcons else {
          result(false)
          return
        }
        UIApplication.shared.setAlternateIconName(name.isEmpty ? nil : name) {
          error in
          // The completion can arrive off the main thread; a Flutter result
          // must not.
          DispatchQueue.main.async { result(error == nil) }
        }
      default:
        result(FlutterMethodNotImplemented)
      }
    }
  }
}
