import Flutter
import Foundation

#if canImport(FoundationModels)
  import FoundationModels
#endif

/// Three suggested replies, generated by the model on this device.
///
/// TWO GUARDS, NOT ONE. `canImport` is the compile-time guard: the framework
/// only exists in the iOS 26 SDK, so a build machine on an older Xcode has to
/// be able to compile this file into a stub rather than fail. `@available` is
/// the runtime guard: the app's deployment target is iOS 13, so most of the
/// phones that run this binary have no such framework to call into. Either
/// guard alone leaves a way to break the build or the app.
///
/// Nothing here leaves the device. The transcript arrives from Dart, goes into
/// the on-device model, and the replies come back — no network, no logging of
/// message text, and no `print` of anything derived from it.
enum SmartReplies {
  static func register(with messenger: FlutterBinaryMessenger) {
    let channel = FlutterMethodChannel(
      name: "okay/smartreplies", binaryMessenger: messenger)
    channel.setMethodCallHandler { call, result in
      switch call.method {
      case "available":
        result(isAvailable)
      case "suggest":
        guard let args = call.arguments as? [String: Any],
          let transcript = args["transcript"] as? String
        else {
          result(FlutterError(
            code: "bad_args", message: "transcript required", details: nil))
          return
        }
        let contact = (args["contact"] as? String) ?? ""
        suggest(transcript: transcript, contact: contact, result: result)
      default:
        result(FlutterMethodNotImplemented)
      }
    }
  }

  /// Whether this device can generate at all.
  ///
  /// Three separate reasons it may not be: the OS is older than the framework,
  /// the hardware is not eligible for Apple Intelligence (an iPhone 15 Pro is,
  /// a base iPhone 15 is not), or the user has it turned off or the model is
  /// still downloading. They all mean the same thing to the caller.
  static var isAvailable: Bool {
    #if canImport(FoundationModels)
      if #available(iOS 26.0, *) {
        return SystemLanguageModel.default.availability == .available
      }
      return false
    #else
      return false
    #endif
  }

  private static func suggest(
    transcript: String, contact: String, result: @escaping FlutterResult
  ) {
    #if canImport(FoundationModels)
      if #available(iOS 26.0, *) {
        Task {
          do {
            let session = LanguageModelSession(instructions: instructions(for: contact))
            let response = try await session.respond(
              to: transcript, generating: SuggestedReplies.self)
            let replies = response.content
            await MainActor.run {
              result([replies.first, replies.second, replies.third])
            }
          } catch {
            // A guardrail refusal, or a transcript that overran the context
            // window despite Dart's cap. Both are "no suggestions", which the
            // Dart side already treats as ordinary.
            await MainActor.run {
              result(FlutterError(
                code: "unavailable", message: "no suggestions", details: nil))
            }
          }
        }
        return
      }
    #endif
    result(FlutterError(
      code: "unsupported", message: "on-device model unavailable", details: nil))
  }

  private static func instructions(for contact: String) -> String {
    let them = contact.trimmingCharacters(in: .whitespacesAndNewlines)
    let name = them.isEmpty ? "the other person" : them
    return """
      You are suggesting replies a person could send in a private chat with \
      \(name). You will be shown the end of their conversation, with each line \
      labelled by who wrote it. "Me" is the person you are writing for.

      Write three replies they might plausibly send next. Keep each one under \
      eight words and make it sound like a person typing on a phone, not an \
      assistant. The three should differ from each other — if one agrees, \
      another might ask something or decline.

      Never invent facts, plans, times, or names that are not in the \
      conversation. If you are unsure what a reply should say, prefer a short \
      neutral acknowledgement over a specific one.
      """
  }
}

#if canImport(FoundationModels)
  /// The shape the model fills in.
  ///
  /// Three named fields rather than an array of three, because guided
  /// generation guarantees the *shape*: with three fields there is no way to
  /// come back with two replies or four, and no count constraint to get wrong.
  @available(iOS 26.0, *)
  @Generable
  struct SuggestedReplies {
    @Guide(description: "A short, natural reply — at most eight words.")
    var first: String

    @Guide(description: "A different short reply, at most eight words.")
    var second: String

    @Guide(description: """
      A third short reply taking a different angle from the first two — \
      a question, or a polite no. At most eight words.
      """)
    var third: String
  }
#endif
