import 'dart:io';

/// Generates `docs/run_all_sql.sql` — the whole schema as ONE paste.
///
/// **Why this exists.** The bundle used to be assembled by hand, once, with
/// no generator. It went stale immediately and silently: by the time anybody
/// checked it was missing THIRTY-ODD migrations, including load-bearing
/// security ones (`directory_phone_privacy.sql`, `moderation_scopes.sql`,
/// `audit_log_immutable.sql`). An owner pasting it would have got a partial
/// schema and no warning. A generator plus a test that the committed file
/// matches its output is the only thing that stops that happening again.
///
/// **The order is a dependency order, not alphabetical.** A function body is
/// parsed at CREATE time, so a file whose policy calls `is_locked_out` has to
/// come after the file that defines it; this repo has already shipped that
/// bug once. Most of the list below is taken verbatim from `tool/check_sql.sh`
/// — the order that is actually verified against a real Postgres — with the
/// files that check does not assert on slotted in where they belong.
const List<String> orderedFiles = [
  // The base schema: tables the rest of the files add to.
  'supabase/schema.sql',
  // Cloud sync's own table, and the directory's reachability columns —
  // `find_by_username` and `find_by_phone`, which every later definition of
  // find_people filters on.
  'docs/supabase_setup.sql',
  'docs/directory_privacy.sql',
  // Roles, sanctions and the append-only audit trail. Everything downstream
  // leans on is_locked_out / is_silenced, so these come early.
  'docs/platform_moderation.sql',
  'docs/audit_log_immutable.sql',
  // Identity (the blue check) and the money tables.
  'docs/identity_verification.sql',
  'docs/identity_name_match.sql',
  'docs/identity_directory_badge.sql',
  'docs/chargeback_bans.sql',
  'docs/iap_subscriptions.sql',
  'docs/storage_usage_setup.sql',
  // The public surfaces.
  'docs/public_feed.sql',
  'docs/creator_subscriptions.sql',
  'docs/payment_controls.sql',
  'docs/directory_numberless.sql',
  'docs/identity_backup.sql',
  'docs/account_lifecycle.sql',
  'docs/admin_users.sql',
  'docs/community_posts.sql',
  'docs/ai_usage.sql',
  'docs/ai_training.sql',
  'docs/legal_documents.sql',
  'docs/public_feed_edit.sql',
  'docs/public_feed_avatars.sql',
  'docs/public_forum.sql',
  'docs/public_forum_comment_votes.sql',
  'docs/community_notes.sql',
  'docs/public_market.sql',
  'docs/market_reviews.sql',
  'docs/paid_servers.sql',
  'docs/banned_signups.sql',
  'docs/public_servers.sql',
  'docs/market_upsert_fix.sql',
  // Central authority, phases 1-4.
  'docs/community_structure.sql',
  'docs/community_voice.sql',
  'docs/chat_structure.sql',
  'docs/server_messages.sql',
  'docs/user_items.sql',
  'docs/call_presence.sql',
  'docs/app_pricing.sql',
  'docs/taken_signups.sql',
  'docs/email_account_bans.sql',
  'docs/moderation_scopes.sql',
  'docs/promoted_posts.sql',
  // The directory rules come LAST, and that is deliberate: find_people is
  // defined four times and the last definition wins, so these two must not
  // be overtaken by an earlier one.
  'docs/directory_phone_privacy.sql',
  'docs/public_profiles.sql',
  // Storage bucket policies. The BUCKETS themselves are a dashboard step.
  'docs/chat_backup_bucket.sql',
  'docs/market_media_bucket.sql',
  'docs/voice_notes_bucket.sql',
];

/// Deliberately NOT in the bundle, each for a reason worth stating rather
/// than leaving somebody to wonder.
const Map<String, String> excluded = {
  'docs/run_all_sql.sql': 'this file',
  'docs/delete_numberless_accounts.sql':
      'destructive and one-off — deletes accounts, run deliberately or not '
          'at all',
  'docs/grant_owner.sql':
      'grants the owner role to one phone number, which has to be edited '
          'before it is run',
  'docs/verify_setup.sql':
      'a read-only check, not a migration — run it after this if you want '
          'the receipt',
};

const String outputPath = 'docs/run_all_sql.sql';

String build() {
  final b = StringBuffer()
    ..writeln('-- ${'=' * 74}')
    ..writeln('-- OkayMessenger — the whole schema, as one paste.')
    ..writeln('--')
    ..writeln('-- GENERATED by tool/build_run_all_sql.dart. Do not edit by '
        'hand: a test')
    ..writeln('-- fails if this file stops matching the generator, which is '
        'what stops it')
    ..writeln('-- going stale the way the hand-assembled version did (it '
        'silently fell')
    ..writeln('-- thirty-odd migrations behind, security ones included).')
    ..writeln('--')
    ..writeln('-- Paste the whole thing into the Supabase SQL editor and run '
        'it. Every')
    ..writeln('-- statement is idempotent (create-or-replace / if-not-exists '
        '/ drop-if-')
    ..writeln('-- exists), so re-running is safe and is how you apply '
        'whatever is new.')
    ..writeln('--')
    ..writeln('-- The ORDER matters and is not alphabetical: a function body '
        'is parsed at')
    ..writeln('-- CREATE time, so a policy calling is_locked_out has to come '
        'after the file')
    ..writeln('-- that defines it. It is the order tool/check_sql.sh verifies '
        'against a')
    ..writeln('-- real Postgres.')
    ..writeln('--')
    ..writeln('-- STILL A DASHBOARD STEP afterwards: create the Storage '
        'buckets')
    ..writeln('-- (chat-backups, market-media, voice-notes, public-media). '
        'The policies for')
    ..writeln('-- them are included here; the buckets themselves are not '
        'SQL.')
    ..writeln('--')
    ..writeln('-- NOT included, on purpose:');
  excluded.forEach((path, why) => b.writeln('--   $path — $why'));
  b
    ..writeln('-- ${'=' * 74}')
    ..writeln();

  for (final path in orderedFiles) {
    final file = File(path);
    if (!file.existsSync()) {
      stderr.writeln('missing: $path');
      exitCode = 1;
      continue;
    }
    b
      ..writeln()
      ..writeln('-- ${'#' * 68}')
      ..writeln('-- ## $path')
      ..writeln('-- ${'#' * 68}')
      ..writeln(file.readAsStringSync().trimRight())
      ..writeln();
  }
  return b.toString();
}

void main(List<String> args) {
  final text = build();
  if (args.contains('--check')) {
    final current =
        File(outputPath).existsSync() ? File(outputPath).readAsStringSync() : '';
    if (current != text) {
      stderr.writeln('$outputPath is stale — run: dart $outputPath');
      exitCode = 1;
      return;
    }
    stdout.writeln('$outputPath is up to date');
    return;
  }
  File(outputPath).writeAsStringSync(text);
  stdout.writeln('wrote $outputPath (${orderedFiles.length} files, '
      '${text.split('\n').length} lines)');
}
