import 'dart:io';

/// Builds the dashboard-paste copies of the Edge Functions.
///
/// The Supabase dashboard editor has no `_shared/` folder, so a function that
/// imports one fails to bundle ("Module not found"). These copies inline the
/// shared helpers. They used to be maintained by hand and drifted: the
/// platform fee still read 1.5% + 0¢ long after the shared helper moved to
/// 3.4% + 35¢, which would have deployed a fee below Stripe's own cut.
/// Generating them removes the chance of that happening twice — `flutter test`
/// fails if a copy on disk doesn't match what this produces.
///
/// Run after touching anything under `supabase/functions/`:
///
///     dart tool/paste_functions.dart

const pasteFunctions = [
  'payments-create-intent',
  'payments-onboard',
  'payments-status',
  'payments-webhook',
  'payments-account-session',
  'payments-connect-fields',
  'payments-intent-status',
  'payments-history',
  'payments-settings',
  'payments-payout',
  'payments-topup',
  'payments-wallet-pay',
  'iap-validate',
  'iap-notify',
  'creator-subscribe',
  'community-subscribe',
  'iap-status',
  'identity-start',
  'identity-status',
  'moderation-status',
  'moderation-act',
  'moderation-queue',
  'moderation-screen',
  'pages',
  // No _shared imports of its own — it is here so the dashboard copy is
  // regenerated with the source rather than drifting from it, which it did.
  'push-send',
  'delete-account',
  'turn-credentials',
  'roles-set',
  'ai-chat',
  'ai-feedback',
  'legal-set',
  'pricing-set',
  // No _shared imports either — listed so the dashboard copy is regenerated
  // with the source rather than being pasted once and forgotten.
  'sports',
];

/// Whatever the paste copy's own header should say for [name].
String _header(String name) => '''
// PASTE-READY, self-contained version of $name for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: $name
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/$name/index.ts with the _shared/
// helpers inlined (the paste editor has no shared files). Edit the sources,
// then re-run the tool.
''';

/// Matches an import/export that pulls from a sibling `_shared` file, in
/// either the function sources (`../_shared/x.ts`) or a shared file's own
/// re-export (`./x.ts`).
final _sharedRef = RegExp(r'''from\s+["'](?:\.\./_shared|\.)/(\w+)\.ts["']''');

/// The `_shared/*.ts` files [source] refers to, in order of appearance.
List<String> sharedImportsOf(String source) =>
    [for (final m in _sharedRef.allMatches(source)) m.group(1)!];

/// One shared helper file, stripped of its `export` keywords, its own leading
/// comment block, and any line referring to another shared file (those get
/// inlined separately, so a re-export would be a dangling import).
String sharedInline(String sharedSource) {
  final lines = sharedSource.split('\n');
  final start = lines.indexWhere((l) => l.startsWith('import '));
  return lines
      .sublist(start < 0 ? 0 : start)
      .where((l) => !_sharedRef.hasMatch(l))
      .map((l) => l.startsWith('export ') ? l.substring('export '.length) : l)
      .join('\n')
      .trim();
}

/// Every shared file reachable from [name], dependencies first, no repeats.
List<String> resolveShared(
  String name,
  String Function(String) readShared, {
  Set<String>? seen,
}) {
  seen ??= <String>{};
  if (!seen.add(name)) return const [];
  return [
    for (final dep in sharedImportsOf(readShared(name)))
      ...resolveShared(dep, readShared, seen: seen),
    name,
  ];
}

/// The function's own source with every `_shared/` import removed — their
/// contents are inlined above it instead.
String functionInline(String source) {
  final out = <String>[];
  var skipping = false;
  for (final line in source.split('\n')) {
    if (line.startsWith('import ') && line.contains('_shared/')) continue;
    if (line.startsWith('import {') && !line.contains('from')) {
      skipping = true; // multi-line import block
      continue;
    }
    if (skipping) {
      if (line.contains('from')) skipping = false;
      continue;
    }
    out.add(line);
  }
  return out.join('\n').trim();
}

/// The full contents of the paste copy for [name]. [readShared] returns the
/// source of `_shared/<name>.ts`, so tests can drive this from memory.
String buildPasteCopy(
  String name, {
  required String Function(String) readShared,
  required String functionSource,
}) {
  final shared = <String>{};
  for (final dep in sharedImportsOf(functionSource)) {
    shared.addAll(resolveShared(dep, readShared));
  }
  final inlined =
      [for (final s in shared) sharedInline(readShared(s))].join('\n\n');
  return '${_header(name)}\n$inlined\n\n${functionInline(functionSource)}\n';
}

void main() {
  String readShared(String n) =>
      File('supabase/functions/_shared/$n.ts').readAsStringSync();
  for (final name in pasteFunctions) {
    final source = File('supabase/functions/$name/index.ts').readAsStringSync();
    File('docs/edge_functions_paste/$name.ts').writeAsStringSync(
      buildPasteCopy(name, readShared: readShared, functionSource: source),
    );
    stdout.writeln('wrote docs/edge_functions_paste/$name.ts');
  }
}
