import 'dart:io';

/// Builds the dashboard-paste copies of the payment Edge Functions.
///
/// The Supabase dashboard editor has no `_shared/` folder, so a function that
/// imports one fails to bundle. These copies inline the shared helpers. They
/// used to be maintained by hand and drifted: the platform fee sat at the old
/// 1.5% + 0¢ long after the shared helper moved to 3.4% + 35¢, which would
/// have deployed a fee below Stripe's own cut. Generating them removes the
/// chance of that happening twice — `flutter test` fails if a copy on disk
/// doesn't match what this produces.
///
/// Run after touching anything under `supabase/functions/`:
///
///     dart tool/paste_functions.dart

const pasteFunctions = [
  'payments-create-intent',
  'payments-onboard',
  'payments-status',
  'payments-webhook',
];

/// Whatever the paste copy's own header should say for [name].
String _header(String name) => '''
// PASTE-READY, self-contained version of $name for the Supabase
// Dashboard editor (Edge Functions -> Deploy a new function -> Via Editor).
// Name the function EXACTLY: $name
//
// GENERATED by tool/paste_functions.dart — do not edit by hand. It is the
// logic of supabase/functions/$name/index.ts with the
// _shared/stripe.ts helpers inlined (the paste editor has no shared files).
// Edit the sources, then re-run the tool.
''';

/// The shared helpers, stripped of their `export` keywords and file header so
/// they can sit at the top of a single-file function.
String sharedInline(String sharedSource) {
  final lines = sharedSource.split('\n');
  // Everything from the first import onward; the leading comment block is
  // about the shared file itself and doesn't belong in a paste copy.
  final start = lines.indexWhere((l) => l.startsWith('import '));
  return lines
      .sublist(start)
      .map((l) => l.startsWith('export ') ? l.substring('export '.length) : l)
      .join('\n')
      .trim();
}

/// The function's own source with its `_shared/stripe.ts` import removed.
String functionInline(String source) {
  final lines = source.split('\n');
  final out = <String>[];
  var skipping = false;
  for (final line in lines) {
    if (line.startsWith('import ') && line.contains('_shared/stripe.ts')) {
      continue; // single-line import
    }
    if (line.startsWith('import {') && !line.contains('from')) {
      skipping = true; // multi-line import block
      continue;
    }
    if (skipping) {
      if (line.contains('_shared/stripe.ts')) skipping = false;
      continue;
    }
    out.add(line);
  }
  return out.join('\n').trim();
}

/// The full contents of the paste copy for [name].
String buildPasteCopy(
  String name, {
  required String sharedSource,
  required String functionSource,
}) =>
    '${_header(name)}\n'
    '${sharedInline(sharedSource)}\n\n'
    '${functionInline(functionSource)}\n';

void main() {
  final shared = File('supabase/functions/_shared/stripe.ts').readAsStringSync();
  for (final name in pasteFunctions) {
    final source = File('supabase/functions/$name/index.ts').readAsStringSync();
    File('docs/edge_functions_paste/$name.ts').writeAsStringSync(
      buildPasteCopy(name, sharedSource: shared, functionSource: source),
    );
    stdout.writeln('wrote docs/edge_functions_paste/$name.ts');
  }
}
